### ISSUE TITLE
Using discriminator inheritance with query cache fail

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean#1020]
If I use a single table inheritance strategy with a discriminator column and I enable the query cache for those entities I get the following exception:

14:16:09.763 [main] DEBUG io.ebean.SUM - txn[1008] FindMany type[ProductConfiguration] origin[B7ksR1.BgNS7.gQlGn] exeMicros[11663] rows[2] predicates[] bind[]
nullnull
java.lang.ClassCastException: org.tests.inheritance.model.ProductConfiguration cannot be cast to org.tests.inheritance.model.GroupConfiguration

	at org.tests.inheritance.TestInheritanceDiscriminatorQueryCache.testDiscriminatorQueryCache(TestInheritanceDiscriminatorQueryCache.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

I'll create a pull request (#1021) for this with a test case that demonstrates the problem.

**Comment by rbygrave** [comment]
Fix pushed to master, closing.
