### ISSUE TITLE
id.eq(id) will throw NullPointerException when use @SoftDelete

### ISSUE THREAD

**Issue by someok** [ebean-orm/ebean#1049]
Query success:
```java
User user1 = User.find
    .query()
    .setIncludeSoftDeletes()
    .setId(id)
    .findOne();

assertThat(user1.isDeleted()).isTrue();
```

Query success:
```java
User user2 = new QUser()
    .setIncludeSoftDeletes()
    .setId(id)
    .findOne();
assertThat(user2.isDeleted()).isTrue();
```

NullPointerException:
```java
User user3 = new QUser()
    .setIncludeSoftDeletes()
    .id.equalTo(id)
    .findOne();
assertThat(user3.isDeleted()).isTrue();
```

error:
```
java.lang.NullPointerException
	at io.onote.service.UserServiceTest.crud(UserServiceTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
```

I think `id.eq` should like `setId` method?

**Comment by rPraml** [comment]
NPE happens in your test class `at io.onote.service.UserServiceTest.crud(UserServiceTest.java:47)` this is most likely this line `.id.equalTo(id)`
Increase debug level of querybean-agent and check if UserServiceTest is properly enhanced

**Comment by someok** [comment]
I found the problem is caused by `ebean.mf`.

Change `entity-packages: com.example.model` to `entity-packages: com.example`.

because enchance the all method that invoke type query bean:
> ebean-enhance> cls: com/example/service/UserService  msg: enhanced - getfield calls replaced

**Comment by rbygrave** [comment]
This should be closed then -  Closing.
