### ISSUE TITLE
enum json read error

### ISSUE THREAD

**Issue by icode** [ebean-orm/ebean#1074]
```
objectMapper.enable(SerializationFeature.WRITE_ENUMS_USING_INDEX);

@Entity
public class Action extends Model {
    @Id
    @GeneratedValue
    public long id;
    /**
     * 动作类型
     */
    public Type type;
    /**
     * 结果类型
     */
    public Integer resultType;
    /**
     * 动作名称
     */
    public String name;
    /**
     * 动作目标 <br>
     * class名或url,使用${[UnitResultBody].propName}占位符
     */
    public String target;
    /**
     * 参数 <br>
     * HTTP类型是请求body使用${UnitResultBody.{propName}}占位符 <br>
     * CLASS类型则参数必须为JSON字符串并在实例化时转化为构造器参数 <br>
     * public Test(Arg arg) ==Arg==> {"name":"test"} <br>
     */
    public String argument;

    /**
     * 动作类型
     */
    public enum Type {
        /**
         * class 类型
         */
        CLASS,
        /**
         * http GET 方法
         */
        GET,
        /**
         * http POST 方法
         */
        POST,
        /**
         * http PUT 方法
         */
        PUT,
        /**
         * http DELETE 方法
         */
        DELETE,
        /**
         * http PATCH 方法
         */
        PATCH,
        /**
         * http HEAD 方法
         */
        HEAD,
        /**
         * http OPTIONS 方法
         */
        OPTIONS
    }
}
```

```console
 18:38:08.648 [Grizzly-worker(4)] INFO  ameba.dev.logging - 1621 * Server has received a request on thread Grizzly-worker(4)
1621 > POST http://172.17.0.1:8889/assistant/action
1621 > accept: application/json, text/javascript, */*; q=0.01
1621 > accept-encoding: gzip, deflate
1621 > accept-language: zh-CN,zh;q=0.8
1621 > cache-control: no-cache
1621 > connection: keep-alive
1621 > content-length: 400
1621 > content-type: application/json
1621 > host: 172.17.0.1:8889
1621 > origin: http://172.17.0.1:8889
1621 > pragma: no-cache
1621 > referer: http://172.17.0.1:8889/view/manager.html?type=%E6%89%80%E6%9C%89%E7%B1%BB%E5%9E%8B&name=&op=eq
1621 > user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
1621 > x-requested-with: XMLHttpRequest
{"type":2,"resultType":1,"name":"fetch_rain","target":"http://192.168.1.225:9200/reports_pro/document/_search","argument":"{\n   \"query\": {\n      \"match_phrase\": {\n         \"title\": {\n            \"query\": \"${schema.botMergedSlots[0].originalWord} ${schema.botMergedSlots[1].originalWord}\",\n            \"slop\": 0,\n            \"analyzer\" : \"keyword\"\n         }\n      }\n   }\n}"}

18:38:14.147 [Grizzly-worker(4)] ERROR a.m.error.DefaultExceptionMapper - 系统错误 > http://172.17.0.1:8889/assistant/action
java.lang.IllegalArgumentException: No enum constant com.sinitek.kanyanbao.models.Action.Type.2
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.ebeaninternal.server.type.ScalarTypeEnumStandard$EnumBase.parse(ScalarTypeEnumStandard.java:221)
	at io.ebeaninternal.server.type.ScalarTypeEnumStandard$EnumBase.jsonRead(ScalarTypeEnumStandard.java:236)
	at io.ebeaninternal.server.deploy.BeanProperty.jsonRead(BeanProperty.java:1382)
	at io.ebeaninternal.server.deploy.BeanDescriptorJsonHelp.jsonReadProperties(BeanDescriptorJsonHelp.java:144)
	at io.ebeaninternal.server.deploy.BeanDescriptorJsonHelp.jsonReadObject(BeanDescriptorJsonHelp.java:124)
	at io.ebeaninternal.server.deploy.BeanDescriptorJsonHelp.jsonRead(BeanDescriptorJsonHelp.java:93)
	at io.ebeaninternal.server.deploy.BeanDescriptor.jsonRead(BeanDescriptor.java:3045)
	at io.ebeaninternal.server.text.json.DJsonContext.toBean(DJsonContext.java:124)
	at io.ebeaninternal.server.text.json.DJsonContext.toBean(DJsonContext.java:115)
	at ameba.db.ebean.jackson.BeanTypeDeserializer.deserialize(BeanTypeDeserializer.java:37)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:97)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:80)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:73)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:92)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:133)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:102)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:186)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rbygrave** [comment]
No, go away and come back with a proper unit test.
