### ISSUE TITLE
Migration broken in 10.4.6 due different classpath-scanner version

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1131]
DbMigration is broken in 10.4.6 due update to classpath-scanner 2.2.4
ebean-migration 10.2.1 still depends on 2.2.2 

## Workaround
In the meantime I reverted back to classpath-scanner 2.2.2

## How to fix: 
Make new release of ebean-migration based on classpath-scanner 2.2.4

```console
	  java.lang.NoClassDefFoundError: org/avaje/classpath/scanner/Scanner
    at io.ebean.migration.runner.LocalMigrationResources.readResources(LocalMigrationResources.java:45) ~[ebean-migration-10.2.1.jar:na]
    at io.ebean.migration.MigrationRunner.run(MigrationRunner.java:98) ~[ebean-migration-10.2.1.jar:na]
    at io.ebean.migration.MigrationRunner.run(MigrationRunner.java:89) ~[ebean-migration-10.2.1.jar:na]
    at io.ebean.migration.MigrationRunner.run(MigrationRunner.java:67) ~[ebean-migration-10.2.1.jar:na]
    at io.ebean.config.ServerConfig.runDbMigration(ServerConfig.java:2821) ~[ebean-10.4.6-FOC1.jar:10.4.6-FOC1]
    at io.ebeaninternal.server.core.DefaultServer.start(DefaultServer.java:391) ~[ebean-10.4.6-FOC1.jar:10.4.6-FOC1]
```

**Comment by rbygrave** [comment]
ebean-migration 10.3.1 uses the 2.2.4 scanner, that is now released.  

The fix for this is then to use ebean-migration 10.3.1.
