### ISSUE TITLE
NoSuchMethodError: javax.persistence.Embedded.prefix()Ljava/lang/String;

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1139]
When using EE 7 the standard JPA API does not have the prefix() option on Embedded.  As such we get:

```console
Caused by: java.lang.NoSuchMethodError: javax.persistence.Embedded.prefix()Ljava/lang/String;
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocOnes.readEmbedded(AnnotationAssocOnes.java:202)
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocOnes.readAssocOne(AnnotationAssocOnes.java:61)
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocOnes.parse(AnnotationAssocOnes.java:44)
	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readAssociations(ReadAnnotations.java:78)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1189)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:711)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:326)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:141)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:140)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
```

**Comment by rbygrave** [comment]
Reproduce via exclusion:
```xml
    <dependency>
      <groupId>io.ebean</groupId>
      <artifactId>ebean</artifactId>
      <version>11.1.1-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>io.ebean</groupId>
          <artifactId>persistence-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
