### ISSUE TITLE
Error when applied disjunction to filterMany

### ISSUE THREAD

**Issue by diegocolombo** [ebean-orm/ebean#1182]
## Expected behavior
Apply the due filter to the many relation

## Actual behavior
A NullPointerException occurs

### Steps to reproduce
Use any method that returns a Junction after declaring filterMany
```java
 query.filterMany(entity).or()
                .eq("userPermissions.userId", user.getId())
                .in("userGroupPermissions.groupId", user.getGroups())
                .in("companyPermissions.companyId", user.getCompanies());
```

```console
  java.lang.NullPointerException: null
	at io.ebeaninternal.server.expression.DefaultExpressionList.<init>(DefaultExpressionList.java:72) ~[ebean-11.2.3.jar:?]
	at io.ebeaninternal.server.expression.JunctionExpression.<init>(JunctionExpression.java:50) ~[ebean-11.2.3.jar:?]
	at io.ebeaninternal.server.expression.DefaultExpressionFactory.junction(DefaultExpressionFactory.java:582) ~[ebean-11.2.3.jar:?]
	at io.ebeaninternal.server.expression.DefaultExpressionList.junction(DefaultExpressionList.java:999) ~[ebean-11.2.3.jar:?]
	at io.ebeaninternal.server.expression.DefaultExpressionList.disjunction(DefaultExpressionList.java:1046) ~[ebean-11.2.3.jar:?]
	at io.ebeaninternal.server.expression.DefaultExpressionList.or(DefaultExpressionList.java:1031) ~[ebean-11.2.3.jar:?]
```

**Comment by rbygrave** [comment]
Thanks, will be fixed in release 11.3.1
