### ISSUE TITLE
Remove support for PropertyChangeListener from entity beans

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1198]
Entity beans have PropertyChangeListener support.  I announced this on the forum with no feedback to suggest anyone needs or want this so will remove this feature.

**Comment by rPraml** [comment]
>  I announced this on the forum with no feedback to suggest anyone needs or want this so will remove this feature.
Oh... I did not see the announcement. I have some cases where I still use this. I think it's a good point to migrate my existing code.

**Comment by buckfeng** [comment]
This change seemed to break the [example-springboot](https://github.com/ebean-orm-examples/example-springboot.git)

The following exception was thrown at line `return EbeanServerFactory.create(config)`

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ebeanFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)Ljava/beans/PropertyChangeEvent;
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1634)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 58 common frames omitted
Caused by: java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)Ljava/beans/PropertyChangeEvent;
	at org.example.sboot.domain.BaseModel._ebean_set_id(BaseModel.java:1)
	at org.example.sboot.domain.BaseModel.<init>(BaseModel.java:20)
	at org.example.sboot.domain.Content.<init>(Content.java:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.ebeaninternal.server.deploy.BeanDescriptor.createPrototypeEntityBean(BeanDescriptor.java:581)
	at io.ebeaninternal.server.deploy.BeanDescriptor.<init>(BeanDescriptor.java:418)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:790)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:340)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:152)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:140)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:107)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:66)
	at org.example.sboot.service.EbeanFactoryBean.getObject(EbeanFactoryBean.java:44)
	at org.example.sboot.service.EbeanFactoryBean.getObject(EbeanFactoryBean.java:17)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 67 common frames omitted
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.222 sec <<< FAILURE! - in org.example.sboot.service.WiringTest
