### ISSUE TITLE
NPE with TxType `SUPPORTS`

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/ebean#1213]
## Expected behavior

No exception

## Actual behavior

`NullPointerException` encountered

### Steps to reproduce

```java
    @Transactional(type = TxType.SUPPORTS)
    private List<World> doUpdate(int q) {
        List<World> retVal = new ArrayList<>(q);
        for (int i = 0; i < q; ++i) {
            retVal.add(findAndModifyOne());
        }
        dao.save(retVal);
        return retVal; // <- Line 91: NPE triggered here 
    }
```

```console
java.lang.NullPointerException: null
	at io.ebeaninternal.server.core.DefaultServer.scopedTransactionExit(DefaultServer.java:766)
	at io.ebeaninternal.api.HelpScopeTrans.exit(HelpScopeTrans.java:22)
	at com.techempower.act.controller.WorldController.doUpdate(WorldController.java:91)
	at com.techempower.act.controller.WorldController.updateQueries(WorldController.java:81)
	at com.techempower.act.controller.WorldControllerMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:656)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:338)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:53)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:501)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:206)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1341)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Note** the error is encountered on `ebean-11.5.1`. If I changed to `ebean-11.4.1` then I will still get NPE with a different error log, which I believe is the same issue with #1207:

```console
java.lang.NullPointerException: null
	at io.ebeaninternal.api.SpiTransactionProxy.isActive(SpiTransactionProxy.java:189)
	at io.ebeaninternal.api.ScopedTransaction.isActive(ScopedTransaction.java:13)
	at io.ebeaninternal.server.transaction.DefaultTransactionScopeManager.get(DefaultTransactionScopeManager.java:33)
	at io.ebeaninternal.server.core.DefaultServer.scopedTransaction(DefaultServer.java:806)
	at io.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:795)
	at io.ebeaninternal.server.core.DefaultServer.scopedTransactionEnter(DefaultServer.java:762)
	at io.ebeaninternal.api.HelpScopeTrans.enter(HelpScopeTrans.java:15)
	at com.techempower.act.controller.WorldController.doUpdate(WorldController.java)
	at com.techempower.act.controller.WorldController.updateQueries(WorldController.java:81)
	at com.techempower.act.controller.WorldControllerMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:656)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:338)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:53)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:501)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:206)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1341)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rbygrave** [comment]
Fixed and push to master.

Note that there is effectively no value in explicitly using SUPPORTS with Ebean ... I wonder what you are looking to gain from using it?

**Comment by greenlaw110** [comment]
I am using ebean to support the [actframework](https://github.com/actframework/actframework) in [TechEmpower Framework Benchmark, AKA TFB](https://www.techempower.com/benchmarks/previews/round15/) tests.

The database updates score is exceptionally low (see https://www.techempower.com/benchmarks/previews/round15/#section=data-r15&hw=ph&test=update&l=zik0vz&o=6&f=1-5pfk-pa8-75-hra0hs-72gw-13ydk0-0).

There are two frameworks uses ebean in TFB: ActFramework and Play2-Java. All of them get very bad score in updates test. The test [requirement](https://www.techempower.com/benchmarks/#section=code) says:


> Use of transactions is acceptable but not required. If transactions are used, a transaction should only encapsulate a single iteration, composed of a single read and single write. Transactions should not be used to consolidate multiple iterations into a single operation.


And I found it is because Ebean always uses an implicit transaction which caused makes it very slow when comparing to other frameworks. So I was in a progress trying to hack around ebean to disable transactions. Obviously this is not possible. Never mind anyway.
