### ISSUE TITLE
Add IDENTITY support for Oracle platform (since 12c Oracle supports auto generated identity)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1243]
```sql
create table customer (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);
```
Currently Ebean does not support IDENTITY with Oracle and will only use SEQUENCE.  When trying to use:
```java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
Integer id;

We get an exception:
```console
Caused by: java.sql.SQLSyntaxErrorException: ORA-02289: sequence does not exist

  at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
  at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
  at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
  at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
  ....
```

**Comment by rbygrave** [comment]
Note that the default for Oracle is still SEQUENCE.  It might be good to be able to configure that ... and we can't do that yet.
