### ISSUE TITLE
SpringJdbcTransactionManager inifinite recursion

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/ebean#1254]
## Actual behavior

When no current Spring transaction exists, `currentTransaction` crashes due to infinite recursion with `SpringJdbcTransactionManager.getCurrentTransaction()` calling `TransactionManager.get()` which calls `ExternalTransactionScopeManager.get()` which calls back to `SpringJdbcTransactionManager.getCurrentTransaction()`.

## Expected behavior

Something sane happens -- not sure if the check in `SpringJdbcTransactionManager` to see if a native Ebean transaction exists that can be used is still relevant or if it should just return null.

### Steps to reproduce

```java
  @Test
  public void springTxnManager() {
    ServerConfig config = new ServerConfig();
    config.setRegister(false);
    config.getDataSourceConfig().setUrl("jdbc:h2:mem:ebean-test;DB_CLOSE_ON_EXIT=FALSE");
    config.getDataSourceConfig().setUsername("h2");
    config.getDataSourceConfig().setPassword("");
    config.getDataSourceConfig().setDriver(org.h2.Driver.class.getName());
    config.setExternalTransactionManager(new SpringJdbcTransactionManager());
    EbeanServer server = EbeanServerFactory.create(config);
    try {
      server.currentTransaction(); // infinite recursion -> StackOverflowError
    } finally {
      server.shutdown(true, false);
    }
  }
```

ebean-11.10.2
ebean-spring-txn-11.10.1

**Comment by rbygrave** [comment]
```console
java.lang.StackOverflowError
	at org.springframework.transaction.support.TransactionSynchronizationUtils.unwrapResourceIfNecessary(TransactionSynchronizationUtils.java:62)
	at org.springframework.transaction.support.TransactionSynchronizationManager.getResource(TransactionSynchronizationManager.java:137)
	at io.ebean.spring.txn.SpringJdbcTransactionManager.getCurrentTransaction(SpringJdbcTransactionManager.java:69)
	at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.get(ExternalTransactionScopeManager.java:44)
	at io.ebeaninternal.server.transaction.TransactionManager.get(TransactionManager.java:205)
	at io.ebean.spring.txn.SpringJdbcTransactionManager.getCurrentTransaction(SpringJdbcTransactionManager.java:73)
	at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.get(ExternalTransactionScopeManager.java:44)
	at io.ebeaninternal.server.transaction.TransactionManager.get(TransactionManager.java:205)
	at io.ebean.spring.txn.SpringJdbcTransactionManager.getCurrentTransaction(SpringJdbcTransactionManager.java:73)
	at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.get(ExternalTransactionScopeManager.java:44)
	at io.ebeaninternal.server.transaction.TransactionManager.get(TransactionManager.java:205)
```

**Comment by rbygrave** [comment]
Yes, I introduced this doozy issue with ..  #1245 - Refactor internals - move TransactionMangerScope to be part of TransactionManager

> Something sane happens

Yes :) ... fixed the currentTransaction() will return null (as there is no active/current transaction).

Note that the issue was (well, a missing test for one but ...) the "TransactionScopeManager" is now 'owned' by the transaction manager ... which is good and makes sense but ExternalTransactionScopeManager was written to live out by itself ... and it's get() method reflected that.  So in the new organisation where it is now owned by the transaction manager and it at the "bottom" so to speak ... it's get() method really should just look in the scope.

The fix it to have ExternalTransactionManager extend DefaultTransactionManager ... and remove all it's methods bar the registration - the effect being get() ... then just gets from scope.

**Comment by ksperling** [comment]
I'm still running into an issue where I've got a transaction with some further queries outside of the transaction being performed in the same thread afterwards. In this case `SpringJdbTransactionManager` seems to pick up the previous (now inactive) transaction via `transactionManager.getInScope()` which then causes an IllegalStateException a little later during `flushJdbcBatchOnQuery`:

```
java.lang.IllegalStateException: Transaction is Inactive
	at io.ebeaninternal.server.transaction.JdbcTransaction.flush(JdbcTransaction.java:793)
	at io.ebeaninternal.server.transaction.JdbcTransaction.flushBatch(JdbcTransaction.java:800)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.flushJdbcBatchOnQuery(DefaultOrmQueryEngine.java:62)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:181)
	at io.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:384)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1113)
	at io.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:997)
	at io.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:983)
	...
```

Unfortunately I haven't been able to track down exactly how this broke; its working OK with Ebean 10.1.6 / ebean-spring-txn 10.1.1 but fails in the latest version.

**Comment by rbygrave** [comment]
I can't reproduce with:

@Test
public void testFindNonTransactional() {
  logger.info("Finding User with OID = 1 ...");
  User user = userService.find(1);

  // makes another fetch with same thread but no current transaction ...
  User user2 = userService.findNoCurrentTransaction(2);
  logger.info("nonTransactional find user1:{} user2:{}", user, user2);
}


The first fetch uses the spring transaction .. and see that via the
'transaction id' txn[s1731763384]

10:47:35.487 [main] DEBUG io.ebean.SQL - *txn[s1731763384]* select t0.oid,
t0.name, t1.id from user t0 left join account t1 on t1.user_oid = t0.oid
where t0.oid = ?  ; --bind(1, )
10:47:35.487 [main] DEBUG io.ebean.SUM - *txn[s1731763384]* FindBean
type[User] origin[CJfs2t.A.A] exeMicros[941] rows[1] bind[1, ]
10:47:35.487 [main] DEBUG io.ebean.TXN - *txn[s1731763384]* Commit
10:47:35.488 [main] DEBUG io.ebean.SQL - *txn[1003]* select t0.oid, t0.name,
t1.id from user t0 left join account t1 on t1.user_oid = t0.oid  where
t0.oid = ?  ; --bind(2, )
10:47:35.489 [main] DEBUG io.ebean.SUM - *txn[1003]* FindBean type[User]
origin[CJfs2t.A.A] exeMicros[910] rows[1] bind[2, ]


... and the find of user 2 uses an Ebean transaction .... txn[1003]


Can you look at the tests and see how they need to be modified to reproduce?

This test is  at:
https://github.com/ebean-orm/ebean-spring-txn/blob/master/src/test/java/org/example/EbeanSpringModuleTest.java#L79


Thanks, Rob.
