### ISSUE TITLE
Not supported for @DbArray mapping when using kotlin var instead of val (wildcard enum type)

### ISSUE THREAD

**Issue by pgilmore** [ebean-orm/ebean#1282]
## Expected behavior
``` kotlin
@Entity
@Table(name = "e_kotlin_parent")
class BrokenParent(
        @Id
        val id: UUID? = null,
        @CreatedTimestamp
        val created: Instant? = null,
        @UpdatedTimestamp
        val updated: Instant? = null,
        @Version
        val version: Long? = null,
        @DbArray
        var parentTypes: Set<ParentType>
)
```
Should generate a working database model when testing

## Actual behavior

```console 
Caused by: java.lang.IllegalArgumentException: Type [? extends com.youcruit.ebean.list.kotlin.test.ParentType] not supported for @DbArray mapping
	at io.ebeaninternal.server.type.ScalarTypeArraySetH2$Factory.typeFor(ScalarTypeArraySetH2.java:48) ~[ebean-11.11.1.jar:?]
	at io.ebeaninternal.server.type.ScalarTypeArraySetH2$Factory.typeFor(ScalarTypeArraySetH2.java:25) ~[ebean-11.11.1.jar:?]
	at io.ebeaninternal.server.type.DefaultTypeManager.getArrayScalarType(DefaultTypeManager.java:354) ~[ebean-11.11.1.jar:?]
```

### Steps to reproduce

This test fails 
https://github.com/pgilmore/ebean-test/blob/master/src/test/kotlin/BrokenDBArrayTest.kt

Where as this works fine
https://github.com/pgilmore/ebean-test/blob/master/src/test/kotlin/WorkingDBArrayTest.kt

The difference between them is var vs val. The reason it fails is when using var Type valueType = this.getValueType(genericType) (DefaultTypeManager:271) does not return an Enum, instead it returns a sun.reflect.generics.reflectiveObjects.WildcardTypeImpl

**Comment by rbygrave** [comment]
Thanks, nice bug report !!  Fixed in next release.

Cheers, Rob.
