### ISSUE TITLE
NPE when delete cascade from bean with SoftDelete to imported OneToOne without SoftDelete

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1294]
### Steps to reproduce

```java
@Entity
public class ESoftDelOneA {

  @Id
  long id;

  String name;

  @OneToOne(cascade = CascadeType.ALL)
  ESoftDelOneB oneb;

  @SoftDelete
  boolean deleted;
 ...
```

```java
@Entity
public class ESoftDelOneB {

  @Id
  long id;

  String name;

  @OneToOne(mappedBy = "oneb")
  ESoftDelOneA onea;
 ...
```

```java
  ESoftDelOneA a = new ESoftDelOneA("a1");
    ESoftDelOneB b = new ESoftDelOneB("b1");

    a.setOneb(b);
    b.setOnea(a);

    Ebean.save(a);

    // delete should not cascade to ESoftDelOneB as this is a
    // soft delete and ESoftDelOneB doesn't have soft delete flag
    Ebean.delete(a);
```

```console
 java.lang.NullPointerException
	at io.ebeaninternal.server.deploy.BeanDescriptor.setSoftDeleteValue(BeanDescriptor.java:2714)
	at io.ebeaninternal.server.core.PersistRequestBean.prepareForSoftDelete(PersistRequestBean.java:766)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:749)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNoBatch(PersistRequestBean.java:792)
	at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:783)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:814)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:547)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:527)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRecurse(DefaultPersister.java:340)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteAssocOne(DefaultPersister.java:1270)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:817)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:547)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:527)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:519)
	at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1761)
	at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1752)
	at io.ebean.Ebean.delete(Ebean.java:664)
	at org.tests.softdelete.TestSoftDeleteOtoCascade.test(TestSoftDeleteOtoCascade.java:31)
```

**Comment by rbygrave** [comment]
Fix in DefaultPersister.deleteAssocOne() ...
