### ISSUE TITLE
Ebean 11.12.1 broken when using ScalarTypeConverter with enum

### ISSUE THREAD

**Issue by pgilmore** [ebean-orm/ebean#1329]
## Expected behavior
```kotlin
@Entity
@Table(name = "e_kotlin_parent")
class BrokenParent(
        @Id
        val id: UUID? = null,
        @CreatedTimestamp
        val created: Instant? = null,
        @UpdatedTimestamp
        val updated: Instant? = null,
        @Version
        val version: Long? = null,
        @DbArray
        var parentTypes: Set<ParentType>,
        val type: TypeEnum
)
```
Should generate a working database model even when there is a ScalarTypeWrapper for TypeEnum

## Actual behavior

This fails as the getScalarType(enumType) method returns String from the wrapper and not a ScalarTypeEnum<?> which is expected.

```console 
ava.lang.RuntimeException: Error reading annotations for com.youcruit.ebean.list.kotlin.test.BrokenParent

	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:60)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.createDeployBeanInfo(BeanDescriptorManager.java:1298)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentInitial(BeanDescriptorManager.java:713)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:356)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:154)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:139)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at BrokenDBArrayTest.setupEbean(BrokenDBArrayTest.kt:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: io.ebeaninternal.server.type.ScalarTypeWrapper cannot be cast to io.ebeaninternal.server.type.ScalarTypeEnum
	at io.ebeaninternal.server.type.DefaultTypeManager.createEnumScalarType(DefaultTypeManager.java:591)
	at io.ebeaninternal.server.deploy.parse.DeployUtil.setEnumScalarType(DeployUtil.java:118)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:184)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.parse(AnnotationFields.java:116)
	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:57)
	... 31 more
```
### Steps to reproduce
This test fails
https://github.com/pgilmore/ebean-test/blob/master/src/test/kotlin/BrokenDBArrayTest.kt

**Comment by rbygrave** [comment]
Thanks.
