### ISSUE TITLE
Split SQL Server Platform into SqlServer16 and SqlServer17 (where 2017 which uses UTF8 types nvarchar etc and prefers Sequences).  

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1340]
The **SqlServer16Platform** will support the current behaviour.

The **SqlServer17Platform** will be enhanced with:
- nvarchar, nchar columns that support UTF8 
- Preference for Sequences over Identity for better JDBC batch support

When Ebean starts with SqlServer detected ... and no explicit platform choice is made Ebean will fail to start asking you to chose the preferred platform (2017 or 2018).

`For SqlServer please choose the more specific sqlserver16 or sqlserver17 platform via ServerConfig.setDatabasePlatformName. Refer to issue #1340 for details
`

```console
    javax.persistence.PersistenceException: java.lang.IllegalArgumentException: For SqlServer please choose the more specific sqlserver16 or sqlserver17 platform via ServerConfig.setDatabasePlatformName. Refer to issue #1340 for details

    at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:62)
    at io.ebeaninternal.server.core.DefaultContainer.setDatabasePlatform(DefaultContainer.java:266)
    at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:126)
    at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
    at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
    at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
    at io.ebean.config.ServerConfigSqlServerTest.need_explicitPlatform(ServerConfigSqlServerTest.java:35)

```

**Comment by wilmol** [comment]
Can you update the error message? `ServerConfig` is deprecated, I had to use `DatabaseConfig` instead.
