### ISSUE TITLE
Modularized project cannot locate ebean.properties file on Java 10

### ISSUE THREAD

**Issue by fwgreen** [ebean-orm/ebean#1367]
I think the new rule, as of Java 9, is a resource has to be located on the module path (whatever that means).  Trying to [workaround the issue](https://github.com/ebean-orm/ebean/issues/1368) by using `ServerConfig` and the `AgentLoader` doesn't work either.

```
[main] INFO io.ebean.EbeanVersion - ebean version: 11.15.4
[main] INFO io.ebean.config.properties.LoadContext - loaded properties from []
[main] WARN org.avaje.classpath.scanner.internal.scanner.classpath.ClassPathScanner - Unable to resolve location classpath:
[main] ERROR io.ebean.Ebean - Error trying to create the default EbeanServer
java.lang.RuntimeException: DataSource user is null?
	at avaje.datasource@3.2.2/org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:207)
	at avaje.datasource@3.2.2/org.avaje.datasource.core.Factory.createPool(Factory.java:15)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:334)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:278)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:117)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:88)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:202)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.<init>(Ebean.java:160)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at io.ebean@11.15.4/io.ebean.Ebean.<clinit>(Ebean.java:127)
	at io.ebean@11.15.4/io.ebean.Finder.db(Finder.java:116)
	at io.ebean@11.15.4/io.ebean.Finder.query(Finder.java:196)
	at io.ebean@11.15.4/io.ebean.Finder.all(Finder.java:165)
	at Beaner/org.fwgreen.beaner.Main.main(Main.java:7)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.ebean@11.15.4/io.ebean.Finder.db(Finder.java:116)
	at io.ebean@11.15.4/io.ebean.Finder.query(Finder.java:196)
	at io.ebean@11.15.4/io.ebean.Finder.all(Finder.java:165)
	at Beaner/org.fwgreen.beaner.Main.main(Main.java:7)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: DataSource user is null?
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.<init>(Ebean.java:165)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.<init>(Ebean.java:133)
	at io.ebean@11.15.4/io.ebean.Ebean.<clinit>(Ebean.java:127)
	... 4 more
Caused by: java.lang.RuntimeException: DataSource user is null?
	at avaje.datasource@3.2.2/org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:207)
	at avaje.datasource@3.2.2/org.avaje.datasource.core.Factory.createPool(Factory.java:15)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:334)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:278)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:117)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:88)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:202)
	at io.ebean@11.15.4/io.ebean.Ebean$ServerManager.<init>(Ebean.java:160)
	... 6 more
```

**Comment by rbygrave** [comment]
Are you able to create a maven or gradle project somewhere (github maybe) that demonstrates this issue?
Thanks, Rob.

**Comment by fwgreen** [comment]
Here's a stripped down version: https://github.com/fwgreen/ModularEbean

**Comment by fwgreen** [comment]
Thanks for your hard work!  I mentioned this issue to another developer facing a similar problem.
