### ISSUE TITLE
Bean "not enhanced" error in modularized project after successful enhancement

### ISSUE THREAD

**Issue by fwgreen** [ebean-orm/ebean#1368]
The version of ASM in the Maven Compiler Plugin isn't compatible with Java 10 so...
```Xml
<plugin>
   <artifactId>maven-compiler-plugin</artifactId>
   <version>3.7.0</version>
   <configuration>
       <source>10</source>
       <target>10</target>
   </configuration>
   <dependencies>
       <dependency>
           <groupId>org.ow2.asm</groupId>
           <artifactId>asm</artifactId>
           <version>6.1.1</version>
       </dependency>
    </dependencies>
</plugin>
```
After running `process-classes` the compiler claims success
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Beaner 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Beaner ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ Beaner ---
[INFO] Required filename-based automodules detected. Please don't publish this project to a public artifact repository!
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 4 source files to /home/francois/Documents/idea_projects/Beaner/target/classes
[INFO] /home/francois/Documents/idea_projects/Beaner/src/main/java/module-info.java: /home/francois/Documents/idea_projects/Beaner/src/main/java/module-info.java uses or overrides a deprecated API that is marked for removal.
[INFO] /home/francois/Documents/idea_projects/Beaner/src/main/java/module-info.java: Recompile with -Xlint:removal for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.549 s
[INFO] Finished at: 2018-05-01T19:52:13-04:00
[INFO] Final Memory: 14M/54M
[INFO] ------------------------------------------------------------------------
```
But trying to run the project returns...
```
[main] INFO io.ebean.EbeanVersion - ebean version: 11.15.4
[main] INFO io.ebean.config.properties.LoadContext - loaded properties from []
[main] INFO org.avaje.datasource.pool.ConnectionPool - DataSourcePool [pg] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
[main] INFO io.ebean.internal.DefaultContainer - DatabasePlatform name:pg platform:postgres
[main] ERROR io.ebeaninternal.server.deploy.BeanDescriptorManager - Error in deployment
java.lang.IllegalStateException: Bean class org.fwgreen.beaner.Person is not enhanced?
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1547)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1414)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1332)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:747)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:368)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:163)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:139)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at Beaner/org.fwgreen.beaner.Server.create(Main.java:44)
	at Beaner/org.fwgreen.beaner.Server.start(Main.java:27)
	at Beaner/org.fwgreen.beaner.Main.main(Main.java:12)
Exception in thread "main" java.lang.IllegalStateException: Bean class org.fwgreen.beaner.Person is not enhanced?
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1547)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1414)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1332)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:747)
	at io.ebean@11.15.4/io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:368)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:163)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:139)
	at io.ebean@11.15.4/io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean@11.15.4/io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at Beaner/org.fwgreen.beaner.Server.create(Main.java:44)
	at Beaner/org.fwgreen.beaner.Server.start(Main.java:27)
	at Beaner/org.fwgreen.beaner.Main.main(Main.java:12)
```

**Comment by rbygrave** [comment]
The entity bean is enhanced but not actually registered  ... that is we should explicitly do so (before it is used) via something like:
```java

ServerConfig serverConfig = new ServerConfig();
serverConfig.loadFromProperties();
serverConfig.addClass(Person.class);

EbeanServer ebeanServer = EbeanServerFactory.create(serverConfig);
```
And this should happen early in bootup before the Person bean is actually used.

That is, we can't really classpath scan for entity beans in Java 10 modular apps (and really shouldn't either so that is fine by me).

**Comment by rbygrave** [comment]
So all working on master at the moment.  Need to check DB migrations (resource loading) though so I'll look to do that sometime this week hopefully.

```java
package org.fwgreen;

import io.ebean.EbeanServer;
import io.ebean.EbeanServerFactory;
import io.ebean.config.ServerConfig;

public class Main {

	public static void main(String[] args) {

		System.out.println(Runtime.version());

		ServerConfig serverConfig = new ServerConfig();
		serverConfig.loadFromProperties();
		serverConfig.addClass(Person.class);

		EbeanServer ebeanServer = EbeanServerFactory.create(serverConfig);


		var p = new Person("asd", "asd", "asd", "asd");
		p.save();

		var  roundtrip = Person.repo.all();

		roundtrip.forEach(System.out::println);
	}
}
```

```console
/usr/lib/jvm/jdk10/bin/java -javaagent:/home/rob/apps/idea-IU-181.4445.78/lib/idea_rt.jar=40973:/home/rob/apps/idea-IU-181.4445.78/bin -Dfile.encoding=UTF-8 -p /home/rob/github/ebean-dir/examples/ModularEbean/target/classes:/home/rob/.m2/repository-pv/com/h2database/h2/1.4.196/h2-1.4.196.jar:/home/rob/.m2/repository-pv/io/ebean/persistence-api/2.2.2-SNAPSHOT/persistence-api-2.2.2-SNAPSHOT.jar:/home/rob/.m2/repository-pv/io/ebean/ebean-annotation/3.12-SNAPSHOT/ebean-annotation-3.12-SNAPSHOT.jar:/home/rob/.m2/repository-pv/io/ebean/ebean/11.15.11-SNAPSHOT/ebean-11.15.11-SNAPSHOT.jar:/home/rob/.m2/repository-pv/org/yaml/snakeyaml/1.21/snakeyaml-1.21.jar:/home/rob/.m2/repository-pv/org/avaje/avaje-datasource/3.2.2/avaje-datasource-3.2.2.jar:/home/rob/.m2/repository-pv/org/avaje/avaje-datasource-api/3.2/avaje-datasource-api-3.2.jar:/home/rob/.m2/repository-pv/org/avaje/avaje-classpath-scanner/3.1.1/avaje-classpath-scanner-3.1.1.jar:/home/rob/.m2/repository-pv/org/avaje/avaje-classpath-scanner-api/2.2/avaje-classpath-scanner-api-2.2.jar:/home/rob/.m2/repository-pv/io/ebean/ebean-migration/11.5.4/ebean-migration-11.5.4.jar:/home/rob/.m2/repository-pv/org/antlr/antlr4-runtime/4.7.1/antlr4-runtime-4.7.1.jar:/home/rob/.m2/repository-pv/com/fasterxml/jackson/core/jackson-core/2.9.5/jackson-core-2.9.5.jar:/home/rob/.m2/repository-pv/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar:/home/rob/.m2/repository-pv/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar -m postgres.exp/org.fwgreen.Main
10.0.1+10
[main] INFO io.ebean.config.properties.LoadContext - loaded properties from [ebean.properties]
[main] INFO io.ebean.EbeanVersion - ebean version: 11.15.11-SNAPSHOT
[main] INFO org.avaje.datasource.pool.ConnectionPool - DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
[main] INFO io.ebean.internal.DefaultContainer - DatabasePlatform name:db platform:h2
[main] INFO io.ebean.DDL - Executing db-create-all.sql - 2 statements
Person [firstname=asd, lastname=asd, telephone=asd, email=asd]

Process finished with exit code 0
```

**Comment by rbygrave** [comment]
Used H2 so:
```properties
ebean.ddl.generate=true
ebean.ddl.run=true
ebean.ddl.createOnly=true

datasource.default=db

#datasource.pg.username=postgres
#datasource.pg.password=abc123
#datasource.pg.databaseUrl=jdbc:postgresql://127.0.0.1:5432/sample_db?currentSchema=persons
#datasource.pg.databaseDriver=org.postgresql.Driver


datasource.db.username=sa
datasource.db.password=
datasource.db.databaseUrl=jdbc:h2:mem:tests
datasource.db.databaseDriver=org.h2.Driver
```

**Comment by rbygrave** [comment]
Noting this issue trying to use jaxb for db migration generation with Java 10 -  https://github.com/javaee/jaxb-v2/issues/1168

Somewhat of a problem now currently with both jaxb-runtime and jaxb-core sharing the same packages.  Need 2.3.1 released with this resolved I believe.
