### ISSUE TITLE
Missing @OneToOne mapping yields unusable error messages.

### ISSUE THREAD

**Issue by EgbertW** [ebean-orm/ebean#1372]
In a Play 2.6.11 application using ebean 11.7.1 I ran into an issue when using a RawSql statement. The bug was mine, but the resulting error is obnoxious and hard to trace. I have an bean class annotated with `@Sql` and `@Entity` and a reference to another `@Entity` class (Employer) of an actual database table. I forgot to add a `@OneToOne` annotation to the reference.

When executing the query, this results in a `NullPointerException` in `BeanPropertyAssocOne.buildRawSqlSelectChain` because `targetIdFinder` is null. This is the result of the missing `@OneToOne` annotation but should be caught earlier and should have thrown a different exception, IMO.

## Expected behavior

I would expect an exception telling me that the `Employer` object could not be resolved due to the lack of a relation mapping. Something like:

```
io.ebean.QueryException: no foreign key mapping for employer
	at io.ebeaninternal.server.query.SqlTree.buildRawSqlSelectChain(SqlTree.java:95)
	at io.ebeaninternal.server.query.CQueryPlanRawSql.createIndexPositions(CQueryPlanRawSql.java:31)
	at io.ebeaninternal.server.query.CQueryPlanRawSql.<init>(CQueryPlanRawSql.java:21)
	at io.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:329)
	at io.ebeaninternal.server.query.CQueryEngine.findIterate(CQueryEngine.java:195)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findIterate(DefaultOrmQueryEngine.java:127)
	at io.ebeaninternal.server.core.OrmQueryRequest.findEach(OrmQueryRequest.java:383)
	at io.ebeaninternal.server.core.DefaultServer.findEach(DefaultServer.java:1481)
```

## Actual behavior

```
java.lang.NullPointerException: null
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.buildRawSqlSelectChain(BeanPropertyAssocOne.java:324)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.buildRawSqlSelectChain(SqlTreeNodeBean.java:190)
	at io.ebeaninternal.server.query.SqlTree.buildRawSqlSelectChain(SqlTree.java:95)
	at io.ebeaninternal.server.query.CQueryPlanRawSql.createIndexPositions(CQueryPlanRawSql.java:31)
	at io.ebeaninternal.server.query.CQueryPlanRawSql.<init>(CQueryPlanRawSql.java:21)
	at io.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:329)
	at io.ebeaninternal.server.query.CQueryEngine.findIterate(CQueryEngine.java:195)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findIterate(DefaultOrmQueryEngine.java:127)
	at io.ebeaninternal.server.core.OrmQueryRequest.findEach(OrmQueryRequest.java:383)
	at io.ebeaninternal.server.core.DefaultServer.findEach(DefaultServer.java:1481)
```

### Steps to reproduce

```java
@Entity
@Sql
class EmployeeQueryResult {
    Employer employer;
    Integer numberOfEmployees
}
```

```java
RawSql sql = RawSqlBuilder
    .parse("SELECT employer_id, COUNT(id) AS numberOfEmployees FROM employee GROUP BY employer_id")
    .columnMapping("employer_id", "employer.id")
    .create();
Query<EmployeeQueryResult> query = ebeanServer
    .find(EmployeeQueryResult.class)
    .setRawSql(sql)
    .findEach(record -> { // do something; });
```

Simply adding a `@OneToOne` annotation on the `employer` field solves the problem, but the resulting exception hardly points in this direction.

**Comment by rbygrave** [comment]
Good work - thanks !!
