### ISSUE TITLE
NullPointerException when using L2 Bean cache with findOne()

### ISSUE THREAD

**Issue by phantasia15** [ebean-orm/ebean#1503]
## Expected behavior

Should not throw exception if the bean is not exist

## Actual behavior

Throw NullPointerException

### Steps to reproduce

Ebean version: 11.22.8
Annotate the model with `@Cache` annotation

```java
       query()
            .where()
            .eq("code", "NonExistCode")
            .findOne();
```
   
```console
  java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at io.ebeaninternal.server.cache.DefaultServerCache.put(DefaultServerCache.java:209)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.ebeaninternal.server.cache.DefaultServerCache.putAll(DefaultServerCache.java:199)
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.beanCachePutAllDirect(BeanDescriptorCacheHelp.java:518)
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.beanPutAll(BeanDescriptorCacheHelp.java:473)
	at io.ebeaninternal.server.deploy.BeanDescriptor.cacheBeanPutAll(BeanDescriptor.java:1465)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:144)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:452)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1571)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1245)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOne(DefaultOrmQuery.java:1469)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findOne(DefaultExpressionList.java:431)
```

**Comment by rbygrave** [comment]
Hi @phantasia15 ... there is no `@Bean` annotation.  Can you supply the model that you are using?

**Comment by rbygrave** [comment]
Ah, I see you probably editing this and are using `@Cache`, ok ta.

**Comment by rbygrave** [comment]
So I am not able to reproduce.  From the stack trace it appears one of the beans fetch does not have an Id value.

Can you produce a failing test case to reproduce this issue?

**Comment by phantasia15** [comment]
My bad, the model is indeed missing the @Id annotation.
We actually just moved some of our Java code to Kotlin and seems like the @Id were missing during the conversion. Re-adding @Id to the model and everything works as expected.
Really sorry for the confusion, I will close the issue right now.

Anyways, thank you for your great work on Ebean. Have  a nice day!
