### ISSUE TITLE
"NullPointerException" in query.copy().findList() but not in query.findList()

### ISSUE THREAD

**Issue by Marc2017** [ebean-orm/ebean#1574]
**Update**

## Expected behavior

query.copy().findList() should return the same as query.findList()

was: 
query.findCount() should return the rowcount of a query.

## Actual behavior

query.copy().findList() throws NullPointerException when fetch().findMany().in() is used.

was:
query.findCount() throws NullPointerException in some circumstances.
but query.findList() works normal on the same query.

**Additional Info (Update):**
The problem seems to be in the **query.copy()** function
query.findList() works
query.copy().findList() throws the same NullPointerException

Perhaps copy() does miss to also copy "fetch("").filterMany(...).in()" Informations?

### Steps to reproduce

1) Create a Query with a fetch().filterMany() construct
2) execute "query.copy().findList()"

was:
I was not able yet to create a testcase, but I can tell some things I saw while debugging, perhaps this allready helps?

- the query has some query.fetch(..).filterMany(...) joins
- in query.findList() it seems that they are executed within the second execution ("PlanDescriptor)
- in the query.findCount() all fetch-joins are within the first execution, whereas the "bindValues" Instance is "null" and therefore throws a NullPointerException in:

query.findCount() execution:

OrmQueryProperties.queryPlanHash(StringBuilder builder) {
...
if (filterMany != null) {
      builder.append(" filterMany[");
      **filterMany.queryPlanHash(builder);**
      builder.append("]");
    }
...
}

then

DefaultExpressionList.queryPlanHash(StringBuilder builder) {
...
for (SpiExpression aList : list) {
      **aList.queryPlanHash(builder);**
      builder.append(",");
    }
...
}

then

InExpression. queryPlanHash(StringBuilder builder) {
...
    if (!multiValueSupported) {
      // query plan specific to the number of parameters in the IN clause
      **builder.append(bindValues.size()); //bindValues is NULL -> EXCEPTION** 
    }
    builder.append("]");
...
}

**Comment by rbygrave** [comment]
You should include the stack trace.  Can you do that please?

**Comment by rbygrave** [comment]
Ok, I think the following is the stack trace you see (but good to confirm that if you can).
```
java.lang.NullPointerException
	at io.ebeaninternal.server.expression.InExpression.queryPlanHash(InExpression.java:148)
	at io.ebeaninternal.server.expression.DefaultExpressionList.queryPlanHash(DefaultExpressionList.java:613)
	at io.ebeaninternal.server.querydefn.OrmQueryProperties.queryPlanHash(OrmQueryProperties.java:496)
	at io.ebeaninternal.server.querydefn.OrmQueryDetail.queryPlanHash(OrmQueryDetail.java:75)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.planDescription(DefaultOrmQuery.java:1106)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.createQueryPlanKey(DefaultOrmQuery.java:1051)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.prepare(DefaultOrmQuery.java:1155)
	at io.ebeaninternal.server.core.OrmQueryRequest.prepareQuery(OrmQueryRequest.java:222)
	at io.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1148)
	at io.ebeaninternal.server.core.DefaultServer.createQueryRequest(DefaultServer.java:1121)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1564)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1558)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1447)
	at org.tests.query.TestQueryFilterMany.test_copy(TestQueryFilterMany.java:60)
```

**Comment by rbygrave** [comment]
Ok, I'm 99% sure I have reproduced and fixed the same issue.  You might want to check the stack trace and tests to confirm ... but yes I'll close at fixed (with the above commit).

Thanks, Rob.
