### ISSUE TITLE
Cascading update isn't propagated - use of merge() vs "stateless update"

### ISSUE THREAD

**Issue by viluon** [ebean-orm/ebean#1656]
I believe we've come across a bug with `EbeanServer.update()`. In the provided test case, an update isn't propagated to linked entities (despite `CascadeType.ALL`). This happens on Ebeans 11.22.10.

## Expected behavior
The provided unit test should pass.

## Actual behavior
The update doesn't touch a list of entities deeper within the hierarchy.

### Steps to reproduce
[This gist](https://gist.github.com/viluon/8a6dd71e1bd96068a4dd4ddfefbc9116) contains a unit test showcasing the issue. The unit test fails with the following output:
```console
java.lang.AssertionError: 
Expected :1
Actual   :2

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.somewhere.EbeanSoftDeleteTest.testEbeanBug(EbeanSoftDeleteTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rbygrave** [comment]
@viluon  did the above comment make sense?

Thanks, Rob.

**Comment by rbygrave** [comment]
@viluon  ... I'll close this for now.  I am assuming you are using `merge()` for this case rather than a `stateless update`.

**Comment by viluon** [comment]
@rbygrave thanks for the workaround, but a workaround isn't a fix. I would expect a stateless update to work with `CascadeType.ALL`. This bug is the reason why we are stuck with an older version of Ebeans, the newer versions are unusable for production due to this issue.

Note that a fix for this and another issue was proposed in https://github.com/ebean-orm/ebean/pull/1403, but was rejected due to refactoring work. The provided unit test shows that a proper solution never made it to `master`.

**Comment by viluon** [comment]
@rbygrave could you please reopen this issue to reflect the state of the bug?

**Comment by rbygrave** [comment]
> This bug is the reason why we are stuck with an older version of Ebeans

That doesn't make sense to me. You will need to expand on that ... (are you stuck on your own fork?)

>  fix for this and another issue was proposed in #1403, but was rejected 

Well that PR was closed with agreement that the issue was resolved by other changes.  That PR didn't contain **ANY** failing test case.  If that PR contained "a fix" then you could create a PR with the failing test and the associated fix and I could review that - no problem with that - why don't you do that?

> I would expect a stateless update to work with CascadeType.ALL

I believe it is more complex than that.  More specifically the ability to differentiate between an empty collection for non-cascading and an empty collection that is "remove all as orphans".  We have to be pretty careful with the behaviour here.  I believe the interesting aspect here is the orphanRemoval=true setting on the relationships which might be enough to imply that a stateless update can be "aggressive" wrt cascading collections.

Another option would be to use MergeOptions/MergeOptionsBuilder to be explicit on the paths to cascade (rather than being implicit).


`merge()` is nice and explicit with no room for interpretation - it is not clear to me why you are rejecting that option.
  
The other workaround would be to perform a stateless update on `entityRoot.foo` (as then the collection is off the "root" bean being updated).

I'll re-open but not sure when I'll get to look at it.  I would be good if you can clarify the points raised above.

Cheers, Rob.

**Comment by rbygrave** [comment]
Closing.  No feed back, expecting people to use merge() when appropriate.
Cheers, Rob.

**Comment by rbygrave** [comment]
Refer to https://github.com/ebean-orm/ebean/issues/1824 ... which is the same issue.  

PR pending.  

This is considered as a breaking change, removing the deleteMissingChildren parameter for stateless updates in favour of always honouring orphanRemoval.
