### ISSUE TITLE
Ebean try to do update child nodes instead of inserting them on cascading save resulting in OptimisticLockException

### ISSUE THREAD

**Issue by twilek** [ebean-orm/ebean#167]
When I update to Ebean 4.1.2 from 3.2.5 I starts to get OptimisticLockException on several of my integration tests when I try to save completely new entities that never been saved to the database before. This happens on objects that has OneToMany Cascading child entities and it seems like Ebean think the child objects already exists in the database and thefore determine an update shall be made instead of the correct insert.

Here is striped down version of the entities I try to save:

```
@Data
@Entity
@Table(name = "orders")
public class OrderEntity {
    @Id
    @Column(name = "uuid")
    private String id;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "order")
    private List<OrderItemEntity> items;
}

@Data
@Entity
@Table(name = "order_items")
public class OrderItemEntity {
    @Id
    @Column(name = "uuid")
    private String id;
    @Column(name = "product_variant_uuid")
    private String variantId;
    @JoinColumn(name = "order_uuid")
    @ManyToOne
    private OrderEntity order;
    private int quantity;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "orderItem")
    private List<OrderItemPropertyEntity> properties;
}
```

And the code that gives the exception looks like hits

```
OrderEntity orderEntity = new OrderEntity();
orderEntity.setId("anyOrderId");
OrderItemEntity orderItemEntity = new OrderItemEntity();
orderItemEntity.setId("anyOrderItemId");
orderItemEntity.setVariantId("anyVariantId");
orderItemEntity.setAmount(BigDecimal.ONE);
entity.setItems(toList(orderItemEntity));
getServer().save(entity);
```

This will result in this exception:

```
javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update order_items set product_variant_uuid=?, amount=?, order_uuid=? where uuid=?] bind[null]
    at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:91)
    at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:74)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66)
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:81)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:378)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:404)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:289)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:238)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocManyDetails(DefaultPersister.java:794)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveMany(DefaultPersister.java:673)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocMany(DefaultPersister.java:574)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:265)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:212)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:200)
    at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1576)
```

**Comment by fandayrockworld** [comment]
Also reproduced in version 4.4.1

**Comment by rbygrave** [comment]
You'll need to produce a test case.  This ticket has test  src/test/java/com/avaje/tests/insert/TestInsertOnStringKey.java ... and that does not fail. You'll need to create a testcase that fails on the latest version like 4.7.3

**Comment by valentincocaud** [comment]
Also repoduce in 6.2.2 with an @Id annotation on a String attribute. It's not an UUID so I can't fix with the UUID type.
https://github.com/ebean-orm/avaje-ebeanorm/issues/378
