### ISSUE TITLE
Wrong SQL generated when using setDistinct and order by on aggregated column

### ISSUE THREAD

**Issue by shubhamp-zeotap** [ebean-orm/ebean#1746]
## Actual behavior

This is the model I am using
```
@Data
@Entity
@Table(name = "segments")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@AllArgsConstructor
@NoArgsConstructor
public class PartialSegment extends Model {

    @Id
    @Column(name = "id")
    private Long id;

    @NotNull
    @Index
    @Column(name = "segment_id_zat")
    private Long segmentIdZat;

    @Index
    @ManyToOne
    @JoinColumn(name = "segment_status_id", referencedColumnName = "status_id", nullable = false)
    private SegmentStatus status;

    @NotNull
    @Column(name = "product_type", nullable = false, columnDefinition = "varchar(255) default 'target'")
    String productType = "target";

    public static final Finder<Long, PartialSegment> find = new Finder<Long, PartialSegment>(PartialSegment.class);
}
```

And I am querying it like this:
```
        Ebean.find(PartialSegment.class).setDistinct(true)
                .select("segmentIdZat, min(status)")
                .where().eq("segmentIdZat", 108L)
                .orderBy("min(status) asc nulls last")
                .findList();
```

This is generating a wrong SQL with ```nulls last``` somehow coming in the select clause
```
javax.persistence.PersistenceException: Query threw SQLException:ERROR: syntax error at or near "nulls"
  Position: 89 Bind values:[108] Query was:select distinct t0.segment_id_zat, min(t0.segment_status_id), min(t0.segment_status_id) nulls last from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat order by min(t0.segment_status_id) nulls last
```

The wrong SQL is getting generated only on the following pre-conditions:
1) setDistinct(true) is enabled
2) order by is done on an aggregate column like ```min(status)```
3) sort order is ASC/asc (desc is working fine)

In all other cases the SQL generated in correct.

This is the stack trace of the exception
```
javax.persistence.PersistenceException: Query threw SQLException:ERROR: syntax error at or near "nulls"
  Position: 89 Bind values:[108] Query was:select distinct t0.segment_id_zat, min(t0.segment_status_id), min(t0.segment_status_id) nulls last from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat order by min(t0.segment_status_id) nulls last
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:52)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:223)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:149)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.translate(DefaultOrmQueryEngine.java:43)
	at io.ebeaninternal.server.core.OrmQueryRequest.translate(OrmQueryRequest.java:103)
	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:701)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:411)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:133)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:451)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1552)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1528)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1526)
	at services.SegmentListingService.listSegments(SegmentListingService.java:43)
	at controllers.SegmentControllerV2.listSegments(SegmentControllerV2.java:66)
	at v2.Routes$$anonfun$routes$1.$anonfun$applyOrElse$6(Routes.scala:102)
	at play.core.routing.HandlerInvokerFactory$$anon$9.resultCall(HandlerInvoker.scala:155)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:116)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:131)
	at play.mvc.Action.lambda$call$0(Action.java:89)
	at java.util.Optional.map(Optional.java:215)
	at play.mvc.Action.call(Action.java:81)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
	at play.mvc.Action.call(Action.java:66)
	at actions.AuthorizedAccessAction.call(AuthorizedAccessAction.java:16)
	at actions.AuthenticatedAccessAction.call(AuthenticatedAccessAction.java:27)
	at play.mvc.Action.lambda$call$0(Action.java:89)
	at java.util.Optional.map(Optional.java:215)
	at play.mvc.Action.call(Action.java:81)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:191)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:79)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:72)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.impl.Promise.transform(Promise.scala:33)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
	at scala.concurrent.Future$.apply(Future.scala:658)
	at play.core.j.JavaAction.apply(JavaAction.scala:192)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:98)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "nulls"
  Position: 89
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.ebeaninternal.server.query.CQuery.prepareResultSet(CQuery.java:377)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:325)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:320)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:384)
	... 59 more
```

## Expected behavior

When sort order is changed to desc
```
        Ebean.find(PartialSegment.class)
                .select("segmentIdZat, min(status)").setDistinct(true)
                .where().eq("segmentIdZat", 108L)
                .order("min(status) desc nulls last")
                .findList();
```

This is SQL generation which is the actual expected behaviour:
```
[debug] io.ebean.SQL - txn[1001] select distinct t0.segment_id_zat, min(t0.segment_status_id), min(t0.segment_status_id) from segments t0 where t0.segment_id_zat = ? group by t0.segment_id_zat order by min(t0.segment_status_id) desc nulls last; --bind(108)
```

But this SQL generation has ```min(t0.segment_status_id)``` still coming twice in the select clause which again is an issue in itself.

**Comment by rbygrave** [comment]
As a side note ...
```java
    @Index
    @ManyToOne
```
You might want to have a look to see if there are 2 indexes on `segment_status_id`.  That is, by  default Ebean will generate an index on foreign key constraint columns.  We don't generally have `@Index` with `@ManyToOne`.

Cheers, Rob.

**Comment by rbygrave** [comment]
As a side note ...
```java
    @ManyToOne
    @JoinColumn(name = "segment_status_id", referencedColumnName = "status_id", nullable = false)
    private SegmentStatus status;
```
It looks like the `@JoinColumn` could be removed as those columns match the default naming convention.  So instead we could just put optional = false on the ManyToOne like - `@ManyToOne(optional=false)` ... to get the `nullable = false` part.

**Comment by rbygrave** [comment]
**Background notes:**
This relates back to https://github.com/ebean-orm/ebean/issues/85 ... the behaviour of Ebean with a query that has `distinct` and `order by` is to ensure that the properties included in the order by are part of the select clause.

- This only applies for `select distinct`
- For a lot of cases this behaviour isn't needed at all (all the properties in the order by are part of the select clause already)
- #85 Is the issue/case that this behaviour "fixes" (by including the order by properties in the select clause)
- When the order by isn't "safe for use in the select clause" by including `nulls` or `collate` Ebean will produce incorrect sql which is this bug

Note: TestPview.test:23 and TestOrderByWithDistinctTake2.testWithAscAndDesc:60 are the tests that barf if we don't add to the select clause.

-----
So the "fix" I think is appropriate is that for the `select distinct` case Ebean should only automatically add the `order by` to the `select clause` when the order by is deemed "safe for use in select" meaning the order by doesn't contain `nulls` or `collate` options.

There is possibly an argument that Ebean shouldn't add to the select clause for this case but the issue raised by #85 is a realistic example of when this behaviour is good.  The order by includes a related / joined column but we don't wish to load that part of the graph.

**Comment by shubhamp-zeotap** [comment]
Thanks a lot, Rob! That makes sense.
