### ISSUE TITLE
GregorianCalendar no register

### ISSUE THREAD

**Issue by BrettCao** [ebean-orm/ebean#1786]
### Steps to reproduce

```java
orderDetails.deliveryTime.before(c2);
```

```console
2019-08-08 08:35:10.893 ERROR 24396 --- [orker-thread-11] com.diandou.handles.FailureHandler       : javax.persistence.PersistenceException: No ScalarType registered for class java.util.GregorianCalendar
	at io.ebeaninternal.server.persist.Binder.getScalarType(Binder.java:206)
	at io.ebeaninternal.server.persist.Binder.bindObject(Binder.java:232)
	at io.ebeaninternal.server.expression.DefaultExpressionRequest.bind(DefaultExpressionRequest.java:71)
	at io.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:168)
	at io.ebeaninternal.server.query.CQueryPredicates.bind(CQueryPredicates.java:119)
	at io.ebeaninternal.server.query.CQueryRowCount.findCount(CQueryRowCount.java:119)
	at io.ebeaninternal.server.query.CQueryEngine.findCount(CQueryEngine.java:173)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findCount(DefaultOrmQueryEngine.java:89)
	at io.ebeaninternal.server.core.OrmQueryRequest.findCount(OrmQueryRequest.java:412)
	at io.ebeaninternal.server.core.DefaultServer.findCountWithCopy(DefaultServer.java:1309)
	at io.ebeaninternal.server.core.DefaultServer.findCount(DefaultServer.java:1296)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findCount(DefaultOrmQuery.java:1489)
	at io.ebean.typequery.TQRootBean.findCount(TQRootBean.java:1802)
	at com.diandou.http.controllers.OrderController.orderOnlineView(OrderController.kt:160)
	at com.diandou.routes.web.OrderWeb$20.handle(OrderWeb.kt:54)
	at com.diandou.routes.web.OrderWeb$20.handle(OrderWeb.kt:11)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:154)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.lambda$authorizeUser$3(AuthHandlerImpl.java:219)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorize(AuthHandlerImpl.java:107)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorizeUser(AuthHandlerImpl.java:213)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:125)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:154)
	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:256)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$0(SessionHandlerImpl.java:171)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$2(SessionHandlerImpl.java:202)
	at io.vertx.ext.web.sstore.impl.ClusteredSessionStoreImpl.lambda$null$0(ClusteredSessionStoreImpl.java:90)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:34)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rbygrave** [comment]
Why are you using GregorianCalendar in your entity beans rather one of the type from javax.time like Instant, OffsetDateTime, ZonedDateTime etc.

GregorianCalendar, Calendar, java.util.Date are all mutable types which means that there are relatively poor choices in terms of types to use - they are not "immutable value types".

Can you not use one of the types from javax.time instead?

**Comment by rbygrave** [comment]
I'll close for now.  Please re-open when you have answers / thoughts on the above questions. 

Ta, Rob.
