### ISSUE TITLE
Kotlin: Generating collection with wildcard type - Get error BeanNotRegisteredException: Error with association to [null] from [...Foo.manyProperty]. Is null registered?

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1804]
This is an issue when a collection is defined with a wildcard like like:
```
@OneToMany
List<? extends Customer> customers;
```

We don't normally use this but Kotlin can effectively compile to this.

```
Caused by: io.ebean.config.BeanNotRegisteredException: Error with association to [null] from [com.admin.system.domain.SysUser.roles]. Is null registered? See https://ebean.io/docs/trouble-shooting#not-registered
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocManys.setBeanTable(AnnotationAssocManys.java:479)
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocManys.readToMany(AnnotationAssocManys.java:454)
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocManys.read(AnnotationAssocManys.java:106)
	at io.ebeaninternal.server.deploy.parse.AnnotationAssocManys.parse(AnnotationAssocManys.java:67)
	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readAssociations(ReadAnnotations.java:50)

```

**Comment by rbygrave** [comment]
Related to https://github.com/ebean-orm/ebean/issues/1803

**Comment by rbygrave** [comment]
Failing test: TestOneToManyWildcard
```
Caused by: io.ebean.config.BeanNotRegisteredException: Error with association to [null] from [org.tests.o2m.OMParentWithWild.related]. Is null registered? See https://ebean.io/docs/trouble-shooting#not-registered
```
