### ISSUE TITLE
Q: Ebean supports redshift database

### ISSUE THREAD

**Issue by hiteshzeotap** [ebean-orm/ebean#1828]
I am trying to connect redshift database using ebean. Is ebean supports redshift?
I am facing below error:

[info] play.api.Play - Application started (Dev)
[error] io.ebean.Ebean - Error trying to create the default EbeanServer
java.lang.RuntimeException: DataSource user is null?
	at org.avaje.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:207)
	at org.avaje.datasource.core.Factory.createPool(Factory.java:15)
	at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:334)
	at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:278)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:117)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:88)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:202)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:160)
Uncaught error from thread [application-akka.actor.default-dispatcher-2]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.ExceptionInInitializerError
	at Repos.DatabaseRepository.test(DatabaseRepository.java:13)
	at controllers.testController.testDB(testController.java:23)

**Comment by rbygrave** [comment]
No.  There is currently no support for Redshift.
