### ISSUE TITLE
ebean.allQuotedIdentifiers is ignored for @JoinColumn

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1896]
When I have 2 entities got a relation like `@ManyToOne` and described using `@JoinColumn`, the new column that describes that relation does not follow the other columns convention with a quote.

If I remove `@JoinColumn` the column is following the convention like `[addressAddressID]            numeric(19),`.

## Expected behavior

I think column `addressid` should be `AddressID` as what described in `@JoinColumn`

## Actual behavior

it is always not quoted for `@JoinColumn`.

### Steps to reproduce

I have the following entities:

```java
@Entity
@Table(name = "Labs", schema = "dev")
public class Labs extends BaseModel<LabsData> {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LabID")
    private Integer id;

    @Column(name = "Name", length = 50, nullable = false)
    private String name;

    @ManyToOne(optional = true, targetEntity = AddressData.class, fetch = FetchType.EAGER)
    @JoinColumn(name = "AddressID", insertable = false)
    private AddressData address;

}

```

```java
@Entity
@Table(name = "Addresses", schema = "dev")
public class AddressData extends BaseModel<AddressData> {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "AddressID")
    private Long id;

    @Column(name = "Name", length = 50, nullable = false)
    private String name;

    @Column(name = "Address1", length = 75)
    private String address1;

    @Column(name = "Address2", length = 75)
    private String address2;

    @Column(name = "City", length = 50)
    private String city;

    @Column(name = "State", length = 50)
    private String state;

    @Column(name = "Zip", length = 50)
    private String zipCode;

    @Column(name = "Country", length = 50)
    private String country;

}
```

The generated script is:

```sql
create table [dev].[Addresses] (
  [AddressID]                   numeric(19) identity(1,1) not null,
  [Name]                        nvarchar(50) not null,
  [Address1]                    nvarchar(75),
  [Address2]                    nvarchar(75),
  [City]                        nvarchar(50),
  [State]                       nvarchar(50),
  [Zip]                         nvarchar(50),
  [Country]                     nvarchar(50),
  constraint pk_addresses primary key ([AddressID])
);

create table [dev].[Labs] (
  [LabID]                       integer identity(1,1) not null,
  [Name]                        nvarchar(50) not null,
  addressid                     numeric(19),
  constraint pk_labs primary key ([LabID])
);

```

note the `addressid` here. 

_Also, I'm not sure what the index name should look like, I hope there is a better convention, or maybe the index name should be quoted as well? like `[ix_Labs_AddressID]`, I can open another issue for this, also for `fk_labs_addressid` maybe should be `[fk_Labs_AddressID]`, maybe primary keys for tables as well? `[pk_Labs]` instead of `pk_labs`_

but the column name is not quoted as well, it is: 

Without `@JoinColumn`

```sql
create index ix_labs_addressaddressid on [dev].[Labs] ([addressAddressID]);
alter table [dev].[Labs] add constraint fk_labs_addressaddressid foreign key ([addressAddressID]) references [dev].[Addresses] ([AddressID]);
```

With `@JoinColumn`

```sql
create index ix_labs_addressid on [dev].[Labs] (addressid);
alter table [dev].[Labs] add constraint fk_labs_addressid foreign key (addressid) references [dev].[Addresses] ([AddressID]);
```

**Comment by rbygrave** [comment]
Reference test case in minimal project - https://github.com/ebean-orm-examples/example-minimal/pull/5/files

**Comment by rbygrave** [comment]
Error in failing test:
```
javax.persistence.PersistenceException: Query threw SQLException:Invalid column name 'AddressID'. Bind values:[] Query was:select t0.[LabID], t0.[Name], t0.AddressID from [Labs] t0

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:55)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:231)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:149)
	...

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'AddressID'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
```

**Comment by rbygrave** [comment]
Great work @almothafar , this test case is nice and clear, excellent work.

Cheers, Rob.
