### ISSUE TITLE
ManyToMany relation entity behavior is not working as version 11.45.x

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1977]
I got a relation entity between two tables represents ManyToMany relation, previously I was set that relation using a collection, and ebean was dealing with what the newly added and what was previously and what removed, so one line of code is enough, now I have to find that myself and do delete, add or keep.

As for example, I have `User.java` and `Role.java` so I do the relation between them using `UserRole.java`, what was enough to be is having `Set<UserRole> userRoles` in `User.java` and set that with roles that I have.

## Expected behavior
Work as before, without doing all the logic myself,

## Actual behavior
Currently, I have to do queries and find what the differences and set that, ebean don't remove what is missing.

### Steps to reproduce

I have the following beans:

User.java
```java

@Entity
@Table(name = "users")
public class User extends BasicModel<User> {
    ...
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @DbForeignKey(onDelete = ConstraintMode.CASCADE)
    // ROB NOTE: Prefer List over Set ... due to Set's implicit early use of equals/hashCode
    private Set<UserRole> userRoles;

   // ... setters and getters
}

```

Role.java
```java

@Entity
@Table(name = "roles")
public class Role extends BaseModel<Role> {
    @Id
    private String idKey;

    @ManyToOne(optional = false)
    protected Product product;
    ...

    // ROB NOTE: Prefer NOT to add equals() and hashCode() 
    // .. and instead leave that to Ebean enhancement

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Role)) return false;
        Role role = (Role) o;
        return Objects.equals(this.idKey, role.getIdKey());
    }

    @Override
    public int hashCode() {
        // BECAUSE THIS IS A MUTATING HASHCODE VALUE WHICH IS BAD !!!
        final String idKey = this.idKey == null ? buildIdKey() : this.idKey;
        return Objects.hash(idKey, getProduct());
    }

    @PrePersist
    public void beforePersist() {
        this.idKey = buildIdKey();
    }

    private String buildIdKey() {
        return display != null && getProduct() != null ? (getProduct().getUniqueKey() + ":" + display.replaceAll("\\s+", "_")).toLowerCase() : null;
    }

   // ... setters and getters
}

```

UserRole.java
```java

@Entity
@Table(name = "user_role", uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "role_id_key"}))
public class UserRole extends BasicModel<UserRole> {

    @ManyToOne(optional = false)
    private User user;

    @ManyToOne(optional = false)
    private Role role;

    // ROB NOTE: I'd tend to remove an unused constructor
    public UserRole() {
    }

    public UserRole(User user, Role role) {
        this.user = user;
        this.role = role;
    }

   // ... setters and getters
}

```

If you want `BaseModel.java`:
```java
@MappedSuperclass
@SuppressWarnings("unchecked")
public abstract class BaseModel<T extends BaseModel<?>> extends Model {
    
    @WhenCreated
    private LocalDateTime createdDate;
    ...
}
```
If you want `BasicModel.java`:
```java
@MappedSuperclass
@SuppressWarnings("unchecked")
public abstract class BasicModel<T extends BasicModel<T>> extends BaseModel<T> {
    @Id
    private Integer id;
   ...
}

```

Currently, If I try to save it like this (while in version 11.45.1 is working fine):
```java
public User updateUserRoles(int userId, Set<Role> roles) {
        final User userInDB = Ebean.find(User.class)
                .setDisableLazyLoading(true)
                .fetch("userRoles")
                .where()
                .idEq(userId)
                .findOne();

        if (userInDB != null) {
            if (roles != null) {
                final Set<UserRole> userRoles = roles.stream()
                        .map(role -> new UserRole(userInDB, Ebean.getReference(Role.class, role.getIdKey())))
                        .collect(Collectors.toSet());
                userInDB.setUserRoles(userRoles);
            }
            userInDB.update();
            // The rest of the fields that could be updated.....
            return userInDB;
        } else {
           // throw exception or whatever
           return null;
        }
}
```

I get error

```console
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'uq_user_role_user_id_role_id_key'. Cannot insert duplicate key in object 'dbo.user_role'. The duplicate key value is (18, spl:reports).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:473)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:92)
	at io.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:125)
	at io.ebeaninternal.server.persist.dml.DmlHandler.executeNoBatch(DmlHandler.java:99)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:73)
	... 31 more

```

But using the following code is working fine with the new version:
```java
public User updateUserRoles(int userId, Set<Role> roles) {
        final User userInDB = Ebean.find(User.class)
                .setDisableLazyLoading(true)
                .fetch("userRoles")
                .where()
                .idEq(userId)
                .findOne();

        if (userInDB != null) {
            if (roles != null) {
                final Set<UserRole> rolesToKeep = userInDB.getUserRoles().stream()
                        .filter(userRole -> roles.contains(userRole.getRole())).collect(Collectors.toSet());

                final Set<UserRole> rolesToRemove = userInDB.getUserRoles().stream()
                        .filter(userRole -> !roles.contains(userRole.getRole())).collect(Collectors.toSet());

                final Set<UserRole> rolesToAdd = roles.stream()
                        .filter(role -> rolesToKeep.stream().filter(userRole -> role.equals(userRole.getRole())).findFirst().isEmpty())
                        .map(role -> new UserRole(userInDB, Ebean.getReference(Role.class, role.getIdKey())))
                        .collect(Collectors.toSet());

                rolesToAdd.addAll(rolesToKeep);
                Ebean.deleteAll(rolesToRemove);
                userInDB.setUserRoles(rolesToAdd);
            }
            userInDB.update();
            // The rest of the fields that could be updated.....
            return userInDB;
        } else {
           // throw exception or whatever
           return null;
        }
}
```

Am I doing things wrong? or a new bug with the new version?

**Comment by rbygrave** [comment]
Yes, we can improve this by just using a stateless update. So I can show you what that means / looks like but _first_ ... can you post up the log for io.ebean.SQL & io.ebean.TXN. 
We want to compare what actually happens in terms of SQL statements being executed. This then will be more obvious why we have "stateless updates" for this case with Ebean because we can see that we can skip loading the user and roles altogether (skip those sql select queries completely).

**Comment by rbygrave** [comment]
Oh hang on ... can you show me the full UserRole.java again ?

**Comment by rbygrave** [comment]
Note that there is no `@ManyToMany` here but instead `@OneToMany` (and the intersection/bridge table is explicitly modelled by UserRole).  So that will stop us using a simple "stateless update".  Show me the full UserRole again ... (plus the original sql & txn log) and I'll have a look.

**Comment by rbygrave** [comment]
I suspect this relates to the stateless update change that came with 12.1.1 - https://github.com/ebean-orm/ebean/releases/tag/ebean-12.1.1

**Comment by rbygrave** [comment]
I'll close this for now.
