### ISSUE TITLE
conflict with eureka config generate StringIndexOutOfBoundsException with 12.2.1 version

### ISSUE THREAD

**Issue by elhoce** [ebean-orm/ebean#1982]
## Expected behav

the statusPageUrl eureka config thrown StringIndexOutOfBoundsException with 12.2.1 ebean version, working fine with 12.1.13 version

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    hostname: localhost
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka/}
### Steps to reproduce
use spring boot version 2.0.8 with eureka.
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    hostname: localhost
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka/}

stacktrace

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967) ~[na:1.8.0_242]
	at io.avaje.config.load.CoreExpressionEval$EvalBuffer.parseForDefault(CoreExpressionEval.java:164) ~[config-1.0.jar:na]
	at io.avaje.config.load.CoreExpressionEval$EvalBuffer.evalNext(CoreExpressionEval.java:209) ~[config-1.0.jar:na]
	at io.avaje.config.load.CoreExpressionEval$EvalBuffer.process(CoreExpressionEval.java:214) ~[config-1.0.jar:na]
	at io.avaje.config.load.CoreExpressionEval.eval(CoreExpressionEval.java:102) ~[config-1.0.jar:na]
	at io.avaje.config.load.CoreExpressionEval.eval(CoreExpressionEval.java:62) ~[config-1.0.jar:na]
	at io.avaje.config.load.LoadContext.evalAll(LoadContext.java:129) ~[config-1.0.jar:na]
	at io.avaje.config.load.Loader.eval(Loader.java:238) ~[config-1.0.jar:na]
	at io.avaje.config.load.Loader.load(Loader.java:84) ~[config-1.0.jar:na]
	at io.avaje.config.CoreConfiguration.load(CoreConfiguration.java:25) ~[config-1.0.jar:na]
	at io.avaje.config.Config.<clinit>(Config.java:18) ~[config-1.0.jar:na]
	... 44 common frames omitted

**Comment by elhoce** [comment]
working fine when removing ${var} expression.

**Comment by rbygrave** [comment]
Where is `$[var}` ? ... it isn't in the example above ?

**Comment by elhoce** [comment]
example :
statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info

**Comment by rbygrave** [comment]
Thanks, that makes more sense.  Actual issue logged as https://github.com/avaje/config/issues/4
