### ISSUE TITLE
Postgres Entity @Column Problem

### ISSUE THREAD

**Issue by buckfeng** [ebean-orm/ebean#2018]
There seemed to be a problem using @Column to define column name on Postgres.   I am able to reproduce the problem with the "example-minimal" code.  If I add @Column to the id column as such:

```
@Entity
public class Customer extends Model
{
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name="ID")
  Long id;
```

I would get the error:

```
javax.persistence.PersistenceException: Error[ERROR: column "ID" does not exist   Position: 129]

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:55)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:231)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:83)
	at io.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:49)
	at io.ebeaninternal.server.core.PersistRequestBean.executeInsert(PersistRequestBean.java:1260)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:786)
	at io.ebeaninternal.server.core.PersistRequestBean.executeNoBatch(PersistRequestBean.java:841)
	at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:832)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:519)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:467)
	at io.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:450)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1767)
	at io.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1759)
	at org.example.domain.CustomerDateTest.testLocalDateMapping(CustomerDateTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.postgresql.util.PSQLException: ERROR: column "ID" does not exist
  Position: 129
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
```

The trace showed:

```
23:07:36.154 [main] INFO  io.ebean.EbeanVersion - ebean version: 12.2.4
23:07:36.347 [main] WARN  io.avaje.config.load.Loader - Loading properties from test-ebean.properties is deprecated. Please migrate to application-test.yaml or application-test.properties instead.
23:07:36.396 [main] INFO  i.e.datasource.pool.ConnectionPool - DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
23:07:38.139 [main] INFO  io.ebean.internal.DefaultContainer - DatabasePlatform name:db platform:postgres
23:07:38.329 [main] TRACE io.ebean.TXN - txn[1001] Begin
23:07:38.337 [main] DEBUG io.ebean.SQL - txn[1001] insert into customer (name, notes, birthday, birth_moment, local_dt, zoned_dt, version) values (?,?,?,?,?,?,?); -- bind(Rob,null,2020-01-15T00:00Z[UTC],2020-06-09T04:07:38.325Z,2020-06-08T23:07:38.325,2020-06-08T23:07:38.325-05:00[America/Chicago],1)
23:07:38.437 [main] DEBUG io.ebean.SUM - txn[1001] Error[ERROR: column "ID" does not exist   Position: 129]
23:07:38.524 [main] TRACE io.ebean.TXN - txn[1001] Commit - query only
```

This problem seemed to affect Postgres only.  The same code worked fine on Oracle and SqlServer.  It may have to do with case-sensitivity.  I tried using @Column(name="id") and that worked fine.  Our naming convention is ALL_CAP_SNAKE_CASE for table column names and camelCase for entity field names.  We can't assume that the the column names and field names are always consistent and only differ by casing.

Thanks for your help.

Buck

**Comment by rbygrave** [comment]
You need to create a failing test case.  Awaiting that.

**Comment by buckfeng** [comment]
I was using an older version of the "example-minimal" and a local postgres instance.  The latest "example-minimal" switched to docker test with postgres.  It had problem starting up the container (see errors below) .    the ut_postgres container seemed to require a password.

```
15:57:42.821 [main] INFO  i.e.config.properties.LoadContext - loaded properties from [application.properties, application-test.yaml]
15:57:42.867 [ForkJoinPool.commonPool-worker-5] INFO  io.ebean.test.config.platform.Config - Using jdbc settings - username:myapp url:jdbc:postgresql://localhost:6432/myapp driver:org.postgresql.Driver
15:58:06.664 [ForkJoinPool.commonPool-worker-5] INFO  io.ebean.docker.commands.Commands - Run container ut_postgres with port:6432 db:myapp user:myapp/test mode:Create shutdown:stop
16:00:07.240 [ForkJoinPool.commonPool-worker-5] WARN  io.ebean.docker.commands.Commands - Failed waitForDatabaseReady for container ut_postgres
16:00:07.240 [ForkJoinPool.commonPool-worker-5] WARN  io.ebean.docker.commands.Commands - Failed to start container ut_postgres with port 6432
16:00:07.248 [main] INFO  i.e.t.c.provider.ProviderAutoConfig - for testing purposes a current user and tenant provider has been configured. Use io.ebean.test.UserContext to set current user and tenant in tests.
16:00:07.336 [main] INFO  i.e.datasource.pool.ConnectionPool - DataSourcePool [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200]
16:00:09.405 [main] INFO  i.e.d.pool.PooledConnectionQueue - Reseting DataSourcePool [db] min[2] max[200] free[0] busy[0] waiting[0] highWaterMark[0] waitCount[0] hitCount[0]
16:00:09.406 [main] ERROR i.e.datasource.pool.ConnectionPool - FATAL: DataSourcePool [db] is down or has network error!!!
16:00:09.409 [main] ERROR io.ebean.Ebean - Error trying to create the default Database
io.ebean.datasource.DataSourceInitialiseException: Error initialising DataSource: Connection to localhost:6432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

```

```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by rbygrave** [comment]
example-minimal needs to have it's dependencies upgraded.  What happened is that postgres docker container changed to need an explicit password.  Updating to the latest version of ebean-test will sort that out.

**Comment by buckfeng** [comment]
I upgraded ebean-test to the latest (v12.3.3) and had the same issue.  maybe the changes are not in maven yet?
```
18:30:05.505 [main] INFO  io.ebean.EbeanVersion - ebean version: 12.3.3
18:30:05.864 [ForkJoinPool.commonPool-worker-5] INFO  io.ebean.test.config.platform.Config - Using jdbc settings - username:myapp url:jdbc:postgresql://localhost:6432/myapp driver:org.postgresql.Driver
18:30:31.681 [ForkJoinPool.commonPool-worker-5] INFO  io.ebean.docker.commands.Commands - Start container ut_postgres with port:6432 db:myapp user:myapp/test shutdown:Stop
18:37:41.001 [ForkJoinPool.commonPool-worker-5] WARN  io.ebean.docker.commands.Commands - Failed waiting for connectivity
```

**Comment by rbygrave** [comment]
When the insert PreparedStatement is bound in `InsertHandler` line 113 
`      return conn.prepareStatement(sql, meta.getIdentityDbColumns());` 

The meta.getIdentityDbColumns() returns a String[] with a single "ID" value.  In theory Postgres identifier is case insensitive. The Postgres JDBC Driver converts this insert statement into:

`insert into account (name, notes, version) values (?,?,?) RETURNING "ID"`

Note that this has double quotes around the ID column identifier. So `"ID"` indeed is not a known column on the account table (but `ID` and `id` both are).  

In PG Parser line 317 it has `Utils.escapeIdentifier(nativeSql, columnName);` ... and `Utils.doAppendEscapedIdentifier()` line 96 and line 111 and surrounding the returning column name with double quotes.

So it's right down here in the PG JDBC Driver that it is quoting the given returning column name - hence the `"ID"` rather than `ID` (which is what I'd expect actually).

--- 
In a SQL console:
```sql
select ID, id, name from account;
-- works

select "id", name from account;
-- works

select "ID", name from account;
-- ERROR column "ID" does not exist
```

**Comment by rbygrave** [comment]
Our naming convention is all_lower_snake_case ... would work for Postgres as `"id"` and `id` and `ID` then all work.

**Comment by rbygrave** [comment]
So I will close this issue in that it isn't deemed to be an Ebean issue. 

Cheers, Rob.

**Comment by buckfeng** [comment]
Thank you Rob for looking into this.   We changed to lower case convention for identity columns and that worked well for all three databases: oracle, postgres, and sql server.
