### ISSUE TITLE
updated from 12.3.6 to 12.3.7 - NPE BeanDescriptor.findPropertyFromPath(BeanDescriptor.java:1965)

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/ebean#2038]
just updated from patch version to another, got this. what could be the reason?

```java
NullPointerException.java.lang: null
    at io.ebeaninternal.server.deploy.BeanDescriptor.findPropertyFromPath(BeanDescriptor.java:1965)
    at io.ebeaninternal.server.loadcontext.DLoadContext.getBeanProperty(DLoadContext.java:340)
    at io.ebeaninternal.server.loadcontext.DLoadContext.createManyContext(DLoadContext.java:326)
    at io.ebeaninternal.server.loadcontext.DLoadContext.lambda$getManyContext$2(DLoadContext.java:322)
    at java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    at io.ebeaninternal.server.loadcontext.DLoadContext.getManyContext(DLoadContext.java:322)
    at io.ebeaninternal.server.loadcontext.DLoadContext.register(DLoadContext.java:287)
    at io.ebeaninternal.server.loadcontext.DLoadBeanContext.register(DLoadBeanContext.java:42)
    at io.ebeaninternal.server.deploy.BeanDescriptor.lazyLoadMany(BeanDescriptor.java:2311)
    at io.ebeaninternal.server.deploy.BeanDescriptor.lazyLoadMany(BeanDescriptor.java:2291)
    at io.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:185)
    at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:842)
    at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:821)
    at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:913)
```

```console
  // some logging output
```

**Comment by rbygrave** [comment]
@turbospaces   Do you have more information ?

**Comment by nc-rafj** [comment]
I'm having the same issue after upgrading to ebean 12.3.7 in a spring boot project. Everything works fine with 12.3.6.

In my case, this exception occurs when performing multiple lazy loads e.g. 
```
List<Foo> foosList1 = bazFromDb.foo.bar.fooList
```

Note that the following works fine:
```
List<Foo> foosList = fooFromDb.bar.fooList
```

I have created a small spring boot project where the error occurs. https://github.com/nc-rafj/ebean-issue-2038

Sorry for providing groovy examples instead of java.

**Comment by rbygrave** [comment]
So far this looks like a regression due to the change from https://github.com/ebean-orm/ebean/issues/2035
