### ISSUE TITLE
Error enum mapping for Postgresql

### ISSUE THREAD

**Issue by marysia16122** [ebean-orm/ebean#2040]
database: postgres
driver: 42.2.14
ebean: 12.1.10
java: 14

In database:
1. Create custom type:
`CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');`

2. Create table 'person' and insert data
`CREATE TABLE person (
    name text,
    current_mood mood
);
INSERT INTO person VALUES ('Moe', 'happy');
`

In java:
1. Create class (use lombok annotations):
```@Entity
@Data
@ReadAudit
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "person")
public class Person extends Model {
    private String name;
    private Mood current_mood;

    public enum Mood {
        sad, ok, happy;

        @DbEnumValue
        public String value() {
            return name();
        }
    }
}
```

2. call
`new QPerson().current_mood.in(Person.Mood.happy).findList();`

The problem when I can use enum in 'WHERE' block

Error:
`Caused by: javax.persistence.PersistenceException: Query threw SQLException:ERROR: operator does not exist: mood = character varying
  Подсказка: No operator matches the given name and argument types. You might need to add explicit type casts.
  Позиция: 70 Bind values:[Array[1]={happy}] Query was:select t0.name, t0.current_mood from person t0 where t0.current_mood = any(?)
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:55)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:231)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:149)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.translate(DefaultOrmQueryEngine.java:43)
	at io.ebeaninternal.server.core.OrmQueryRequest.translate(OrmQueryRequest.java:108)
	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:707)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:413)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:131)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:472)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1604)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1580)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1555)
	at io.ebean.typequery.TQRootBean.findList(TQRootBean.java:1601)`

**Comment by rbygrave** [comment]
Database enum types are not supported at this stage.

**Comment by rbygrave** [comment]
Happy to review a PR if someone is looking to add support for this.  In the meantime may as well close this as unsupported.

Cheers, Rob.
