### ISSUE TITLE
@Convert(converter = StringToListConverter.class) removes the column from generated SQL

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2119]
I have  `nvarchar` column that contains strings joined by a delimiter, as for example `code1,code2,code3` but in the code, I deal with them as `List<String> codes` so I used `@Convert` to deal with conversation, the problem is I see that using this is making the column used to disappear from SQL code generated:

![image](https://user-images.githubusercontent.com/13887564/100620771-75eadf00-3327-11eb-8e10-7a5a03868983.png)

### Steps to reproduce

Column
```java
    @Column(name = "TestCodes", length = 300)
    @Convert(converter = StringToListConverter.class)
    private List<String> testCodes;
```
Converter
```java
@Converter
public class StringToListConverter implements AttributeConverter<List<String>, String> {

    @Override
    public String convertToDatabaseColumn(List<String> list) {
        return list != null ? String.join(",", list) : null;
    }

    @Override
    public List<String> convertToEntityAttribute(String joined) {
        return joined != null ? new ArrayList<>(Arrays.asList(joined.split(","))) : null;
    }
}

```

**Comment by rbygrave** [comment]
Note that you can use @DbArray even on databases that don't support ARRAY
type.  To me that is more logically correct.  Ebean doesn't support
using @Convert in this way and it does provide a lot of limitations in
going down that path and we don't have those limitations when we
use @DbArray.

So to me the expected and better path is to use @DbArray.

**Comment by rbygrave** [comment]
If SQL Server is the only target then another potential option that
provides more functionality database wise would be to map as JSON (json
array of string).

This allows us to use db json functions for predicates like: where
testCodes contains 'foo'  ... and hence the option of DB functional indexes
etc.

**Comment by almothafar** [comment]
I tried to use `@DbArray` and `@DbJson` the problems are:
* I'm using SQ Server so the array is not an option.
* I "can't"/"don't know how to" set column name, nullable or not, and other attributes except the length.
* IDE reports an error with message
![image](https://user-images.githubusercontent.com/13887564/100724557-ac7a3580-33cb-11eb-942d-46e2f1660a5f.png)

![image](https://user-images.githubusercontent.com/13887564/100724446-8fddfd80-33cb-11eb-833a-c2ddc20ef8ae.png)

**Comment by rbygrave** [comment]
> I'm using SQ Server so the array is not an option.

I don't know why you say that.  If we use `@DbArray` with SQL Server (or any database that doesn't support ARRAY types) Ebean will support it via something that is very similar to the StringToListConverter.  So as I see it that is an option.


> IDE reports an error with message

You just have to ignore that.  JPA has no `@DbArray` and the IDE warning is going to be JPA orientated and equally unaware.

**Comment by almothafar** [comment]
Ok the following code seems removing even the error:

```java
    @SuppressWarnings("JpaAttributeTypeInspection")
    @Column(name = "TestCodes")
    @DbArray(length = 300)
    private List<String> testCodes;
```

But it is `varchar`, not `nvarchar`, not a big deal for now:
![image](https://user-images.githubusercontent.com/13887564/100734334-2dd7c500-33d8-11eb-8d46-860541b24a59.png)

I'll test it.

**Comment by almothafar** [comment]
@rbygrave I get error:

```console
[error] - [                    ] a.PostAction - Direct exception java.lang.NoClassDefFoundError: Could not initialize class io.ebean.text.json.EJson
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class io.ebean.text.json.EJson
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.ebean.text.json.EJson
	at io.ebeaninternal.server.type.ScalarTypeJsonList$Base.bind(ScalarTypeJsonList.java:95)
	at io.ebeaninternal.server.type.ScalarTypeJsonList$Varchar.bind(ScalarTypeJsonList.java:42)
	at io.ebeaninternal.server.type.ScalarTypeJsonList$Base.bind(ScalarTypeJsonList.java:69)
	at io.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:657)
	at io.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:240)
	at io.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:212)
	at io.ebeaninternal.server.persist.dmlbind.BindableProperty.dmlBind(BindableProperty.java:54)
	at io.ebeaninternal.server.persist.dmlbind.BindableList.dmlBind(BindableList.java:66)
	at io.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:149)
	at io.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:98)

```

**Comment by rbygrave** [comment]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.ebean.text.json.EJson

So this is suggesting that either EJson is not in the class path or that something is interesting with class loading (what is special/different about the class loading mechanism).

The first question is -  Is `io.ebean.text.json.EJson` in the class path? (It is in the ebean-api module)

**Comment by almothafar** [comment]
It is there: 
![image](https://user-images.githubusercontent.com/13887564/100991422-a4e99680-355b-11eb-86ca-fa41c239b02a.png)

But in runtime I tried also something like:

```java
        try {
            Class<?> clazz = Class.forName("io.ebean.text.json.EJson");
        } catch (NoClassDefFoundError e) {
            logger.error("io.ebean.text.json.EJson not found");
        }
```
And logger did log it:

```console
[error] - [                    ] m.StartupModule - io.ebean.text.json.EJson not found
```

Note that if I set `testCodes` with null, the API works fine and the data got stored.

**Comment by almothafar** [comment]
@rbygrave 
So it is not OK even to use `@Converter` with ebean? because I'm getting wired issue if I tried to use it:
```console
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
Caused by: java.lang.NullPointerException: null
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.createReference(BeanPropertyAssocMany.java:636)
	at io.ebeaninternal.server.deploy.BeanDescriptor.lazyLoadMany(BeanDescriptor.java:2319)
	at io.ebeaninternal.server.deploy.BeanDescriptor.lazyLoadMany(BeanDescriptor.java:2302)
	at io.ebeaninternal.server.loadcontext.DLoadBeanContext$LoadBuffer.loadBean(DLoadBeanContext.java:197)
	at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:852)
	at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:829)
	at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:923)
	at m.s.XEntity._ebean_get_testCodes(XEntity.java:6)
	at m.s.XEntity.getTestCodes(XEntity.java:356)
	at v2.s.Resource.<init>(Resource.java:59)
```

where in `Resource.java:59` I just access to data like `data.getTestCodes()` 

So now Can't use `@DbArray` and `@Converter` :)

**Comment by rbygrave** [comment]
> So it is not OK even to use @Converter with ebean? because I'm getting wired issue if I tried to use it:

Have we seen the code / mapping that produce that error?


> So now Can't use @DbArray and @Converter :)

I don't understand this comment -  it isn't clear to me what this means.


> my current workaround is doing this:

Sure, but `@DbArray` would also work too so I think we are missing some information. Ideally we see a failing test case without any dependency on Akka or anything (and then compare it to the existing tests to see if there is missing coverage or something).

**Comment by rbygrave** [comment]
Forking and submitting a PR on https://github.com/ebean-orm-examples/example-minimal is a good way to provide a failing test (if we think we have a bug).

**Comment by almothafar** [comment]
@rbygrave Yeah it saves a lot of time to provide a working project having an issue, already got a minimal project https://github.com/almothafar/play-java-ebean-sql-server but I barely have time, I'm under infinite stress these days (well actually years....)...
I'll try to maintain that project to reproduce this asap I can breathe...

**Comment by rbygrave** [comment]
I think we will close this for now.  Re-open if there is more but I think we should be just using @DbArray or @DbJson
