### ISSUE TITLE
ebean doest not support Spring @Transactional(propagation = Propagation.REQUIRES_NEW)

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean#2135]
```
      @Transactional
    public void test() {
        AsrTask asrTask = new AsrTask();
        asrTask.insert();
        SpringBeanUtil.getBean(TestTransactionService.class).test1();
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void test1() {
        AsrTask asrTask = new AsrTask();
        asrTask.insert();
    }
```

```
  javax.persistence.PersistenceException: Invalid state - there is an existing Active transaction ScopedTransaction[ScopeTrans[txn[s553496382] ]]

	at io.ebeaninternal.server.transaction.DefaultTransactionScopeManager.checkForActiveTransaction(DefaultTransactionScopeManager.java:66)
	at io.ebeaninternal.server.transaction.DefaultTransactionScopeManager.set(DefaultTransactionScopeManager.java:48)
	at io.ebeaninternal.server.transaction.TransactionManager.externalBeginTransaction(TransactionManager.java:637)
	at io.ebean.spring.txn.SpringJdbcTransactionManager.getCurrentTransaction(SpringJdbcTransactionManager.java:94)
	at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.getActive(ExternalTransactionScopeManager.java:27)
	at io.ebeaninternal.server.transaction.TransactionManager.getActive(TransactionManager.java:225)
	at io.ebeaninternal.server.core.DefaultServer.currentServerTransaction(DefaultServer.java:763)
	at io.ebeaninternal.server.core.BeanRequest.createImplicitTransIfRequired(BeanRequest.java:47)
	at io.ebeaninternal.server.core.PersistRequestBean.initTransIfRequiredWithBatchCascade(PersistRequestBean.java:285)
	at io.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:462)
	at io.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1676)
	at io.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1668)
	at io.ebean.Model.insert(Model.java:235)
	at ltd.linfei.record.test.TestTransactionService.test1(TestTransactionService.java:43)

```

**Comment by rbygrave** [comment]
Do you want to create a PR with a failing test in https://github.com/ebean-orm/ebean-spring-txn ?

**Comment by rbygrave** [comment]
Did not reproduce with:
 https://github.com/ebean-orm/ebean-spring-txn/commit/bf0c8d8dab58ce98f4f40d537d138b088b73f8d8
https://github.com/ebean-orm/ebean-spring-txn/commit/559867294ff2ce65520441ba836aef5b37d75c39

**Comment by rbygrave** [comment]
Can you add a failing test to   https://github.com/ebean-orm/ebean-spring-txn ?

**Comment by spinachomes** [comment]
I submitted a [pr](https://github.com/ebean-orm/ebean-spring-txn/pull/24)
It seems add blew code in SpringTxnListener can resolve this problem
```
        @Override
        public void suspend() {
            transactionManager.externalRemoveTransaction();
        }
```

**Comment by rbygrave** [comment]
Great, thanks.  I see the issue there ...

**Comment by rbygrave** [comment]
The fix is to change to use `scopeManager.replace(scopedTxn);` rather than `set()` as we are leaving it up to the external transaction manager to nest the scopes.

Need to do more checks here around "popping" externally managed nested transactions.
