### ISSUE TITLE
With @ManyToMany mapping seems does not take custom table and column names provided in @JoinTable 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2187]
It is maybe related to #2186 but the issue that I got is when I try to override values auto-generated by ebean it seems it does not read the custom column names

So the question is: how I can customize the table name? I tried something like:

So if I have:

```java
public class Student extends Model {

    @Id
    @Column(name = "StudentNumber", length = 35, nullable = false, updatable = false)
    private String studentNumber;

    // getters, and setters
}

public class Course extends Model {

    @Id
    @Column(name = "Id", nullable = false, updatable = false, unique = true)
    private UUID id;

   @ManyToMany(cascade = CascadeType.ALL)
    private List<Student> students;

    // getters, and setters
}

```

And in `Course` side I tried to do mapping like:

```java
    @ManyToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "CustomCourseStudent",
            joinColumns = @JoinColumn(name = "CustomCourseId"),
            inverseJoinColumns = @JoinColumn(name = "CustomStudentNumber")
    )
    private List<Student> students;
```

or 

```java
    @ManyToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "CourseStudent",
            joinColumns = @JoinColumn(name = "CourseId"),
            inverseJoinColumns = @JoinColumn(name = "StudentNumber")
    )
    private List<Student> students;
```

Both didn't work, and it returns with error:

```console
Caused by: javax.persistence.PersistenceException: Error with the Join on [models.Course.students]. Could not find the matching foreign key for [[Id]] in table[CourseStudent]? Perhaps using a @JoinColumn with the name/referencedColumnName attributes swapped?
	at io.ebeaninternal.server.deploy.BeanPropertyAssoc.findMatch(BeanPropertyAssoc.java:613)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.findMatch(BeanPropertyAssocMany.java:701)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.createExported(BeanPropertyAssocMany.java:689)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.initialiseAssocMany(BeanPropertyAssocMany.java:185)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.initialise(BeanPropertyAssocMany.java:153)
	at io.ebeaninternal.server.deploy.BeanDescriptor.initialiseOther(BeanDescriptor.java:636)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.initialiseAll(BeanDescriptorManager.java:525)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:330)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:177)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:110)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
	at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:123)
	at io.ebean.DatabaseFactory.create(DatabaseFactory.java:77)
	at play.db.ebean.orm.EbeanDynamicEvolutions.lambda$start$2(EbeanDynamicEvolutions.java:127)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at play.db.ebean.orm.EbeanDynamicEvolutions.start(EbeanDynamicEvolutions.java:123)
	at play.db.ebean.orm.EbeanDynamicEvolutions.<init>(EbeanDynamicEvolutions.java:68)
	at play.db.ebean.orm.EbeanDynamicEvolutions$$FastClassByGuice$$9cd3c635.newInstance(<generated>)
```

The error mentions `[Id]` but it should be by default `TableName_IdColumnName`, the exception might get resolved in the other ticket, but still it seems when I tried to work around it, it does not read `@JoinTable`?

**Comment by almothafar** [comment]
It is related to #2157?

**Comment by rbygrave** [comment]
> Could not find the matching foreign key for [[Id]] in table[CourseStudent]

There is no `[Id]` specified in the `@JoinColumn`.  I think we need it explicitly via the _referencedColumnName_ like:

```java
  @ManyToMany(cascade = CascadeType.ALL)
  @JoinTable(
    name = "CourseStudent",
    joinColumns = @JoinColumn(name = "CourseId", referencedColumnName = "Id"),
    inverseJoinColumns = @JoinColumn(name = "StudentNumber", referencedColumnName = "StudentNumber")
  )
```

> It is related to #2157?

I have not looked yet ...

**Comment by almothafar** [comment]
@rbygrave I think I need a vacation, where that already mentioned in error, for 2 days, I didn't see it, doing that actually worked, the script generated was:

```sql
create table dbo.CourseStudent (
  [CourseId]      uniqueidentifier not null,
  [StudentNumber] nvarchar(35) not null,
  constraint [pk_Course_Student] primary key ([CourseId],[StudentNumber])
);
```

I'll close this issue and comment on another issue.
I  facepalmed myself hard in real on this lol, sorry.

**Comment by rbygrave** [comment]
> I think I need a vacation

Ha ha, I'm feeling that too at the moment :) 

I'll good.  I think we could improve the error message. I've just pushed a little improvement to that error message so hopefully that gives people a little more direction next time as well.

Cheers, Rob.
