### ISSUE TITLE
Ebean was unable to use @Embeddable class with @ElementCollection

### ISSUE THREAD

**Issue by geliotropvimd** [ebean-orm/ebean#2242]
## Expected behavior
I want to get tables for these data classes

## Actual behavior
When creating tables in the course of the code, the following error occurs.

### Steps to reproduce

```kotlin
@Serializable
@Embeddable
data class Debt(
val nextPaymentSum: String?,
val od: String?,
@ElementCollection
val payments: List<Payment>
)

@Serializable
@Embeddable
data class  Payment(
val sumToGo: String?,
val odToGo: String?,
)

@Entity
class DebtEntity(
    @Id override val id: UUID,
    @Embedded override var data: Debt?,
)
```

```console
java.lang.NullPointerException: null
at java.lang.String.replace(String.java:2142) ~[?:?]
at io.ebean.util.StringHelper.replace(StringHelper.java:112) ~[ebean-api-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanPropertyOverride.replace(BeanPropertyOverride.java:49) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanProperty.<init>(BeanProperty.java:438) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanEmbeddedMetaFactory.create(BeanEmbeddedMetaFactory.java:48) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.<init>(BeanPropertyAssocOne.java:85) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.meta.DeployBeanPropertyLists.createBeanProperty(DeployBeanPropertyLists.java:482) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.meta.DeployBeanPropertyLists.<init>(DeployBeanPropertyLists.java:119) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanDescriptor.<init>(BeanDescriptor.java:396) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanDescriptorManager.registerBeanDescriptor(BeanDescriptorManager.java:627) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:742) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:325) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:177) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:110) ~[ebean-core-12.8.3.jar:?]
at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35) ~[ebean-core-12.8.3.jar:?]
at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:130) ~[ebean-api-12.8.3.jar:?]
at io.ebean.DatabaseFactory.create(DatabaseFactory.java:78) ~[ebean-api-12.8.3.jar:?]
at ru.citc.hcm.api.app.ebean.EbeanConfigurationKt$ebeanInitializer$1$invoke$$inlined$bean$default$2.get(BeanDefinitionDsl.kt:1196) ~[main/:?]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1231) ~[spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.7.jar:5.3.7]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) [spring-beans-5.3.7.jar:5.3.7]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) [spring-context-5.3.7.jar:5.3.7]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) [spring-context-5.3.7.jar:5.3.7]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) [spring-boot-2.5.0.jar:2.5.0]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
at ru.citc.hcm.api.app.ApplicationKt.main(Application.kt:84) [main/:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.5.0.jar:2.5.0]
```

**Comment by rbygrave** [comment]
Ebean does not support `@Embeddable` that contains an `@ElementCollection` - this is a limitation of Ebean.

**Comment by rbygrave** [comment]
I think we will close this for now as a limitation.
