### ISSUE TITLE
When Lazy load of soft deleted bean - javax.persistence.EntityNotFoundException: Bean not found during lazy load or refresh. id[*] type[class *]

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2376]
### Steps to reproduce

- 2 cached bean related as ManyToOne
- Cached bean references the other cached bean
- Soft delete the referenced bean 
- Load the bean and navigate to the references bean and invoke lazy loading
- 

```console
javax.persistence.EntityNotFoundException: Bean not found during lazy load or refresh. id[SDLL-Person-01] type[class org.tests.cache.personinfo.PersonCacheInfo]

	at io.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:241)
	at io.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:168)
	at io.ebeaninternal.server.core.DefaultServer.loadBeanRef(DefaultServer.java:575)
	at io.ebean.bean.SingleBeanLoader$Ref.loadBean(SingleBeanLoader.java:56)
	at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:879)
	at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:856)
	at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:950)
	at org.tests.cache.personinfo.PersonCacheInfo._ebean_get_deleted(PersonCacheInfo.java:6)
	at org.tests.cache.personinfo.PersonCacheInfo.deleted(PersonCacheInfo.java:45)
	at org.tests.cache.personinfo.TestCacheSoftDeleteLazyLoad.softDeleteReferencedBean_when_lazyLoad_expect(TestCacheSoftDeleteLazyLoad.java:41)
	
```
```java
  @Test
  void softDeleteReferencedBean_when_lazyLoad_expect() {
    setup();
    // load cache
    DB.find(PersonCacheEmail.class, personEmailId);

    // soft delete our bean referenced by email
    PersonCacheInfo info = DB.find(PersonCacheInfo.class, personId);
    DB.delete(info);

    // load from cache (still references a now soft deleted bean)
    PersonCacheEmail email2 = DB.find(PersonCacheEmail.class, personEmailId);
    assert email2 != null;

    LoggedSql.start();
    PersonCacheInfo personInfo = email2.getPersonInfo();
    assertThat(personInfo).isNotNull();
    assertThat(personInfo.deleted()).isTrue(); // lazy load includes soft deletes

    List<String> sql = LoggedSql.stop();
    assertThat(sql).hasSize(1);
    assertThat(sql.get(0))
      .contains(" from person_cache_info t0 where t0.person_id = ?")
      .doesNotContain("and t0.deleted =");
  }
```

**Comment by rbygrave** [comment]
The "fix" for this will be to allow lazy loading of a reference bean to include soft deletes. The thinking here is that we already have a reference to the bean (via it's id) that was previously loaded - in this sense it is valid to lazy load it even when it has been soft deleted (which is consistent with the code example, the stream filter is checking for isDeleted() etc).

In a sense this fix might be slightly controversial but the current behaviour is throwing an exception and is pretty hard to deal with in a better way. That is, I don't see a better way to deal with a lazy load on a soft deleted bean.
