### ISSUE TITLE
Hit the L2 bean cache via property IN expression (when property is the id property)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2387]
Given an entity RCust with an Id property called `id`

This query below will hit the L2 bean cache where as currently it does not.

```java
    List<RCust> f0 = new QRCust()
      .id.in(ids) // just using a normal IN expression
      .findList();
```

Right now we are expected to use the `setIdIn()` expression.

```java
    List<RCust> f0 = new QRCust()
      .setIdIn(ids.toArray()) // a bit more expected than the setIdsIn() expression
      .findList();
```

**Comment by ulyChou** [comment]
Hello Rob
I urgently obtained the latest code for the local test, currently L2 cache can be correctly hit, but the ids obtained by using MGET is an array, maybe some historical logic codes need to be adjusted, please take a look at this problem

`2021-09-23 09:47:36.217 TRACE 7000 --- [nio-8300-exec-9] io.ebean.cache.BEAN                      :    MGET Role([[1]]) - hits:[]`

`java.lang.NumberFormatException: For input string: "[1]"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]
	at java.base/java.lang.Long.parseLong(Long.java:692) ~[na:na]
	at java.base/java.lang.Long.valueOf(Long.java:1144) ~[na:na]
	at io.ebeaninternal.server.core.BasicTypeConverter.toLong(BasicTypeConverter.java:294) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.type.ScalarTypeLong.toBeanType(ScalarTypeLong.java:46) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.type.ScalarTypeLong.toBeanType(ScalarTypeLong.java:19) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.id.IdBinderSimple.convertSetId(IdBinderSimple.java:246) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.id.IdBinderSimple.addIdInBindValues(IdBinderSimple.java:149) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.expression.IdInExpression.addBindValues(IdInExpression.java:81) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.expression.DefaultExpressionList.addBindValues(DefaultExpressionList.java:636) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.expression.DefaultExpressionRequest.<init>(DefaultExpressionRequest.java:37) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.query.CQueryPredicates.prepare(CQueryPredicates.java:204) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:340) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:342) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:131) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:423) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1511) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1490) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1481) ~[ebean-core-12.11.5.jar:na]
	at io.ebean.typequery.TQRootBean.findList(TQRootBean.java:1632) ~[ebean-querybean-12.11.5.jar:na]`

**Comment by rbygrave** [comment]
What does the query code look like?  

I suspect it is using `setIdIn(ids)` where ids is a collection and that method is taking varargs.  Can you confirm that?

For example, changing to `setIdIn(ids.toArray())` would fix that issue.

**Comment by ulyChou** [comment]
`Role.where().id.isIn(roleIds).findList()`

```
2021-09-23 10:43:34.787  WARN 29588 --- [nio-8300-exec-3] io.ebean.redis.RedisCache                : Error when reading redis cache

redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'mget' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:135) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:169) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:223) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:304) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryJedis.mget(BinaryJedis.java:872) ~[jedis-3.6.3.jar:na]
	at io.ebean.redis.RedisCache.getAll(RedisCache.java:124) ~[ebean-redis-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.cacheIdLookup(BeanDescriptorCacheHelp.java:353) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.BeanDescriptor.cacheIdLookup(BeanDescriptor.java:1306) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.OrmQueryRequest.getFromBeanCache(OrmQueryRequest.java:612) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1497) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1490) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1481) ~[ebean-core-12.11.5.jar:na]
	at io.ebean.typequery.TQRootBean.findList(TQRootBean.java:1632) ~[ebean-querybean-12.11.5.jar:na]
```

`Role.where().setIdIn(roleIds.toLongArray()).findList()`

```
2021-09-23 10:47:08.367 TRACE 30124 --- [nio-8300-exec-3] io.ebean.cache.BEAN                      :    MGET Role([[J@68bda019]) - hits:[]
2021-09-23 10:47:08.377 ERROR 30124 --- [nio-8300-exec-3] c.d.e.c.w.e.a.GlobalExceptionHandler     : 

java.lang.NumberFormatException: For input string: "[J@68bda019"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]
	at java.base/java.lang.Long.parseLong(Long.java:692) ~[na:na]
	at java.base/java.lang.Long.valueOf(Long.java:1144) ~[na:na]
	at io.ebeaninternal.server.core.BasicTypeConverter.toLong(BasicTypeConverter.java:294) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.type.ScalarTypeLong.toBeanType(ScalarTypeLong.java:46) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.type.ScalarTypeLong.toBeanType(ScalarTypeLong.java:19) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.id.IdBinderSimple.convertSetId(IdBinderSimple.java:246) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.id.IdBinderSimple.addIdInBindValues(IdBinderSimple.java:149) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.expression.IdInExpression.addBindValues(IdInExpression.java:81) ~[ebean-core-12.11.5.jar:na
```]

**Comment by ulyChou** [comment]
Then I tried to debug it
Expect values= [1, 2]
The actual values [[1, 2]]

![image](https://user-images.githubusercontent.com/46878819/134448251-d89de85f-edd1-48b9-8989-528c1d488972.png)

**Comment by rbygrave** [comment]
> roleIds.toLongArray()

What is the type of rolesIds in this case?  What is the response type of the toLongArray() method?  Is this Kotlin?
The response type of that is not been treated as varargs/array type.

**Comment by ulyChou** [comment]
Thank you for your advice

lang：kotlin

`Role.where().setIdIn(*roleIds.toTypedArray()).findList()`

```
2021-09-23 11:20:19.739  WARN 16460 --- [io-8300-exec-10] io.ebean.redis.RedisCache                : Error when reading redis cache

redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'mget' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:135) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:169) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:223) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:304) ~[jedis-3.6.3.jar:na]
	at redis.clients.jedis.BinaryJedis.mget(BinaryJedis.java:872) ~[jedis-3.6.3.jar:na]
	at io.ebean.redis.RedisCache.getAll(RedisCache.java:124) ~[ebean-redis-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.cacheIdLookup(BeanDescriptorCacheHelp.java:353) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.deploy.BeanDescriptor.cacheIdLookup(BeanDescriptor.java:1306) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.OrmQueryRequest.getFromBeanCache(OrmQueryRequest.java:612) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1497) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1490) ~[ebean-core-12.11.5.jar:na]
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1481) ~[ebean-core-12.11.5.jar:na]
	at io.ebean.typequery.TQRootBean.findList(TQRootBean.java:1632) ~[ebean-querybean-12.11.5.jar:na]
```

**Comment by rbygrave** [comment]
> redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'mget' command

Ah, we can get this when there are no ids.  That is, when the ids is an empty collection and we try and hit redis we get this error - I suspect this is the problem here.

> setIdIn(Collection<?> ids)  ... taking a collection

I will overload `setIdIn()` to additionally take a `Collection<?>` (in addition to varargs).  That should resolve that other issue / much better that converting to an array.

**Comment by ulyChou** [comment]
That's exactly what you said

when ids is an empty array， try hit redis cache

**Comment by rbygrave** [comment]
Cool. I have got a failing test and fix for that as #2389

**Comment by rbygrave** [comment]
Right, thanks for that @ulyChou - all looks good now. I will be looking to release this 12.12.0 version shortly.

**Comment by ulyChou** [comment]
@rbygrave 
ohh~
Thank you, I have a big communication barrier between Java and English, but I am very interested in Ebean

**Comment by rbygrave** [comment]
> I have a big communication barrier between Java and English

You are doing very well, no problems at all - we can both speak Java :)
