### ISSUE TITLE
NoSuchMethodError during DB creation

### ISSUE THREAD

**Issue by gdoenlen** [ebean-orm/ebean#2417]
I upgraded my application to ebean 12.12.2 and this error is being thrown during DB creation. It reproduces on both jdk 16 and 17. 

## Expected behavior
Db is created

## Actual behavior
```
16:15:15.523 [main] ERROR io.ebean - Error trying to create the default Database
java.lang.NoSuchMethodError: 'java.util.List io.avaje.classpath.scanner.ClassPathScanner.scanForClasses(java.lang.String, java.util.function.Predicate)'
        at io.ebeaninternal.server.core.bootup.BootupClassPathSearch.getBootupClasses(BootupClassPathSearch.java:53)
        at io.ebeaninternal.server.core.bootup.BootupClassPathSearch.search(BootupClassPathSearch.java:27)
        at io.ebeaninternal.server.core.DefaultContainer.bootupClasses1(DefaultContainer.java:185)
        at io.ebeaninternal.server.core.DefaultContainer.bootupClasses(DefaultContainer.java:162)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:83)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:63)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
        at io.ebean.DatabaseFactory.create(DatabaseFactory.java:60)
        at io.ebean.DbContext.getWithCreate(DbContext.java:103)
        at io.ebean.DbContext.<init>(DbContext.java:42)
        at io.ebean.DbContext.<clinit>(DbContext.java:23)
        at io.ebean.DB.<clinit>(DB.java:65)
```
### Steps to reproduce
My application is here: 

https://github.com/SFXD/trust-bot/blob/master/pom.xml#L12

Upgrade the ebean version to 12.12.2 and run: `mvn clean compile process-classes test`

**Comment by rbygrave** [comment]
The version of ebean-migration is old / needs updating as well.

**Comment by rbygrave** [comment]
To be more explicit.

This error says NoSuchMethod for

io.avaje.classpath.scanner.ClassPathScanner.scanForClasses(java.lang.String,
java.util.function.Predicate)'

At that point we are interested in checking the version of the dependency
that brings in that class

mvn dependency:tree shows us what brings in the dependency (both ebean and
ebean-migration) and we are getting an older version of the dependency via
the older version of ebean-migration.
