### ISSUE TITLE
DBArray is not loaded in `asDto` Postgres queries

### ISSUE THREAD

**Issue by majkiw** [ebean-orm/ebean#2435]
## Expected behavior
When an underlying table contains a `text[]` or `character varying[]` and we use `.asDto` the value from that column should appear in the DTO, just like it does when loading entities

## Actual behavior
The field containing array is returned as `null` in `DtoQuery`.

### Steps to reproduce
See test TestDbArray_basic#asDto_withArray  in:
https://github.com/ebean-orm/ebean/pull/2434

**Comment by IvanPetkov23** [comment]
I still cannot make it work with `text[]` on PostgreSQL. When trying `String[]` or `List<String>` on DTO, it gets an error:

```java
java.lang.NullPointerException: Cannot invoke "io.ebean.core.type.ScalarType.read(io.ebean.core.type.DataReader)" because "this.scalarTypes[i]" is null
    at io.ebeaninternal.server.dto.DtoMetaConstructor.process(DtoMetaConstructor.java:47)
    at io.ebeaninternal.server.dto.DtoQueryPlanConstructor.readRow(DtoQueryPlanConstructor.java:21)
    at io.ebeaninternal.server.core.DtoQueryRequest.readNextBean(DtoQueryRequest.java:126)
    at io.ebeaninternal.server.query.DtoQueryEngine.findList(DtoQueryEngine.java:35)
    at io.ebeaninternal.server.core.DtoQueryRequest.findList(DtoQueryRequest.java:115)
    at io.ebeaninternal.server.core.DefaultServer.findDtoList(DefaultServer.java:1451)
    at io.ebeaninternal.server.querydefn.DefaultDtoQuery.findList(DefaultDtoQuery.java:135)```
