### ISSUE TITLE
BeanDescriptor.createEntityBean works differently for entities with and without an explicit constructor

### ISSUE THREAD

**Issue by npokr** [ebean-orm/ebean#2476]
## Expected behavior
Entities that differ only in the presence of a constructor fetch the same way.

## Actual behavior
When entity has @ElementCollection field initialized with empty list, findOne works fine for explicit constructor case, but gives errors or unexpected results for opposite case.

### Steps to reproduce
Let's take a look at TestElementCollectionEmbeddedListCache test. With current EcblPerson it passes.
Code `EcblPerson one = DB.find(EcblPerson.class)
      .setId(person.getId())
      .fetch("phoneNumbers")
      .findOne();`
fills the "one" successfully.
But if you remove constructor from EcblPerson, the above code throws an error "java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class io.ebean.bean.BeanCollection".
When EcblPerson has explicit constructor,  BeanDescriptor.createEntityBean returns null in phoneNumbers field, but with implicit default constructor phoneNumbers initialized with empty list, what prevents all further manipulations with this collection.

**Comment by rbygrave** [comment]
```
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class io.ebean.bean.BeanCollection (java.util.ArrayList is in module java.base of loader 'bootstrap'; io.ebean.bean.BeanCollection is in unnamed module of loader 'app')

	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.addBeanToCollectionWithCreate(BeanPropertyAssocMany.java:229)
	at io.ebeaninternal.server.query.SqlTreeNodeManyRoot.load(SqlTreeNodeManyRoot.java:35)
	at io.ebeaninternal.server.query.SqlTreeNodeBean$Load.loadChildren(SqlTreeNodeBean.java:319)
	at io.ebeaninternal.server.query.SqlTreeNodeBean$Load.initialise(SqlTreeNodeBean.java:423)
	at io.ebeaninternal.server.query.SqlTreeNodeBean$Load.perform(SqlTreeNodeBean.java:430)
	at io.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:453)
	at io.ebeaninternal.server.query.SqlTreeNodeRoot.load(SqlTreeNodeRoot.java:43)
	at io.ebeaninternal.server.query.CQuery.readNextBean(CQuery.java:415)
	at io.ebeaninternal.server.query.CQuery.hasNext(CQuery.java:489)
	at io.ebeaninternal.server.query.CQuery.readBean(CQuery.java:463)
	at io.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:391)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:175)
	at io.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:345)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1115)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1132)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOne(DefaultOrmQuery.java:1510)
	at org.tests.model.elementcollection.TestElementCollectionEmbeddedListCache2.test(TestElementCollectionEmbeddedListCache2.java:28)
	at ...
```

**Comment by rbygrave** [comment]
Thanks for the test case description. We have a PR that fixes the issue but I'll investigate a better longer term solution which would treat element collection relationships like ToMany relationships wrt enhancement.
