### ISSUE TITLE
@Id value is always 0 after save()

### ISSUE THREAD

**Issue by cyrilfr** [ebean-orm/ebean#2490]
## Expected behavior

The entity ID should be set with the inserted ID (here an auto-incremented long) after a call to `save()`.

## Actual behavior

It's always 0.

### Steps to reproduce

```java
@MappedSuperclass
public abstract class MyEntity extends Model {

  @Id
  protected long id;

  public void setId(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

}

@MappedSuperclass
public abstract class User extends MyEntity {

  @NotNull
  protected String firstName;

  @NotNull
  protected String lastName;

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getFirstName() {
    return firstName;
  }

  public String getLastName() {
    return lastName;
  }

}

@Entity
public class Admin extends User { }

var admin = new Admin();
admin.setFirstName("John");
admin.setLastName("Doe");
admin.save();

System.out.println("Admin ID: " + admin.getId());

var other = new Admin();
other.setFirstName("Mike");
other.setLastName("Horn");
other.save();

System.out.println("Admin ID: " + other.getId());

```

```console
Admin ID: 0
Admin ID: 0
```

**Comment by rbygrave** [comment]
Can you git clone one of the example projects and reproduce this?  We have a lot of tests that do exactly this and there is no issue so I suspect there is something interesting with the setup of the project.

If you clone and run the examples do they work?  Are you able to modify an example project to reproduce the issue?
- https://github.com/ebean-orm-examples/example-minimal
- https://github.com/ebean-orm/examples

**Comment by cyrilfr** [comment]
I forgot to mention that I'm using Play Framework with Java 11 and MariaDB:

- Play Framework 2.8.13
- sbt-play-ebean 6.0.0 (ebean 11.45.1)
- mariadb-java-client 2.7.4

Default configuration.

I cannot run your example: 
```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
        at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
        at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
        at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
        at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
        at sbt.StandardMain$.initialState(Main.scala:125)
        at sbt.xMain.run(Main.scala:34)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)

[info] Loading global plugins from /home/cyril/.sbt/0.13/plugins
[info] Loading project definition from /home/cyril/Documents/example-minimal/project
[info] Set current project to example-mininal (in build file:/home/cyril/Documents/example-minimal/)
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at sbt.JLine$.sbt$JLine$$terminal(LineReader.scala:85)
        at sbt.JLine$.withTerminal(LineReader.scala:88)
        at sbt.JLine$.usingTerminal(LineReader.scala:96)
        at sbt.JLine$.createReader(LineReader.scala:102)
        at sbt.FullReader.<init>(LineReader.scala:132)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:184)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:181)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.doX$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:190)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:109)
        at sbt.xMain.run(Main.scala:38)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by rbygrave** [comment]
> I cannot run your example:

Build it with maven.  I see there is a really really old build.sbt in there ... don't use that (or update it if you know how to).  I maintain the maven pom / maven build so use maven to build the project.

Note that there are also gradle example projects in https://github.com/ebean-orm/examples

Cheers, Rob.

**Comment by cyrilfr** [comment]
I've been able to build and run with Maven this example: https://github.com/ebean-orm-examples/example-minimal
What could be the reason why the ID remains 0? Should I use MySQL instead of MariaDB?

**Comment by rbygrave** [comment]
> What could be the reason why the ID remains 0?

Typically I'd start by using process of elimination to determine the difference between the 2 projects. Typically you'd start by comparing the versions of dependencies.

Secondly the question is are you using ebean-test for testing?  If so then switching between database platforms is a single property change to `ebean.test.platform` from `mariadb` to `mysql` (or postgres, h2, sqlserver17 ...)


> Should I use MySQL instead of MariaDB?

If the project uses `ebean-test` then switching between database platforms is a single property change to `ebean.test.platform`.

See:
https://ebean.io/docs/intro/configuration/#testing
https://ebean.io/docs/testing/
https://ebean.io/docs/database/mariadb/
https://ebean.io/docs/database/mysql/   ... oh, broken yaml docs on this page - I better fix that

**Comment by cyrilfr** [comment]
I updated my project from [sbt-play-ebean](https://github.com/playframework/play-ebean) 6.0.0 (ebean 11.45.1) to sbt-play-ebean 6.2.0-RC3 (ebean 12.8.1) and the bug has been fixed!
Thank you very much for your time, I really appreciate ;)

**Comment by rbygrave** [comment]
Ok, I'll close this then.

Cheers, Rob.
