### ISSUE TITLE
NullPointerException for @Embeddable at update()

### ISSUE THREAD

**Issue by cyrilfr** [ebean-orm/ebean#2493]
## Expected behavior

The entity is updated without exception.

## Actual behavior

The entity is updated with a NullPointerException.

### Steps to reproduce

```java
@Embeddable
public class Address {
    @NotNull
    @Column(name = "address_street")
    public String street;

    @NotNull
    @Column(name = "address_street_number")
    public String streetNumber;

    @Column(name = "address_extra")
    public String extra;

    @NotNull
    @Length(10)
    @Column(name = "address_postal_code")
    public String postalCode;

    @NotNull
    @Column(name = "address_city")
    public String city;

    @NotNull
    @Column(name = "address_country")
    public String country;
}

@Entity
public class User extends Model {

   ...

   @Embedded
   public Address address;

   ...

}
```
The `extra` column could be null.

```
var address = new Address();
address.setStreet("Bahnhofstrasse");
address.setStreetNumber("13");
address.setPostalCode("1200");
address.setCity("Zurich");

user.setAddress(address);
user.update();
```

```console
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.lang.NullPointerException: null
        at io.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:194)
        at io.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:207)
        at io.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:189)
        at io.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:571)
        at io.ebean.bean.SingleBeanLoader$Dflt.loadBean(SingleBeanLoader.java:70)
        at io.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:852)
        at io.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:819)
        at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:923)
        at models.common.Address._ebean_get_extra(Address.java:6)
        at models.common.Address.getExtra(Address.java:51)
```

**Comment by rbygrave** [comment]
Can you create a failing test that does not use Akka ?  If so include the stack trace from that failing test.  

That is, failing tests should not rely on third party libraries like Akka, Play, Spring etc.

**Comment by rbygrave** [comment]
I'll close this for now.  Re-open with a failing test case etc.  Thanks.
