### ISSUE TITLE
Possible malicious concurrent access of cache entries

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2677]
## Expected behavior

Cache should work reliable

## Actual behavior

db-periodic thread may throw `java.lang.IllegalArgumentException: Comparison method violates its general contract!` under rare conditions.

/edit: an exception in `runEviction` will stop further calls to `runEviction` - so the cache will not be trimmed and the application will run into an OOM sooner or later.

### Steps to reproduce

Did not yet write a test case, As it may be difficult to reproduce. We saw this exception one time production. I think it may happen if cache-entries are accessed during sorting.
Theoretical error:
There are three cache entries. 
Entry A: lastAccessed@00:00:01
Entry B: lastAccessed@00:00:02
Entry C: lastAccessed@00:00:03
... and many other ones

if sorting is done on timestamp 00:00:05 and the sort algoritm may compares 
B & C so B < C
A & B so A < B
the contract says now, that A < C, but if A is accessed during sorting, its last accessed timestamp may be changed to 00:00:05 and the sort fails. I hope it is clear, what I mean.

```java
if (trimForMaxSize > 0 && activeList.size() > maxSize) {
      // sort into last access time ascending
      activeList.sort(BY_LAST_ACCESS); // <-- lastAccessed must noch change due sorting
      int trimSize = getTrimSize();
      for (int i = trimSize; i < activeList.size(); i++) {
        // remove if still in the cache
        if (map.remove(activeList.get(i).getKey()) != null) {
          trimmedByLRU++;
        }
      }
    }
```

Line numbers of ebean 12:
```console
io.ebean.BackgroundExecutor : Error while executing the task io.ebeaninternal.server.cache.DefaultServerCache$EvictionRunnable@51bfb6e8
 java.lang.IllegalArgumentException: Comparison method violates its general contract!
  at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
  at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
  at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
  at java.base/java.util.TimSort.sort(TimSort.java:245)
  at java.base/java.util.Arrays.sort(Arrays.java:1515)
  at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
  at io.ebeaninternal.server.cache.DefaultServerCache.runEviction(DefaultServerCache.java:278)
  at io.ebeaninternal.server.cache.DefaultServerCache$EvictionRunnable.run(DefaultServerCache.java:306)
  at io.ebeaninternal.server.executor.DefaultBackgroundExecutor.lambda$logExceptions$0(DefaultBackground
Executor.java:77)
  at de.foconis.core.api.app.ThreadContextWrapper.lambda$1(ThreadContextWrapper.java:39)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

### Possible fixes:

`activeList.sort(BY_LAST_ACCESS);` should work on a copy of 'lastAccessed'. This can be easily done in the while loop above.

**Comment by rbygrave** [comment]
I think https://github.com/ebean-orm/ebean/pull/2679 ... is a decent fix for this issue.

**Comment by rPraml** [comment]
Great, thanks for the fix.
