### ISSUE TITLE
findDto nonsupport setter chain (accessor style setters, both fluid style and non fluid style) 

### ISSUE THREAD

**Issue by cn-src** [ebean-orm/ebean#2736]
## Expected behavior

Support for Lombok `@Data @Accessors(chain = true)` style dto beans that use **_accessors_** rather than **_bean spec setters_**.

## Actual behavior
`findDto()` nonsupport setter lombok chain.

### Steps to reproduce

```java
public class Main {
    public static void main(String[] args) {
        final List<UserDto> list = DB.findDto(UserDto.class, "SELECT id,name from sys_user")
            .findList();
        System.out.println(list);
    }
}

@Data
@Accessors(chain = true)
public class UserDto {
    UUID id;
    String name;
}
```

```console
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Exception in thread "main" java.lang.IllegalStateException: Unable to map DB column id to a property with a setter method on class demo.UserDto. Consider query.setRelaxedMode() to skip mapping this column.
	at io.ebeaninternal.server.dto.DtoMappingRequest.mapColumn(DtoMappingRequest.java:79)
	at io.ebeaninternal.server.dto.DtoMappingRequest.mapSetters(DtoMappingRequest.java:55)
	at io.ebeaninternal.server.dto.DtoMeta.matchSetters(DtoMeta.java:69)
	at io.ebeaninternal.server.dto.DtoMeta.match(DtoMeta.java:55)
	at io.ebeaninternal.server.dto.DtoBeanDescriptor.buildPlan(DtoBeanDescriptor.java:33)
	at io.ebeaninternal.server.querydefn.DefaultDtoQuery.buildPlan(DefaultDtoQuery.java:77)
	at io.ebeaninternal.server.core.DtoQueryRequest.obtainPlan(DtoQueryRequest.java:79)
	at io.ebeaninternal.server.core.DtoQueryRequest.setResultSet(DtoQueryRequest.java:70)
	at io.ebeaninternal.server.core.AbstractSqlQueryRequest.executeAsSql(AbstractSqlQueryRequest.java:161)
	at io.ebeaninternal.server.core.DtoQueryRequest.executeSql(DtoQueryRequest.java:62)
	at io.ebeaninternal.server.query.DtoQueryEngine.findList(DtoQueryEngine.java:25)
	at io.ebeaninternal.server.core.DtoQueryRequest.findList(DtoQueryRequest.java:114)
	at io.ebeaninternal.server.core.DefaultServer.findDtoList(DefaultServer.java:1600)
	at io.ebeaninternal.server.querydefn.DefaultDtoQuery.findList(DefaultDtoQuery.java:118)
	at demo.Main.main(Main.java:13)
```

**Comment by rbygrave** [comment]
Yes, we can support this easily enough plus imo it's a good style and approach.
