### ISSUE TITLE
ModelContainer.applyChangeSet(ModelContainer.java:167) - IllegalArgumentException: No rule for io.ebeaninternal.dbmigration.migration.CreateSchema

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2742]
```console
Exception in thread "main" java.lang.IllegalArgumentException: No rule for io.ebeaninternal.dbmigration.migration.CreateSchema@11653e3b
	at io.ebeaninternal.dbmigration.model.ModelContainer.applyChangeSet(ModelContainer.java:167)
	at io.ebeaninternal.dbmigration.model.ModelContainer.apply(ModelContainer.java:117)
	at io.ebeaninternal.dbmigration.model.MigrationModel.readMigrations(MigrationModel.java:57)
	at io.ebeaninternal.dbmigration.model.MigrationModel.read(MigrationModel.java:36)
	at io.ebeaninternal.dbmigration.DefaultDbMigration$Request.<init>(DefaultDbMigration.java:504)
	at io.ebeaninternal.dbmigration.DefaultDbMigration.createRequest(DefaultDbMigration.java:481)
	at io.ebeaninternal.dbmigration.DefaultDbMigration.generateMigrationFor(DefaultDbMigration.java:307)
	at io.ebeaninternal.dbmigration.DefaultDbMigration.generateMigration(DefaultDbMigration.java:266)
	at main.GenerateDbMigration.main(GenerateDbMigration.java:18)
```

**Comment by rbygrave** [comment]
The current workaround is to remove the `<createSchema name="foo"/>` from the `<changeSet type="apply">`
