### ISSUE TITLE
In dynamic conditions, redundant 'and'

### ISSUE THREAD

**Issue by cn-src** [ebean-orm/ebean#2752]
### Steps to reproduce

```java
 final ExpressionList<User> where = DB.find(User.class).where();
        String value1 = "";
        String value2 = "xx";
        if (!value1.isEmpty()) {
            where.eq("name", value1);
        }
        where.or();
        if (!value2.isEmpty()) {
            where.eq("name", value2);
        }
        if (!value2.isEmpty()) {
            where.eq("name", value2);
        }
        where.endOr();
        where.findList();
```

```console
19:47:29.896 [main] INFO io.ebean.core - Started database[db] platform[POSTGRES] in 1848ms
19:47:30.018 [main] DEBUG io.ebean.SUM - txn[1001] ERROR executing query, bindLog[xx,xx] error[ERROR: syntax error at or near "and"   位置：47]
19:47:30.086 [main] DEBUG io.ebean.TXN - txn[1001] Commit
Exception in thread "main" javax.persistence.PersistenceException: Query threw SQLException:ERROR: syntax error at or near "and"
  位置：47 Bind values:[xx,xx] Query was:select t0.id, t0.name from sys_user t0 where  and t0.name = ? and t0.name = ?
	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:80)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:245)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:142)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.translate(DefaultOrmQueryEngine.java:44)
	at io.ebeaninternal.server.core.OrmQueryRequest.translate(OrmQueryRequest.java:58)
	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:635)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:374)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:132)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:404)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1464)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1443)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1482)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:452)
	at demo.Main.main(Main.java:27)
```

**Comment by rbygrave** [comment]
FYI

```java
public interface Junction<T> extends Expression, ExpressionList<T>
```

**Comment by cn-src** [comment]
Thank you for your response, I appreciate it.
