### ISSUE TITLE
Concurrent modification of listenerNotify list

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [ebean-orm/ebean#2818]
## Expected behavior

While listeners are being processed, we should not encounter any error due to concurrently modified list.

## Actual behavior

Sometimes, while listeners are being processed, we encounter an exception saying that list have been modified during iteration.

### Steps to reproduce

I did not succeed to reproduce it manually yet. The only hint I have is that this error seems (not sure) to occurs when we are executing a `BeanPersistListener` `updated` method that execute a `DB.sqlUpdate` on the same object as the one concerned by the listener.

```console
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.605137866Z lcdp-monolith-service 1045 	at java.base/java.lang.Thread.run(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.605072332Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.605024628Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604961416Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604914781Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604846543Z lcdp-monolith-service 1045 	at datadog.trace.bootstrap.instrumentation.java.concurrent.RunnableWrapper.run(RunnableWrapper.java:20)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.60479844Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.executor.DefaultBackgroundExecutor.lambda$logExceptions$0(DefaultBackgroundExecutor.java:77)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604732542Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.transaction.PostCommitProcessing.lambda$backgroundNotify$0(PostCommitProcessing.java:122)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604689622Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.transaction.PostCommitProcessing.localPersistListenersNotify(PostCommitProcessing.java:147)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.6046234Z lcdp-monolith-service 1045 	at java.base/java.util.ArrayList$Itr.next(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.604573619Z lcdp-monolith-service 1045 	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)"
"2022-08-31T13:26:28.605Z",,"""lcdp-monolith""","2022-08-31T13:26:28.60450221Z lcdp-monolith-service 1045 java.util.ConcurrentModificationException: null"
"2022-08-31T13:26:28.605Z","""error""","""lcdp-monolith""","2022-08-31T13:26:28.604484173Z lcdp-monolith-service 1045 ebean-default1185 - [[31merror[0m] - io.ebean.BackgroundExecutor - Error while executing the task io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$2289/0x000000084189f040@c0ce0ce"
"2022-08-31T13:26:28.599Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598496823Z lcdp-monolith-service 1045 	at java.base/java.lang.Thread.run(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598446808Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598400034Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598355683Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598308363Z lcdp-monolith-service 1045 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598258494Z lcdp-monolith-service 1045 	at datadog.trace.bootstrap.instrumentation.java.concurrent.RunnableWrapper.run(RunnableWrapper.java:20)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598212824Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.executor.DefaultBackgroundExecutor.lambda$logExceptions$0(DefaultBackgroundExecutor.java:77)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598152311Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.transaction.PostCommitProcessing.lambda$backgroundNotify$0(PostCommitProcessing.java:122)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598102218Z lcdp-monolith-service 1045 	at io.ebeaninternal.server.transaction.PostCommitProcessing.localPersistListenersNotify(PostCommitProcessing.java:147)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.59805396Z lcdp-monolith-service 1045 	at java.base/java.util.ArrayList$Itr.next(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.598017249Z lcdp-monolith-service 1045 	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)"
"2022-08-31T13:26:28.598Z",,"""lcdp-monolith""","2022-08-31T13:26:28.59791241Z lcdp-monolith-service 1045 java.util.ConcurrentModificationException: null"
"2022-08-31T13:26:28.598Z","""error""","""lcdp-monolith""","2022-08-31T13:26:28.597888569Z lcdp-monolith-service 1045 ebean-default1181 - [[31merror[0m] - io.ebean.BackgroundExecutor - Error while executing the task io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$2289/0x000000084189f040@b03e2a7"
```

Yours faithfully,
LCDP

**Comment by rbygrave** [comment]
Is there use of `commitAndContinue()`  ?

**Comment by AntoineDuComptoirDesPharmacies** [comment]
@rbygrave 
No, for the moment we never use `commitAndContinue` in our codebase.

However, in the code that commit the object triggering this listener, we are using `transaction.setNestedUseSavepoint()` at high level and tons of nested `DB.beginTransaction()` / `commit()` below.

Can this issue be related to the use of savepoints ?

**Comment by rbygrave** [comment]
Well yes I do suspect it's related to SavepointTransaction.  I was looking through the code around commitAndContinue() and in that saw that the savepoint transactions looks wrong in its use of TransactionEvent - so very likely thats the problem (SavepointTransaction should use its own TransactionEvent).
