### ISSUE TITLE
Ebean 13.9.3 : org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled

### ISSUE THREAD

**Issue by vladimirfx** [ebean-orm/ebean#2862]
Please add a check for the `autoCommit` flag in PostgresPlatformProvider before calling rollback (https://github.com/ebean-orm/ebean/blob/7152cf656b0850682bb6428ed726c98dbcf4cb4a/platforms/postgres/src/main/java/io/ebean/platform/postgres/PostgresPlatformProvider.java#L65). I can't actually disable autoCommit on Zonky embedded database in tests (https://github.com/zonkyio/embedded-database-spring-test/issues/158).

## Expected behavior

No exception should be thrown (like on 13.9.2).

## Actual behavior

```log
javax.persistence.PersistenceException: javax.persistence.PersistenceException: Error trying to determine postgres platform via JDBC metadata
	at app//io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:58)
	at app//io.ebeaninternal.server.core.DefaultContainer.setDatabasePlatform(DefaultContainer.java:207)
	at app//io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:95)
	at app//io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:29)
	at app//io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:136)
	at app//io.ebean.DatabaseFactory.create(DatabaseFactory.java:85)
	at app//ru.citc.hcm.backend.platform.ebean.EbeanConfigurationKt$ebeanInitializer$1$invoke$$inlined$bean$default$2.get(BeanDefinitionDsl.kt:1196)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	... 84 more
Caused by: javax.persistence.PersistenceException: Error trying to determine postgres platform via JDBC metadata
	at app//io.ebean.platform.postgres.PostgresPlatformProvider.create(PostgresPlatformProvider.java:72)
	at app//io.ebeaninternal.server.core.DatabasePlatformFactory.byDatabaseMeta(DatabasePlatformFactory.java:96)
	at app//io.ebeaninternal.server.core.DatabasePlatformFactory.byDataSource(DatabasePlatformFactory.java:80)
	at app//io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:55)
	... 94 more
Caused by: org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
	at app//org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:893)
	at app//io.zonky.test.db.provider.support.BlockingDatabaseWrapper$BlockingConnectionWrapper.rollback(BlockingDatabaseWrapper.java:170)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at app//io.zonky.test.db.preparer.RecordingMethodInterceptor.invoke(RecordingMethodInterceptor.java:171)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at app/jdk.proxy3/jdk.proxy3.$Proxy135.rollback(Unknown Source)
	at app//io.ebean.platform.postgres.PostgresPlatformProvider.create(PostgresPlatformProvider.java:65)
	... 97 more
```

### Steps to reproduce

Use Pg connection with `autoCommit` enabled.

**Comment by rbygrave** [comment]
Nice, thanks !!
