### ISSUE TITLE
Delayed transaction commit cause NPE

### ISSUE THREAD

**Issue by rvowles** [ebean-orm/ebean#2886]
## Expected behavior

I was expecting a method wrapped in a `Transaction` annotation to be synchronous when committing transactions but this appears to not be the case.

## Actual behavior

I have in my code this:

```java
        save(dbFeatureValue)
        publish(dbFeatureValue)

...

  @Transactional
  private fun save(featureValue: DbFeatureValue) {
    database.save(featureValue)
  }

  private fun publish(featureValue: DbFeatureValue) {
    log.trace("publishing update for {}", featureValue) 
    cacheSource.publishFeatureChange(featureValue) // this gets put into an executor in a different thread
  }

```

what is happening is this (random race condition):

```console
07:59:35.081 [grizzly-http-server-17] DEBUG ?. io.ebean.SQL - txn[1259] insert into fh_env_feature_strategy (id, what_updated, feature_state, default_value, locked, retired, rollout_strat, when_updated, when_created, version, fk_who_updated, fk_environment_id, fk_feature_id) values (?,?,?,?,?,?,?,?,?,?,?,?,?); -- bind(e8c13f6e-6d2d-4f01-b6ea-7aceb6c76c80,null,null,[LOB],false,null,[],2022-11-05T07:59:35.080,2022-11-05T07:59:35.080,1,e235ffca-700b-4671-9ac8-2deb45b2c4fe,ed5546fe-832d-48bc-a63f-f69bbb43cc68,203ecfed-e4a2-492d-9ee0-c2d78c9006e9)
07:59:35.084 [grizzly-http-server-17] DEBUG ?. io.ebean.SUM - txn[1259] Inserted [DbFeatureValue] [e8c13f6e-6d2d-4f01-b6ea-7aceb6c76c80]
07:59:35.084 [grizzly-http-server-17] TRACE ?. io.featurehub.db.services.FeatureSqlApi - publishing update for io.featurehub.db.model.DbFeatureValue@85c16621
07:59:35.086 [ebean-db1] INFO  ?. io.ebean.ChangeLog - {"ts":1667588375084,"change":"I","type":"DbFeatureValue","id":"e8c13f6e-6d2d-4f01-b6ea-7aceb6c76c80","data":{"defaultValue":"12","locked":false,"rolloutStrategies":[],"whenUpdated":"2022-11-05T07:59:35.080","whenCreated":"2022-11-05T07:59:35.080","version":1,"whoUpdated":{"id":"e235ffca-700b-4671-9ac8-2deb45b2c4fe"},"environment":{"id":"ed5546fe-832d-48bc-a63f-f69bbb43cc68"},"feature":{"id":"203ecfed-e4a2-492d-9ee0-c2d78c9006e9"}}}
07:59:35.089 [pool-3-thread-2] DEBUG ?. io.ebean.SQL - txn[1260] select distinct on (t0.cache_name) t0.cache_name from fh_cache t0 join fh_organization u1 on u1.fk_named_cache = t0.cache_name join fh_portfolio u2 on u2.fk_org_id = u1.id join fh_application u3 on u3.fk_portfolio_id = u2.id join fh_environment u4 on u4.fk_app_id = u3.id join fh_env_feature_strategy u5 on u5.fk_environment_id = u4.id where u5.id = ?; --bind(e8c13f6e-6d2d-4f01-b6ea-7aceb6c76c80) --micros(3307)
07:59:35.089 [pool-3-thread-2] DEBUG ?. io.ebean.SUM - txn[1260] FindMany type[DbNamedCache] origin[CDPGAa.A.A] exeMicros[3377] rows[0] predicates[u5.id = ?] bind[e8c13f6e-6d2d-4f01-b6ea-7aceb6c76c80]
07:59:35.089 [grizzly-http-server-17] DEBUG ?. io.ebean.TXN - txn[1259] Commit
07:59:35.092 [pool-3-thread-2] ERROR ?. io.featurehub.db.publish.DbCacheSource - Failed to publish
java.lang.NullPointerException: null
	at io.featurehub.db.publish.DbCacheSource.getFeatureValueCacheName(DbCacheSource.kt:488) ~[classes/:?]
	at io.featurehub.db.publish.DbCacheSource.publishFeatureChange$lambda-10(DbCacheSource.kt:388) ~[classes/:?]

```

I'm not sure if I should force the database transaction to commit the transaction manually rather than using an annotation?

**Comment by rvowles** [comment]
I suspect this is a REQUIRES_NEW issue, so I'm going to close it.
