### ISSUE TITLE
Build with SqlServer is flaky

### ISSUE THREAD

**Issue by nPraml** [ebean-orm/ebean#2917]
Hi @rbygrave,

we noticed that the build of the sqlserver is flaky. I think you also have sometimes the problem: https://github.com/ebean-orm/ebean/actions/runs/3655326152/jobs/6176555814#step:5:97003

I could reproduced it also local on my machine with `mvn clean verify -Dgpg.skip -Dprops.file=testconfig/ebean-sqlserver19.properties` or with `mvn clean verify -Dgpg.skip -Dprops.file=testconfig/ebean-sqlserver17.properties`

What I've figured out by analyzing the problem:
If the build runs "fast enough" then nothing happens, the build is successful.
But if the build is littlebit "slower" then after some time the docker container will shut down, it will be removed and the next test cannot find the connection to the db. 
It is always an other test, that closes the db connection, e.g.

```console
[INFO] Running org.tests.unidirectional.TestUniDirectional
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 s - in org.tests.unidirectional.TestUniDirectional
[INFO] Running org.tests.saveassociation.TestSaveSamePK
Dez. 13, 2022 3:56:59 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNUNG: ConnectionID:7 ClientConnectionId: 454fc56f-c415-4163-a50b-7c861572b4fa Prelogin error: host localhost port 9435 Unexpected end of prelogin response after 0 bytes read
15:57:07.231 [sqlserver2017.heartBeat] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2017] min[2] max[200] free[2] busy[1] waiting[0] highWaterMark[3] waitCount[0] hitCount[647]
15:57:07.235 [sqlserver2017.heartBeat] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver20171] startTime[1670943427225] busySeconds[0] stackTrace[] stmt[null]

15:57:07.235 [sqlserver2017.heartBeat] ERROR io.ebean.datasource - FATAL: DataSourcePool [sqlserver2017] is down or has network error!!!
15:57:07.236 [sqlserver2017.heartBeat] WARN  io.ebean.datasource - Error when trying to return connection to pool, closing fully.
com.microsoft.sqlserver.jdbc.SQLServerException: Die Verbindung wurde geschlossen.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.checkClosed(SQLServerConnection.java:1532)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.clearWarnings(SQLServerConnection.java:4354)
        at io.ebean.datasource.pool.PooledConnection.close(PooledConnection.java:412)
        at io.ebean.datasource.pool.ConnectionPool.checkDataSource(ConnectionPool.java:408)
        at io.ebean.datasource.pool.ConnectionPool$HeartBeatRunnable.run(ConnectionPool.java:189)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
15:57:21.770 [sqlserver2017-ro.heartBeat] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2017-ro] min[2] max[200] free[0] busy[1] waiting[0] highWaterMark[1] waitCount[0] hitCount[635]
15:57:21.771 [sqlserver2017-ro.heartBeat] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver2017-ro0] startTime[1670943418884] busySeconds[22] stackTrace[] stmt[null]

15:57:21.771 [sqlserver2017-ro.heartBeat] ERROR io.ebean.datasource - FATAL: DataSourcePool [sqlserver2017-ro] is down or has network error!!!
15:57:21.771 [main] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2017-ro] min[2] max[200] free[0] busy[1] waiting[0] highWaterMark[1] waitCount[0] hitCount[635]
15:57:21.772 [main] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver2017-ro0] startTime[1670943418884] busySeconds[22] stackTrace[] stmt[null]

15:57:21.772 [main] WARN  io.ebean.datasource - Error when trying to return connection to pool, closing fully.
com.microsoft.sqlserver.jdbc.SQLServerException: Die Verbindung wurde geschlossen.
```
OR

```console
[INFO] Running org.tests.cascade.TestMultiCascadeBatch
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in org.tests.cascade.TestMultiCascadeBatch
[INFO] Running org.tests.cascade.TestOrphanCollectionReplacement
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 s - in org.tests.cascade.TestOrphanCollectionReplacement
[INFO] Running org.tests.cascade.TestOrderedList
16:32:08.562 [main] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2019] min[2] max[200] free[1] busy[1] waiting[0] highWaterMark[3] waitCount[0] hitCount[637]
16:32:08.566 [main] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver20192] startTime[1670945528555] busySeconds[0] stackTrace[] stmt[null]

16:32:08.566 [main] ERROR io.ebean.datasource - FATAL: DataSourcePool [sqlserver2019] is down or has network error!!!
16:32:08.568 [main] WARN  io.ebean.datasource - Error when trying to return connection to pool, closing fully.
com.microsoft.sqlserver.jdbc.SQLServerException: Die Verbindung wurde geschlossen.
```
I tried to get more information to set log level of `io.ebean` to `TRACE`:

```console
16:56:14.949 [main] DEBUG io.ebean.SQL - txn[1414] insert into e_basic_with_ex (id, deleted, version) values (?,?,?); -- bind(4,false,1)
16:56:14.951 [main] TRACE io.ebean.TXN - txn[1414] Commit - query only
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 s - in org.tests.lifecycle.TestLifecycleExceptions
[INFO] Running org.tests.lifecycle.TestLifecycleWithLog
16:56:14.953 [main] DEBUG io.ebean.SQL - txn[1415] insert into e_basic_withlog (id, name, deleted, version) values (?,?,?,?); -- bind(1,Test1,false,1)
16:56:14.955 [main] DEBUG io.ebean.SUM - txn[1415] Inserted [EBasicWithLog] [1]
16:56:14.955 [main] DEBUG io.ebean.SUM - txn[1415] BatchControl flush [EBasicLog:0 i:2]
16:56:14.959 [main] TRACE io.ebean.datasource - Closing Connection[sqlserver20170] slot[156] reason[null], pstmtStats: size[49] max[50] hits[48] miss[91] hitRatio[34] removes[42]
16:56:14.959 [main] TRACE io.ebean.datasource - Closing Connection[sqlserver20170] that is already closed?
Dez. 13, 2022 4:56:15 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNUNG: ConnectionID:9 ClientConnectionId: 3ec65559-41ab-4a85-a461-826da3dd7377 Prelogin error: host localhost port 9435 Unexpected end of prelogin response after 0 bytes read
16:56:22.903 [sqlserver2017-ro.heartBeat] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2017-ro] min[2] max[200] free[1] busy[1] waiting[0] highWaterMark[1] waitCount[0] hitCount[576]
16:56:22.903 [sqlserver2017-ro.heartBeat] TRACE io.ebean.datasource - ... closing all 1 connections from the free list with logErrors: false
16:56:22.903 [sqlserver2017-ro.heartBeat] TRACE io.ebean.datasource - Closing Connection[sqlserver2017-ro0] slot[0] reason[null], pstmtStats: size[0] max[50] hits[0] miss[0] hitRatio[0] removes[0]
16:56:22.904 [sqlserver2017-ro.heartBeat] DEBUG io.ebean.datasource - Closing busy connections using leakTimeMinutes 30
16:56:22.909 [sqlserver2017-ro.heartBeat] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver2017-ro1] startTime[1670946982886] busySeconds[0] stackTrace[] stmt[null]

16:56:22.909 [sqlserver2017-ro.heartBeat] ERROR io.ebean.datasource - FATAL: DataSourcePool [sqlserver2017-ro] is down or has network error!!!
16:56:22.912 [sqlserver2017-ro.heartBeat] WARN  io.ebean.datasource - Error when trying to return connection to pool, closing fully.
com.microsoft.sqlserver.jdbc.SQLServerException: Die Verbindung wurde geschlossen.
```
OR
```console
16:56:12.376 [main] DEBUG io.ebean.TXN - txn[1375] Commit
16:56:12.376 [main] TRACE io.ebean.BackgroundExecutor - Queued io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$544/0x000000080120a000@4b9beefe
16:56:12.376 [ebean-sqlserver20192] TRACE io.ebean.BackgroundExecutor - Start io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$544/0x000000080120a000@4b9beefe (delay time 72 us)
16:56:12.376 [ebean-sqlserver20192] TRACE io.ebean.BackgroundExecutor - Stop io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$544/0x000000080120a000@4b9beefe (exec time 79 us)
16:56:12.433 [main] DEBUG io.ebean.SUM - txn[1376] ERROR executing query, bindLog[1, ] error:Cannot continue the execution because the session is in the kill state.
16:56:12.434 [main] DEBUG io.ebean.TXN - txn[1376] Rollback
16:56:12.437 [main] TRACE io.ebean.datasource - Closing Connection[sqlserver20191] slot[110] reason[null], pstmtStats: size[49] max[50] hits[420] miss[3842] hitRatio[9] removes[3793]
16:56:12.437 [main] TRACE io.ebean.datasource - Closing Connection[sqlserver20191] that is already closed?
16:56:12.443 [main] INFO  io.ebean.datasource - Resetting DataSourcePool [sqlserver2019] min[2] max[200] free[1] busy[1] waiting[0] highWaterMark[3] waitCount[0] hitCount[512]
16:56:12.443 [main] TRACE io.ebean.datasource - ... closing all 1 connections from the free list with logErrors: false
16:56:12.443 [main] TRACE io.ebean.datasource - Closing Connection[sqlserver20190] slot[166] reason[null], pstmtStats: size[34] max[50] hits[3] miss[34] hitRatio[8] removes[0]
16:56:12.444 [main] DEBUG io.ebean.datasource - Closing busy connections using leakTimeMinutes 30
16:56:12.446 [main] INFO  io.ebean.datasource - Busy Connections:
 name[sqlserver20192] startTime[1670946972437] busySeconds[0] stackTrace[] stmt[null]

16:56:12.446 [main] ERROR io.ebean.datasource - FATAL: DataSourcePool [sqlserver2019] is down or has network error!!!
16:56:12.448 [main] WARN  io.ebean.datasource - Error when trying to return connection to pool, closing fully.
com.microsoft.sqlserver.jdbc.SQLServerException: Die Verbindung wurde geschlossen.
```

Do you know what the problem can be or how I can analyze it further?

Kind regards
Noemi

**Comment by nPraml** [comment]
what I also noticed: if you start the docker with sqlserv 2017, it has a weird log entry with 2019 but it starts a 2017 db:

```console
docker logs local_sqlserver2017
SQL Server 2019 will run as non-root by default.
This container is running as user root.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2022-12-14 08:11:13.50 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2022-12-14 08:11:13.55 Server      Did not find an existing master data file /var/opt/mssql/data/master.mdf, copying the missing default master and other system database files. If you have moved the database location, but not moved the database files, startup may fail. To repair: shutdown SQL Server, move the master database to configured location, and restart.
2022-12-14 08:11:13.56 Server      Setup step is copying system data file 'C:\templatedata\mastlog.ldf' to '/var/opt/mssql/data/mastlog.ldf'.
2022-12-14 08:11:13.58 Server      Setup step is copying system data file 'C:\templatedata\model.mdf' to '/var/opt/mssql/data/model.mdf'.
2022-12-14 08:11:13.60 Server      Setup step is copying system data file 'C:\templatedata\modellog.ldf' to '/var/opt/mssql/data/modellog.ldf'.
2022-12-14 08:11:13.62 Server      Setup step is copying system data file 'C:\templatedata\msdbdata.mdf' to '/var/opt/mssql/data/msdbdata.mdf'.
2022-12-14 08:11:13.66 Server      Setup step is copying system data file 'C:\templatedata\msdblog.ldf' to '/var/opt/mssql/data/msdblog.ldf'.
2022-12-14 08:11:13.74 Server      Microsoft SQL Server 2017 (RTM-CU28) (KB5008084) - 14.0.3430.2 (X64)
        Dec 17 2021 14:30:27
        Copyright (C) 2017 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 16.04.7 LTS)
```

**Comment by rbygrave** [comment]
> two parallel builds (sqlserver 2017 & 2019)

Yeah, that isn't expected to work without changing the port on one of those.

> SqlServer 2019

I hit some issues with SqlServer 2019 image early one that I can't recall now but for ebean we currently only run the regular regression testing against the SqlServer 2017 image.

**Comment by nPraml** [comment]
Hello @rbygrave,
thank you!
I think I can close this issue, we will fix it with the time shift.
Tests on sqlserverv 2019 are also working.

**Comment by rbygrave** [comment]
Different version of the sqlserver container. Maybe get ebean test to use
latest.
