### ISSUE TITLE
Ebean Redis - Failed to decode cache data for UUID as Id

### ISSUE THREAD

**Issue by parveenyadav-multiply** [ebean-orm/ebean#2931]
## Expected behavior
when using Redis as L2 cache, and using @Cache on entities, we should be able to use UUID as Id
## Actual behavior
Ebean throws an error for UUID : Failed to decode cache data, Expecting String keys but got type:class java.util.UUID
### Steps to reproduce

1. include ebean-redis in pom
2. apply @Cache on entities
3. have UUID as Id field
4. save the entity

```java
  @Entity
@Table(name = "device_otp")
@Cache(enableQueryCache = true, enableBeanCache = true, nearCache = true, naturalKey = "DeviceOTPDomain")
public class DeviceOTPDomain extends BaseDomain {
    @Id
    UUID id;
}
```

```console
  java.lang.RuntimeException: Failed to decode cache data
	at io.ebean.redis.encode.EncodePrefixKey.encode(EncodePrefixKey.java:24) ~[ebean-redis-13.11.1.jar:13.11.1]
	at io.ebean.redis.RedisCache.key(RedisCache.java:94) ~[ebean-redis-13.11.1.jar:13.11.1]
	at io.ebean.redis.RedisCache.remove(RedisCache.java:213) ~[ebean-redis-13.11.1.jar:13.11.1]
	at io.ebean.redis.DuelCache.remove(DuelCache.java:105) ~[ebean-redis-13.11.1.jar:13.11.1]
	at io.ebeaninternal.server.deploy.BeanDescriptorCacheHelp.manyPropRemove(BeanDescriptorCacheHelp.java:235) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.deploy.BeanDescriptor.cacheManyPropRemove(BeanDescriptor.java:1224) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.cache.CacheChangeSet$ManyKey.cacheRemove(CacheChangeSet.java:249) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.cache.CacheChangeSet$ManyChange.apply(CacheChangeSet.java:208) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.cache.CacheChangeSet.apply(CacheChangeSet.java:48) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.transaction.PostCommitProcessing.processCacheChanges(PostCommitProcessing.java:142) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.transaction.PostCommitProcessing.lambda$backgroundNotify$0(PostCommitProcessing.java:121) ~[ebean-core-13.11.0.jar:13.11.0]
	at io.ebeaninternal.server.executor.DefaultBackgroundExecutor.lambda$logExceptions$0(DefaultBackgroundExecutor.java:76) ~[ebean-core-13.11.0.jar:13.11.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.IllegalStateException: Expecting String keys but got type:class java.util.UUID
	at io.ebean.redis.encode.EncodePrefixKey.encode(EncodePrefixKey.java:19) ~[ebean-redis-13.11.1.jar:13.11.1]
	... 16 common frames omitted
```

**Comment by rbygrave** [comment]
What is the version of ebean?  
What is the version of ebean-redis?

**Comment by parveenyadav-multiply** [comment]
EBEAN - 13.11.0

REDIS - 13.11.1

**Comment by rbygrave** [comment]
Next thing to do is to create a reproducing test case in / add a domain object and test here at: https://github.com/ebean-orm/ebean/tree/master/ebean-redis/src/test/java/org/domain

**Comment by parveenyadav-multiply** [comment]
PR created - https://github.com/ebean-orm/ebean/pull/2932

**Comment by parveenyadav-multiply** [comment]
@rbygrave did you get a chance to look into this?

**Comment by rbygrave** [comment]
Just pushed up a PR with the fix now.
