### ISSUE TITLE
Hibernate's enable_lazy_load_no_trans equivalent in JTA mode?

### ISSUE THREAD

**Issue by tbee** [ebean-orm/ebean#3109]
Is it possible to lazy load entities outside of a JTA transaction, similar like Hibernate's enable_lazy_load_no_trans?

We have an old JEE / JSF application which we're trying to clean up. One of the things we're implementing is to make sure all changes run inside a JTA transaction. But the fact that during rendering of the JSF pages entities can still lazy load things, is a problem: the exact data that will be lazy loaded is difficult to determine, given all conditional paths that can be present in JSF pages. Hibernate solves this with the enable_lazy_load_no_trans flag. 

The only hook to implement this ourselves would be via a custom TransactionManager, but it does not know if the transaction is used for lazy loading or something else, making it way too easy to be abused.

**Comment by rob-bygrave** [comment]
> Is it possible to lazy load entities outside of a JTA transaction

Yes.

Given the default transaction isolation level of READ_COMMITTED this will indeed give us the same result from the database perspective as if the lazy loading occurred inside the transaction. This is why Ebean has always supported lazy loading outside of a transaction (be it a JTA transaction or a resource local transaction).

**Comment by rob-bygrave** [comment]
With Ebean we should not do anything like "open session in view"

**Comment by tbee** [comment]
Hey Rob, thanks for responding.

My tests today showed that if EBean is configured with setUseJtaTransactionManager(true), and I load an object inside a JTA transaction, it will not lazy load outside the transaction. It fails on a missing JTA transaction name in the JEE context. 

I know EBean does do have default transactions in normal mode, but that is not the setup we have.

**Comment by rob-bygrave** [comment]
What does the failure look like in terms of stack trace?

**Comment by tbee** [comment]
The test code looks like this:

```
        Client client = TransactionService.get().runInTransation(() -> new ClientRepo().byObjectId(3L));
        client.getAddresses().size();
```

The transaction service starts a JTA transaction, fetches the client and then closes the transaction. Client.getAddresses() returns a deferred collection, but the size() forces it to be populated (outside a transaction) resulting in:

```
  06:48:35,666 ERROR (ServerService Thread Pool -- 157) [com.nedap.aeos.io.app.ApplicationDelegate] Application startup failed: java.lang.IllegalStateException: No transaction associated with the current thread
          at org.wildfly.transaction.client.ContextTransactionSynchronizationRegistry.getResource(ContextTransactionSynchronizationRegistry.java:83) [wildfly-transaction-client-2.0.1.Final.jar:2.0.1.Final]
          at org.jboss.as.txn.service.internal.tsr.TransactionSynchronizationRegistryWrapper.getResource(TransactionSynchronizationRegistryWrapper.java:108)
          at io.ebeaninternal.server.transaction.JtaTransactionManager.getCurrentTransaction(JtaTransactionManager.java:85) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.transaction.ExternalTransactionScopeManager.active(ExternalTransactionScopeManager.java:27) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.transaction.TransactionManager.active(TransactionManager.java:185) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.currentServerTransaction(DefaultServer.java:781) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.buildQueryRequest(DefaultServer.java:1031) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.buildQueryRequest(DefaultServer.java:1026) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1447) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1442) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultBeanLoader.executeQuery(DefaultBeanLoader.java:154) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultBeanLoader.loadMany(DefaultBeanLoader.java:37) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.core.DefaultServer.loadMany(DefaultServer.java:529) [ebean-core-12.16.1.jar:]
          at io.ebeaninternal.server.loadcontext.DLoadManyContext$LoadBuffer.loadMany(DLoadManyContext.java:222) [ebean-core-12.16.1.jar:]
          at io.ebean.common.AbstractBeanCollection.lazyLoadCollection(AbstractBeanCollection.java:101) [ebean-api-12.16.1.jar:]
          at io.ebean.common.BeanSet.init(BeanSet.java:137) [ebean-api-12.16.1.jar:]
          at io.ebean.common.BeanSet.size(BeanSet.java:346) [ebean-api-12.16.1.jar:]
          at com.nedap.aeos.io.app.ApplicationDelegate.initializeEbean(ApplicationDelegate.java:592) [app.jar:]
          at com.nedap.aeos.io.app.ApplicationDelegate.start(ApplicationDelegate.java:223) [app.jar:]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_362]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_362]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_362]
          at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_362]
          at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47) [wildfly-jpa-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) [wildfly-ee-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
          at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:56) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:232) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:373) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:149) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.security.IdentityOutflowInterceptor.processInvocation(IdentityOutflowInterceptor.java:73) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.security.SecurityDomainInterceptor.processInvocation(SecurityDomainInterceptor.java:44) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
          at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:633) [wildfly-elytron-security-manager-1.19.1.Final.jar:1.19.1.Final]
          at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
          at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
          at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:191)
          at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81)
          at com.nedap.aeos.io.app.ApplicationDelegate$$$view49.start(Unknown Source) [app.jar:]
          at com.nedap.healthcare.tasks.ApplicationStartup.startApplicationMAD(ApplicationStartup.java:33) [application-startup.jar:]
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_362]
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_362]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_362]
          at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_362]
          at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:96)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:232) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.notSupported(LifecycleCMTTxInterceptor.java:86) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:64) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) [wildfly-ee-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
          at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
          at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
          at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:141)
          at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
          at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:127) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:141) [wildfly-ejb3-26.1.2.Final.jar:26.1.2.Final]
          at org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_362]
          at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_362]
          at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
          at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
          at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
          at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
          at java.lang.Thread.run(Thread.java:750) [rt.jar:1.8.0_362]
          at org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

This is EBean 12.16.1. After this migration is complete, we will upgrade Java, and then EBean to 13.

**Comment by tbee** [comment]
The lazy load outside a transaction is in essence comparable to the automatic transactions that EBean already supports in normal mode. The scope of such a lazy-load transaction should be specific, not an "open session in view" as you mention, but a fallback specifically for lazy loading. The used transaction should be read only, or even better: only used when EBean decides to lazy load (so no update is ever done), completely bypassing the JTA transactions. Like Hibernate does; the enable_lazy_load_no_trans setting is a hibernate feature, and outside of either the Spring or JEE framework. Only reading data cannot do any harm. 

This behavior can potentially safe a lot of code, but more importantly can prevent many hard to detect issues - given that building a server side web page can have many conditional paths. The coder is always free to prefetch to improve performance, solving a too many SQL statements situation. But because of repository reuse or simply making sure no issue can occur, prefetching has the risk of reading too much data. This balance between prefetching and loading-on-demand is one the coder should make, so it would be nice if EBean would allow that in a JTA setting.

**Comment by rob-bygrave** [comment]
Yes, agreed. I just have not had a chance to look at the stack trace yet (nor have a JTA setup for testing).

**Comment by rbygrave** [comment]
So this looks easy enough to fix. You could try the fix yourself and confirm it works?

At `io.ebeaninternal.server.transaction.JtaTransactionManager.getCurrentTransaction(JtaTransactionManager.java:85) ` 

```java
  @Override
  public Object getCurrentTransaction() {
    TransactionSynchronizationRegistry syncRegistry = getSyncRegistry();
    SpiTransaction t = (SpiTransaction) syncRegistry.getResource(EBEAN_TXN_RESOURCE);
    if (t != null) {
      // we have already seen this transaction
      return t;
    }
  
   // more code ...
```

And we see from the stack trace that the `syncRegistry.getResource(EBEAN_TXN_RESOURCE);` is wildly code and throwing the `java.lang.IllegalStateException: No transaction associated with the current thread`

So the fix would be to add a try catch block around the ` syncRegistry.getResource(EBEAN_TXN_RESOURCE)` and deem that when an Exception is thrown that there is no current transaction. Returning null means there is no current transaction.

```java
  @Override
  public Object getCurrentTransaction() {
    TransactionSynchronizationRegistry syncRegistry = getSyncRegistry();
    try {
      SpiTransaction t = (SpiTransaction) syncRegistry.getResource(EBEAN_TXN_RESOURCE);
      if (t != null) {
        // we have already seen this transaction
        return t;
      }
    } catch (Exception e) {
      // deem that there is no current transaction
      return null;
    }

   // more code ...
```

**Comment by rbygrave** [comment]
> This is EBean 12.16.1.

You'll need to create your own JtaTransactionManager via a copy of the code with the fix (the extra try catch block).

**Comment by tbee** [comment]
That indeed fixes the problem. Thank you! The code was too integrate for me to determine if that was all it took. 

Can we create a PR with this change on the 12 release? We cannot go to 13 yet, because we need to do the Java 11 migration first.

**Comment by rbygrave** [comment]
Just create your own copy of JtaTransactionManager ?   I don't plan to do more 12.x releases per se.

**Comment by tbee** [comment]
I'd tried to extend it and only patch getUserTransaction, but the class is final. 
So then I'll copy and patch it until we're at EBean 13.

**Comment by tbee** [comment]
If a thread is created by anything but WildFly, the getSyncRegistry() call will throw an exception also, it is better to move that inside the try-catch block as well.

```
        TransactionSynchronizationRegistry syncRegistry = null;
        try {
            syncRegistry = getSyncRegistry();
            SpiTransaction t = (SpiTransaction) syncRegistry.getResource(EBEAN_TXN_RESOURCE);
            if (t != null) {
                // we have already seen this transaction
                return t;
            }
        } catch (Exception e) {
            // deem that there is no current transaction
            return null;
        }

```

**Comment by rob-bygrave** [comment]
Ah ok.  Thanks for that, I'll get a PR organised to make that change in master.

Thanks !!!
