### ISSUE TITLE
Support java.sql.Date 

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#3128]
## Expected behavior
According docs it should work:
https://ebean.io/docs/mapping/type/time

## Actual behavior
Crash with exception
### Steps to reproduce

```java
@WhenCreated
public java.util.Date date; // ok
```
```java
@WhenCreated
public java.sql.Date date; // fail
```

```console
Caused by: PersistenceException: Generated Insert Timestamp not supported on Date
	at InsertTimestampFactory.createInsertTimestamp(InsertTimestampFactory.java:51)
	at InsertTimestampFactory.setInsertTimestamp(InsertTimestampFactory.java:39)
	at GeneratedPropertyFactory.setInsertTimestamp(GeneratedPropertyFactory.java:85)
	at AnnotationFields.initWhen(AnnotationFields.java:295)
	at AnnotationFields.readField(AnnotationFields.java:141)
	at AnnotationFields.parse(AnnotationFields.java:62)
	at ReadAnnotations.readInitial(ReadAnnotations.java:29)
```

**Comment by PromanSEW** [comment]
For generated insertion type must be datetime while java.sql.Date is date only. So it it not bug here

**Comment by rbygrave** [comment]
Just to add that use of java.util.Date is not encouraged.  Use Instant or OffsetDateTime or another newer java type etc
