### ISSUE TITLE
"No matches for Entity._idClass the concatenated key columns where not found" when saving entity with composite primary key

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#3133]
## Note

I actually just found the cause right before I wanted to submit, but still think it's worth reporting.

## Expected behavior

save the entity

## Actual behavior

throws the following exception:
```console
No matches for cz.sentica.qwazar.semantic.storage.DbConcept._idClass the concatenated key columns where not found? I expect that the concatenated key was null, and this bean does not have ManyToOne assoc beans matching the primary key columns?
javax.persistence.PersistenceException: No matches for cz.sentica.qwazar.semantic.storage.DbConcept._idClass the concatenated key columns where not found? I expect that the concatenated key was null, and this bean does not have ManyToOne assoc beans matching the primary key columns?
	at app//io.ebeaninternal.server.persist.dmlbind.BindableIdEmbedded.deriveConcatenatedId(BindableIdEmbedded.java:90)
	at app//io.ebeaninternal.server.persist.dml.InsertMeta.deriveConcatenatedId(InsertMeta.java:116)
	at app//io.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:60)
	at app//io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:63)
	at app//io.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:46)
	at app//io.ebeaninternal.server.core.PersistRequestBean.executeInsert(PersistRequestBean.java:1200)
	at app//io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:726)
	at app//io.ebeaninternal.server.persist.BatchControl.executeNow(BatchControl.java:232)
	at app//io.ebeaninternal.server.persist.BatchedBeanHolder.executeNow(BatchedBeanHolder.java:98)
	at app//io.ebeaninternal.server.persist.BatchControl.executeAll(BatchControl.java:321)
	at app//io.ebeaninternal.server.persist.BatchControl.flushInternal(BatchControl.java:298)
	at app//io.ebeaninternal.server.persist.BatchControl.flushBuffer(BatchControl.java:271)
	at app//io.ebeaninternal.server.persist.BatchControl.flushReset(BatchControl.java:257)
	at app//io.ebeaninternal.server.transaction.JdbcTransaction.batchFlushReset(JdbcTransaction.java:551)
	at app//io.ebeaninternal.server.transaction.JdbcTransaction.flushBatchOnCollection(JdbcTransaction.java:532)
	at app//io.ebeaninternal.server.core.DefaultServer.lambda$saveAllInternal$11(DefaultServer.java:1751)
	at app//io.ebeaninternal.server.core.DefaultServer.executeInTrans(DefaultServer.java:2089)
	at app//io.ebeaninternal.server.core.DefaultServer.saveAllInternal(DefaultServer.java:1744)
	at app//io.ebeaninternal.server.core.DefaultServer.saveAll(DefaultServer.java:1734)
	at app//cz.sentica.qwazar.semantic.storage.CompositeForeignKeyTest.createConnectionWithCompositeForeignKey(CompositeForeignKeyTest.kt:65)
```

### Steps to reproduce

```kotlin
// the id class

@Embeddable
data class ConceptId(val id: String = "", val networkId: String = "") : Serializable

// the using class

@Entity
@DbName(SEMANTIC_DB_NAME)
@Table(name = "sem_concept")
@IdClass(ConceptId::class)
class DbConcept(
    @Id
    @Column(name = "conc_id", nullable = false)
    override val id: String = UUID.randomUUID().toString(),

    @Id
    @Column(name = "conc_network_id", nullable = false)
    val networkId: String = UUID.randomUUID().toString(),

    // ...
) {
    @JsonIgnore
    @OneToMany(mappedBy = "from", fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    var outgoingConnections: Set<DbConnection> = emptySet()

    @JsonIgnore
    @OneToMany(mappedBy = "to", fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    var incomingConnections: Set<DbConnection> = emptySet()

    override fun equals(other: Any?) =
        other is DbConcept && other.id == id && other.networkId == networkId

    override fun hashCode() = 31 * id.hashCode() + networkId.hashCode()
}

// the referencing class

@Entity
@DbName(SEMANTIC_DB_NAME)
@Table(name = "sem_connection")
class DbConnection(
    @Id
    @Column(name = "conn_id", nullable = false)
    override val id: String = UUID.randomUUID().toString(),

    // this will be part of index too, but first make this work for DbConcept
    @Index
    @Column(name = "conn_network_id", nullable = false)
    val networkId: String = UUID.randomUUID().toString(),

    // ...
) {
    @JsonIgnore
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns(
        JoinColumn(name = "conn_from", referencedColumnName = "conc_id", nullable = false),
        JoinColumn(name = "conn_network_id", referencedColumnName = "conc_network_id", nullable = false),
    )
    override var from: DbConcept = DbConcept()

    @JsonIgnore
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns(
        JoinColumn(name = "conn_to", referencedColumnName = "conc_id", nullable = false),
        JoinColumn(name = "conn_network_id", referencedColumnName = "conc_network_id", nullable = false),
    )
    override var to: DbConcept = DbConcept()

    override fun equals(other: Any?) =
        other is DbConnection && other.id == id && other.networkId == networkId

    override fun hashCode() = 31 * id.hashCode() + networkId.hashCode()
}

// the test

@SpringBootTest(classes = [JacksonAutoConfiguration::class])
final class CompositeForeignKeyTest(@Autowired objMapper: ObjectMapper) {
    private val dsConfig = DataSourceConfig().apply {
        username = "sa"
        password = "sa"
        url = "jdbc:h2:mem:semanticdb"
        driver = "org.h2.Driver"
    }

    private val databaseConfig = DatabaseConfig().apply {
        name = SEMANTIC_DB_NAME
        objectMapper = objMapper

        isDdlRun = true
        isDdlGenerate = true
        isDefaultServer = false

        dataSourceConfig = dsConfig.apply {
            addProperty("quoteReturningIdentifiers", false)
        }

        addAll(
            listOf(
                ConceptId::class,
                DbConcept::class,
                DbConnection::class,
            ).map { it.java },
        )
    }

    private lateinit var database: Database

    @BeforeEach
    fun setUp() {
        database = DatabaseFactory.create(databaseConfig)
    }

    @AfterEach
    fun tearDown() {
        database.shutdown()
    }

    @Test
    fun createConnectionWithCompositeForeignKey() {
        val networkId = UUID.randomUUID()
        val concept1 = DbConcept(networkId = networkId.toString())
        val concept2 = DbConcept(networkId = networkId.toString())

        database.saveAll(concept1, concept2) // THIS THROWS
    }
}
```

## Some context

* we're using ebean 13.20.1, java 17, kotlin 1.8.20
* it's quite possible I'm doing something wrong here, but I haven't found much documentation for either of `@Embeddable`, `@IdClass`, `@EmbeddedId` (which I'm not using here, because I have no idea how I'd reference it from `DbConnection`)

**Comment by Incanus3** [comment]
So, as I said right at the top, I just found the cause right before submitting. The problem here is that for this to work with ebean, the id class's property names must actually match not the using entity's `@Id` property names, but the actual id column names, which is obviously pretty easy to fix, but
* it's not very obvious
* it's actually different then how javax.persistence defines this, see the second `<p>` here:

```java
package javax.persistence;

/**
 * Specifies a composite primary key class that is mapped to
 * multiple fields or properties of the entity.
 * <p>
 * <p> The names of the fields or properties in the primary key
 * class and the primary key fields or properties of the entity
 * must correspond and their types must be the same.
 * <p>
 * <pre>
 *
 *   Example:
 *
 *   @IdClass(com.acme.EmployeePK.class)
 *   @Entity
 *   public class Employee {
 *      @Id String empName;
 *      @Id Date birthDay;
 *      ...
 *   }
 * </pre>
 *
 * @since Java Persistence 1.0
 */
@Target({TYPE})
@Retention(RUNTIME)
public @interface IdClass {
  Class value();
}
```

also, the error message doesn't really help here.

**Comment by Incanus3** [comment]
I also encountered a few other minor hurdles to make this work:

1) if I don't annotated the id class by `@Embeddable`, I get the following error, even though I explicitly register the class in the `DatabaseConfig` (and looking at https://www.baeldung.com/jpa-composite-primary-keys, it probably shouldn't be needed for `@IdClass`):

```console
io.ebean.config.BeanNotRegisteredException: Could not find BeanDescriptor for class cz.sentica.qwazar.semantic.storage.ConceptId. Perhaps the EmbeddedId class is not registered? See https://ebean.io/docs/trouble-shooting#not-registered
	at io.ebeaninternal.server.deploy.BeanEmbeddedMetaFactory.create(BeanEmbeddedMetaFactory.java:26) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanPropertyAssocOne.<init>(BeanPropertyAssocOne.java:78) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanPropertyIdClass.<init>(BeanPropertyIdClass.java:13) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.meta.DeployBeanPropertyLists.<init>(DeployBeanPropertyLists.java:51) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanDescriptor.<init>(BeanDescriptor.java:284) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.registerDescriptor(BeanDescriptorManager.java:621) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:736) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:296) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:129) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:104) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:29) ~[ebean-core-13.20.1.jar:13.20.1]
	at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:136) ~[ebean-api-13.20.1.jar:13.20.1]
	at io.ebean.DatabaseFactory.create(DatabaseFactory.java:85) ~[ebean-api-13.20.1.jar:13.20.1]
	at cz.sentica.qwazar.semantic.storage.CompositeForeignKeyTest.setUp(CompositeForeignKeyTest.kt:53) ~[test/:na]
```

2) if I do annotate it, but doesn't register it explicitly and use `DatabaseConfig.packages` property instead, it isn't found (which isn't a big problem, but if it's easy to include this annotation in the class scan, it might me nice)
