### ISSUE TITLE
"class java.lang.String cannot be cast to class io.ebean.bean.EntityBean" when deleting entities that use cascade = [CascadeType.ALL] with composite keys

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#3134]
## Expected behavior

delete both "primary" and related entities

## Actual behavior

throws the following exception:

```console
class java.lang.String cannot be cast to class io.ebean.bean.EntityBean (java.lang.String is in module java.base of loader 'bootstrap'; io.ebean.bean.EntityBean is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.String cannot be cast to class io.ebean.bean.EntityBean (java.lang.String is in module java.base of loader 'bootstrap'; io.ebean.bean.EntityBean is in unnamed module of loader 'app')
	at io.ebeaninternal.server.deploy.BeanPropertyAssoc.flatten(BeanPropertyAssoc.java:500)
	at io.ebeaninternal.server.deploy.BeanPropertyAssoc.flattenParentIds(BeanPropertyAssoc.java:485)
	at io.ebeaninternal.server.deploy.BeanPropertyAssoc.bindParentIds(BeanPropertyAssoc.java:512)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocManySqlHelp.deleteByParentIdList(BeanPropertyAssocManySqlHelp.java:166)
	at io.ebeaninternal.server.deploy.BeanPropertyAssocMany.deleteByParentId(BeanPropertyAssocMany.java:303)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteBatch(DefaultPersister.java:724)
	at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:659)
	at io.ebeaninternal.server.persist.DefaultPersister.deleteByIds(DefaultPersister.java:643)
	at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1252)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.delete(DefaultOrmQuery.java:1413)
	at cz.sentica.qwazar.semantic.storage.CompositeForeignKeyTest.createConnectionWithCompositeForeignKey(CompositeForeignKeyTest.kt:79)
```

### Steps to reproduce

```kotlin
// the "primary" class + id class

@Embeddable
@Suppress("PropertyName")
data class ConceptId(val conc_id: String = "", val conc_network_id: String = "") : Serializable

@Entity
@DbName(SEMANTIC_DB_NAME)
@Table(name = "sem_concept")
@IdClass(ConceptId::class)
class DbConcept(
    @Id
    @Column(name = "conc_id", nullable = false)
    override val id: String = UUID.randomUUID().toString(),

    @Id
    @Column(name = "conc_network_id", nullable = false)
    val networkId: String = UUID.randomUUID().toString(),

    // ...
) {
    @JsonIgnore
    @OneToMany(mappedBy = "from", fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    var outgoingConnections: Set<DbConnection> = emptySet()

    @JsonIgnore
    @OneToMany(mappedBy = "to", fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    var incomingConnections: Set<DbConnection> = emptySet()

    override fun equals(other: Any?) =
        other is DbConcept && other.id == id && other.networkId == networkId

    override fun hashCode() = 31 * id.hashCode() + networkId.hashCode()
}

// the "related" class + id class

@Embeddable
@Suppress("PropertyName")
data class ConnectionId(val conn_id: String = "", val conn_network_id: String = "") : Serializable

@Entity
@DbName(SEMANTIC_DB_NAME)
@Table(name = "sem_connection")
@IdClass(ConnectionId::class)
class DbConnection(
    @Id
    @Column(name = "conn_id", nullable = false)
    override val id: String = UUID.randomUUID().toString(),

    @Id
    @Column(name = "conn_network_id", nullable = false)
    val networkId: String = UUID.randomUUID().toString(),

    // ...
) : Connection {
    @JsonIgnore
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns(
        JoinColumn(name = "conn_from", referencedColumnName = "conc_id", nullable = false),
        JoinColumn(
            name = "conn_network_id", referencedColumnName = "conc_network_id",
            nullable = false, insertable = false, updatable = false,
        ),
    )
    override var from: DbConcept = DbConcept()

    @JsonIgnore
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumns(
        JoinColumn(name = "conn_to", referencedColumnName = "conc_id", nullable = false),
        JoinColumn(
            name = "conn_network_id", referencedColumnName = "conc_network_id",
            nullable = false, insertable = false, updatable = false,
        ),
    )
    override var to: DbConcept = DbConcept()

    override fun equals(other: Any?) =
        other is DbConnection && other.id == id && other.networkId == networkId

    override fun hashCode() = 31 * id.hashCode() + networkId.hashCode()
}

// the test

@SpringBootTest(classes = [JacksonAutoConfiguration::class])
final class CompositeForeignKeyTest(@Autowired objMapper: ObjectMapper) {
    private val dsConfig = DataSourceConfig().apply {
        username = "sa"
        password = "sa"
        url = "jdbc:h2:mem:semanticdb"
        driver = "org.h2.Driver"
    }

    private val databaseConfig = DatabaseConfig().apply {
        name = SEMANTIC_DB_NAME
        objectMapper = objMapper

        isDdlRun = true
        isDdlGenerate = true
        isDefaultServer = false

        dataSourceConfig = dsConfig.apply {
            addProperty("quoteReturningIdentifiers", false)
        }

        addAll(
            listOf(
                ConceptId::class,
                ConnectionId::class,

                DbConcept::class,
                DbConnection::class,
            ).map { it.java },
        )
    }

    private lateinit var database: Database

    @BeforeEach
    fun setUp() {
        database = DatabaseFactory.create(databaseConfig)
    }

    @AfterEach
    fun tearDown() {
        database.shutdown()
    }

    @Test
    fun createConnectionWithCompositeForeignKey() {
        val networkId = UUID.randomUUID()
        val concept1 = DbConcept(networkId = networkId.toString())
        val concept2 = DbConcept(networkId = networkId.toString())

        database.saveAll(concept1, concept2)

        val connection = DbConnection(
            networkId = networkId.toString(),
        ).apply {
            from = concept1
            to = concept2
        }

        database.save(connection)

        // IT DOESN'T MATTER WHETHER I DELETE THE CONNECTIONS FIRST OR NOT
        // database.createQuery(DbConnection::class.java).delete()
        database.createQuery(DbConcept::class.java).delete() // THIS THROWS
        QDbConcept(database).delete() // THIS AS WELL
    }
}
```

* the last two lines of the are basically equivalent and they both throw the same exception shown above
* if I comment out the `@OneToMany` properties in `DbConcept` (or just use `cascade = []` and delete the connections first), the test passes, so the problem is really with the cascading delete, not with the "primary" delete

## Some context
* we're using ebean 13.20.1, java 17, kotlin 1.8.20

**Comment by rob-bygrave** [comment]
Ideally we get an example project in GitHub that demonstrates this issue.  Ideally it is using Java so that it can be transferred later into ebean-test (as it appears to be a missing test case which we need to add).  Ideally it uses ebean-test rather than `@SpringBootTest`.

Are you able to produce that?

**Comment by rob-bygrave** [comment]
> example repository for these tests

There is https://github.com/ebean-orm-examples/example-minimal which is a maven project.  

A basic grade project is at: https://github.com/ebean-orm/examples/tree/master/basic-gradle-java if you need to stick with grade for some reason.

**Comment by Incanus3** [comment]
OK, I managed to reproduce the problem in a repo based off your `example-minimal`. [Here](https://github.com/Incanus3/ebean-composite-key-test/blob/main/src/test/java/org/example/domain/CompositeForeignKeyTest.java#L93)'s the failing test. There's a lot of commented-out code there, because the test also reproduces the problems I reported in #3135 (although I haven't really tested all of those in this repo yet).
