### ISSUE TITLE
UTF-16 to UTF-8 character encoding in EBean 12

### ISSUE THREAD

**Issue by tbee** [ebean-orm/ebean#3214]
We have a MySQL table that has a TEXT field in UTF-8 encoding (TEXT is a CLOB type). The application tries to write a string containing an 'ò' (F2 in UTF-16).

```java
    @Lob
    @Column(name = "message", nullable = false, columnDefinition = "text")
    private String surveyPostMessage;
```

## Expected behavior
Under EBean 7 this results in a call through ScalarTypeClob, which uses DataBind.setString, which forwards to PreparedStatement.setString. The text is stored correctly in the database.

## Actual behavior
Under EBean 12 this results in a call through ScalarTypeClob, which uses DataBind.setClob, which forwards to PreparedStatement.setCharacterStream. This results in the following SQLException:

```java
Caused by: java.sql.SQLException: Incorrect string value: '\xF2f een...' for column 'message' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:787)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)
        at io.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:100) [ebean-core-12.16.1.jar:]
        at io.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:106) [ebean-core-12.16.1.jar:]
        at io.ebeaninternal.server.persist.dml.DmlHandler.executeNoBatch(DmlHandler.java:87) [ebean-core-12.16.1.jar:]
        at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:69) [ebean-core-12.16.1.jar:]
```
AFAIK setCharacterStream requires the application to handle encoding conversion (https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_1.html) and it appears this is not happening. Just putting the string into a StringReader (DataBind.setClob) does not make it convert from UTF-16 (F2) to UTF-8 (C3 B2).

How should this be handled? 
Removing the Lob annotation makes the exception go away.

**Comment by tbee** [comment]
I stand corrected:  The JDBC driver will do any necessary conversion from UNICODE to the database char format. So this seems to be a mysql driver issue.
