### ISSUE TITLE
Error when batch flush on sql 

### ISSUE THREAD

**Issue by deverlex** [ebean-orm/ebean#3278]
I set 2 models
```
@Entity
@Table(name = "orders")
public class Order extends AppModel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}

@Entity
@Table(name = "order_items")
public class OrderItem extends AppModel {
    @Id
    private Long id;
    @ManyToOne
    @Column(nullable = false, name = "order_id")
    private Order order;
}
```
I create new Order () and call setOrder() for a new OrderItem()
after that, I call save them in a transaction
```
Transaction transaction = getDataBase().beginTransaction();
try {
   getDataBase().save(order);
   getDataBase().saveAll(orderItem);
   getDataBase().save(....other entities
}
```
It was throw an error 
```
Error when batch flush on sql: insert into order_items (
at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:80)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:245)
	at io.ebeaninternal.server.transaction.TransactionManager.translate(TransactionManager.java:206)
	at io.ebeaninternal.server.transaction.JdbcTransaction.translate(JdbcTransaction.java:671)
	at io.ebeaninternal.server.transaction.JdbcTransaction.batchFlush(JdbcTransaction.java:653)
	at io.ebeaninternal.server.transaction.JdbcTransaction.internalBatchFlush(JdbcTransaction.java:774)
	at io.ebeaninternal.server.transaction.JdbcTransaction.preCommit(JdbcTransaction.java:998)
	at io.ebeaninternal.server.transaction.JdbcTransaction.flushCommitAndNotify(JdbcTransaction.java:985)
	at io.ebeaninternal.server.transaction.JdbcTransaction.commit(JdbcTransaction.java:1046)
	at io.ebeaninternal.api.ScopeTrans.commitTransaction(ScopeTrans.java:129)
	at io.ebeaninternal.api.ScopedTransaction.commit(ScopedTransaction.java:108)
Caused by: java.sql.BatchUpdateException: (conn=250) Column 'order_id' cannot be null
	at org.mariadb.jdbc.export.ExceptionFactory.createBatchUpdate(ExceptionFactory.java:215)
	at org.mariadb.jdbc.client.impl.StandardClient.executePipeline(StandardClient.java:624)
	at org.mariadb.jdbc.ClientPreparedStatement.executeBatchPipeline(ClientPreparedStatement.java:196)
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternalPreparedBatch(ClientPreparedStatement.java:128)
	at org.mariadb.jdbc.ClientPreparedStatement.executeBatch(ClientPreparedStatement.java:466)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at io.ebeaninternal.server.persist.BatchedPstmt.executeAndCheckRowCounts(BatchedPstmt.java:153)
	at io.ebeaninternal.server.persist.BatchedPstmt.executeBatch(BatchedPstmt.java:109)
	at io.ebeaninternal.server.persist.BatchedPstmtHolder.executeAll(BatchedPstmtHolder.java:139)
	at io.ebeaninternal.server.persist.BatchedPstmtHolder.flush(BatchedPstmtHolder.java:115)
	at io.ebeaninternal.server.persist.BatchControl.flushPstmtHolder(BatchControl.java:213)
	at io.ebeaninternal.server.persist.BatchControl.executeNow(BatchControl.java:231)
	at io.ebeaninternal.server.persist.BatchedBeanHolder.executeNow(BatchedBeanHolder.java:98)
	at io.ebeaninternal.server.persist.BatchControl.executeAll(BatchControl.java:319)
	at io.ebeaninternal.server.persist.BatchControl.flushInternal(BatchControl.java:296)
	at io.ebeaninternal.server.persist.BatchControl.flushBuffer(BatchControl.java:269)
	at io.ebeaninternal.server.persist.BatchControl.flushOnCommit(BatchControl.java:236)
	at io.ebeaninternal.server.transaction.JdbcTransaction.batchFlush(JdbcTransaction.java:651)
	... 97 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=250) Column 'order_id' cannot be null
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:290)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:840)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:779)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:698)
	at org.mariadb.jdbc.client.impl.StandardClient.executePipeline(StandardClient.java:575)
	... 114 common frames omitted
```

**Comment by deverlex** [comment]
If I set cascade = CascadeType.MERGE, it will ok. But some case, it will be call duplicated `insert into (id,...` with existed id and will throw a exception constrainst unique for primary key

**Comment by deverlex** [comment]
When I call flush(), it is ok. But I don't want to call flush for every entity, Anyone have a solution?

**Comment by deverlex** [comment]
Same issue: https://github.com/ebean-orm/ebean/issues/3037

It's fixed, upgrade new version if anyone have same issue
