### ISSUE TITLE
Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.

### ISSUE THREAD

**Issue by aohanhongzhi** [ebean-orm/ebean#3314]
## Expected behavior

I run my code normally in IDEA, but it can't run right after package as jar file and run `java -jar app.jar`

```
Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.
```

## Actual behavior

excute `java -jar app.jar` error

### Steps to reproduce

```java
  // some java code

       // https://ebean.io/docs/intro/configuration/#factory
            // datasource
            val dataSourceConfig = DataSourceConfig()
            dataSourceConfig.setUrl(url)
            dataSourceConfig.setUsername(username)
            dataSourceConfig.setPassword(password)
            dataSourceConfig.setPlatform("mysql")

            // configuration ...
            val config = DatabaseConfig();
            config.setDataSourceConfig(dataSourceConfig)

            // create database instance
            val database = DatabaseFactory.create(config)

```

```gradle

val ebean_version: String by extra("13.26.0") // https://github.com/ebean-orm/ebean


    implementation("io.ebean:ebean:$ebean_version")
    // query bean generation
    annotationProcessor("io.ebean:querybean-generator:$ebean_version")
    testImplementation("io.ebean:ebean-test:$ebean_version")
    implementation("io.ebean:ebean-mysql:$ebean_version")

    implementation("mysql:mysql-connector-java:8.0.33")

```

this is my package task for gradle 
```
tasks.jar.configure {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest.attributes["Main-Class"] = mainKotlinClass
    from(configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) })
}
```

then run below shell command
```shell
./gradlew jar -x test
```

finally run 
```shell
java -jar app.jar```

the error happend
```console
  // some logging output
20:34:34.380 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - ebean version: 13.26.0
20:34:34.386 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - Loaded properties from [resource:application.yaml] 
20:34:34.598 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - DataSource [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200] in[190ms]
Exception in thread "main" javax.persistence.PersistenceException: java.lang.IllegalStateException: Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.
        at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:58)
        at io.ebeaninternal.server.core.DefaultContainer.setDatabasePlatform(DefaultContainer.java:219)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:109)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:33)
        at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:135)
        at io.ebean.DatabaseFactory.create(DatabaseFactory.java:84)
        at hxy.dragon.MainKt.main$lambda$7$lambda$6(Main.kt:111)
        at io.javalin.event.EventManager.fireEvent(EventManager.kt:26)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:90)
        at io.javalin.Javalin.start(Javalin.java:123)
        at hxy.dragon.MainKt.main(Main.kt:129)
        at hxy.dragon.MainKt.main(Main.kt)
Caused by: java.lang.IllegalStateException: Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.
        at io.ebeaninternal.server.core.DatabasePlatformFactory.byDatabaseMeta(DatabasePlatformFactory.java:104)
        at io.ebeaninternal.server.core.DatabasePlatformFactory.byDataSource(DatabasePlatformFactory.java:80)
        at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:55)
        ... 11 more

```

**Comment by aohanhongzhi** [comment]
it is my problem , I know the reason !
because I run the incorrect jar file.

below , it is all right.

<img width="685" alt="image" src="https://github.com/ebean-orm/ebean/assets/37319319/95bf8e31-1966-479a-bc7d-f08b6fca3409">

and below it is wrong!

<img width="695" alt="image" src="https://github.com/ebean-orm/ebean/assets/37319319/fe72ee5c-90b5-4b99-9f85-4312cf05813b">

<img width="636" alt="image" src="https://github.com/ebean-orm/ebean/assets/37319319/3d721eb9-27f9-4d1f-9db3-c905d0153802">

**Comment by aohanhongzhi** [comment]
the problem happened again.  I build the project. and run the only jar file. there is no other jar file.

![image](https://github.com/ebean-orm/ebean/assets/37319319/cebd7176-c556-4473-8d9c-590bc463b14f)

when I run it

```shell
~/Project/Java/JavalinDemo-Kotlin$ java -jar app/build/libs/app-1.0-SNAPSHOT.jar
```
 error happened

```
12:44:43.696 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - ebean version: 15.0.1
12:44:43.711 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - Loaded properties from [resource:application.yaml] 
12:44:44.250 kotlin [main] INFO  at io.avaje.applog.slf4j.Slf4jLogger.performLog (Slf4jLogger.java:122) - DataSource [db] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[200] in[501ms]
Exception in thread "main" jakarta.persistence.PersistenceException: java.lang.IllegalStateException: Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.
        at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:58)
        at io.ebeaninternal.server.core.DefaultContainer.setDatabasePlatform(DefaultContainer.java:215)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:105)
        at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:33)
        at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:135)
        at io.ebean.DatabaseFactory.create(DatabaseFactory.java:84)
        at hxy.dragon.MainKt.main$lambda$7$lambda$6(Main.kt:111)
        at io.javalin.event.EventManager.fireEvent(EventManager.kt:26)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:90)
        at io.javalin.Javalin.start(Javalin.java:123)
        at hxy.dragon.MainKt.main(Main.kt:129)
        at hxy.dragon.MainKt.main(Main.kt)
Caused by: java.lang.IllegalStateException: Unable to determine the appropriate ebean platform given database product name [mysql] and ebean platform providers [SqlServer]. With ebean 13+ we now have separate platforms (ebean-postgres, ebean-mysql etc) and should use database specific platform dependency like ebean-postgres. Note that we can use ebean-platform-all to include all the platforms.
        at io.ebeaninternal.server.core.DatabasePlatformFactory.byDatabaseMeta(DatabasePlatformFactory.java:104)
        at io.ebeaninternal.server.core.DatabasePlatformFactory.byDataSource(DatabasePlatformFactory.java:80)
        at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:55)
        ... 11 more
```

my project 

https://github.com/aohanhongzhi/JavalinDemo-Kotlin
