### ISSUE TITLE
connect remote mysql server, heartBeat exception :java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.

### ISSUE THREAD

**Issue by zh-or** [ebean-orm/ebean#3428]
## Expected behavior
no exception

## Actual behavior
Error reported after running for a period of time
```
14:50:34.035 [db.heartBeat] [ERROR] io.ebean.datasource - Error when fully closing connection [name[db2513] startTime[1719297875479] busySeconds[358] stackTrace[] stmt[null]]
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1807)
	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1667)
	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:710)
	at io.ebean.datasource.pool.PooledConnection.closeConnectionFully(PooledConnection.java:211)
	at io.ebean.datasource.pool.FreeConnectionBuffer.trim(FreeConnectionBuffer.java:76)
	at io.ebean.datasource.pool.PooledConnectionQueue.trimInactiveConnections(PooledConnectionQueue.java:359)
	at io.ebean.datasource.pool.PooledConnectionQueue.trim(PooledConnectionQueue.java:340)
	at io.ebean.datasource.pool.ConnectionPool.trimIdleConnections(ConnectionPool.java:356)
	at io.ebean.datasource.pool.ConnectionPool.checkDataSource(ConnectionPool.java:372)
	at io.ebean.datasource.pool.ConnectionPool$HeartBeatRunnable.run(ConnectionPool.java:155)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```

### Steps to reproduce

1. Connect to remote mysql server
2. just wait heartbeat

```xml
<dependencies>
        <dependency>
            <groupId>io.ebean</groupId>
            <artifactId>ebean-mysql</artifactId>
            <version>14.1.0</version>
        </dependency>

        <!-- mysql -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
        </dependency>
</dependencies>
```

```java
  DataSourceConfig dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setUsername("root");
        dataSourceConfig.setPassword("xxx");
        dataSourceConfig.setUrl("jdbc:mysql://remote-server-ip/test");
        dataSourceConfig.setMaxConnections(100);
        dataSourceConfig.setMinConnections(10);
        dataSourceConfig.setHeartbeatSql("select 1");
        dataSourceConfig.setHeartbeatFreqSecs(60 * 3);
        dataSourceConfig.setHeartbeatTimeoutSeconds(10);

        DatabaseConfig config = new DatabaseConfig();
        config.setDataSourceConfig(dataSourceConfig);

        Database db = DatabaseFactory.create(config);
```

```console
  14:50:34.073 [db.heartBeat] [ERROR] io.ebean.datasource - Error when fully closing connection [name[db2512] startTime[1719297875153] busySeconds[358] stackTrace[] stmt[null]]
java.sql.SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1807)
	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1667)
	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:710)
	at io.ebean.datasource.pool.PooledConnection.closeConnectionFully(PooledConnection.java:211)
	at io.ebean.datasource.pool.FreeConnectionBuffer.trim(FreeConnectionBuffer.java:76)
	at io.ebean.datasource.pool.PooledConnectionQueue.trimInactiveConnections(PooledConnectionQueue.java:359)
	at io.ebean.datasource.pool.PooledConnectionQueue.trim(PooledConnectionQueue.java:340)
	at io.ebean.datasource.pool.ConnectionPool.trimIdleConnections(ConnectionPool.java:356)
	at io.ebean.datasource.pool.ConnectionPool.checkDataSource(ConnectionPool.java:372)
	at io.ebean.datasource.pool.ConnectionPool$HeartBeatRunnable.run(ConnectionPool.java:155)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```

**Comment by rob-bygrave** [comment]
I'd start with confirming you can obtain a connection. That is, you have given an error from the connection validation query but haven't stated if you can obtain ANY connection?

The next thing would be explain why you have increased the setHeartbeatFreqSecs to 180 seconds?  And why have you specified setHeartbeatSql("select 1"); rather than use the JDBC drivers validation method?  Did you do those changes for a reason? If you use the defaults do you get the same issue?

Next thing you can do is look at the causes and actions in https://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql

**Comment by zh-or** [comment]
thank you for your reply, yes! i can get connection,
this is init log
```log
13:38:29.782 [main] [INFO ] io.ebean - ebean version: 14.1.0
13:38:33.823 [main] [INFO ] io.ebean.datasource - DataSource [db] autoCommit[false] transIsolation[READ_COMMITTED] min[10] max[100] in[3,915ms]
13:38:34.014 [main] [INFO ] io.ebean.core - Started database[db] platform[MYSQL] in 4,218ms
```

I thought it was a parameter issue, so I tried adjusting these parameters to solve the problem
this is test code, If I remove these codes, I get the same error.
 ``` java
dataSourceConfig.setHeartbeatSql("select 1");
dataSourceConfig.setHeartbeatFreqSecs(60 * 3);
dataSourceConfig.setHeartbeatTimeoutSeconds(10);
```

**Comment by zh-or** [comment]
是否是因为autocommit的问题, 也许我可以加上这个配置试一下
`dataSourceConfig.setAutoCommit(true);`

**Comment by zh-or** [comment]
after deleting these configurations, it ran for two days without any abnormalities， but I think if there are network fluctuations, this error will reappear
```
dataSourceConfig.setHeartbeatSql("select 1");
dataSourceConfig.setHeartbeatFreqSecs(60 * 3);
dataSourceConfig.setHeartbeatTimeoutSeconds(10);
```
