### ISSUE TITLE
[ebean-migration] Connection is closed error running migration with MySql and Hikari

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean#3434]
## Actual behavior
db migration cause Connection is closed when ebean upgrade to 15.4.0 from 15.3.1.
After I returned to the old version, the program run normally.There is another situation, if the database is postgresql, there is no error
### Steps to reproduce
db:mysql
ebean: 15.3.1->15.4.0
```java
  // some java code
```

```console
Caused by: io.ebean.migration.MigrationException: Error running DB migrations
	at io.ebean.migration.runner.MigrationEngine.setAutoCommitFalse(MigrationEngine.java:103)
	at io.ebean.migration.runner.MigrationEngine.run(MigrationEngine.java:72)
	at io.ebean.migration.runner.MigrationEngine.run(MigrationEngine.java:44)
	at io.ebean.migration.MigrationRunner.run(MigrationRunner.java:100)
	at io.ebean.migration.MigrationRunner.run(MigrationRunner.java:72)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:503)
	at jdk.proxy3/jdk.proxy3.$Proxy64.setAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:402)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at io.ebean.migration.runner.MigrationEngine.setAutoCommitFalse(MigrationEngine.java:101)
```

**Comment by rbygrave** [comment]
> ebean upgrade to 15.4.0

The change here was that **_fastMode_** was enabled by default. 

When MigrationRunner executes with:
- Hikari Connection Pool
- AutoCommit = true
- MySQL
- No actual migrations have run yet (this is expected)

The fastMode can fail (as expected) but the bug is that is performs `connection.rollback()` regardless of the AutoCommit mode [and it only should when autoCommit=false]. Hikari connection pool then reads the MySQL SQLException and infers that the connection is broken and should be evicted (imo this is a Hikari bug, using the ebean-datasource this issue doesn't reproduce).

The fix to ebean-migration is for the fastMode check to only rollback when autoCommit=false.

**Comment by rbygrave** [comment]
Note the fix for this is in `io.ebean : ebean-migration : 14.2.0`
