### ISSUE TITLE
@ManyToOne(optional = false, cascade = ALL) does not work

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#3483]
## Expected behavior
`someModel.delete()` cascade deletes rows in other tables with FK constraints
## Actual behavior
`DataIntegrityException` with error that are references in other tables
### Steps to reproduce
```java
@Entity
@Table(name = "history")
public class HistoryEntry extends Model {
	...
	@ManyToOne(optional = false, cascade = CascadeType.ALL)
	public User user;
}
...
User user = DB.find(User.class).setId(1).findOne();
user.delete(); // ERROR: references in history table
```
How to cascade remove parent bean without manually deleting referenced rows in others?

**Comment by rbygrave** [comment]
Can you include the actual sql that is run and the actual error.

**Comment by PromanSEW** [comment]
`[DataIntegrityException: Error: ERROR: UPDATE or DELETE on table "users" violates foreign key constraint "fk_history_user_id" on table "history" Details: Key (id)=(248651) is still referenced in table "history".]`
SQL is not included in error, stacktrace also. Error is possibly generated by PostgreSQL driver.

**Comment by PromanSEW** [comment]
Got stacktrace:
```
at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:79)
        at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:212)
        at io.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:77)
        at io.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:38)
        at io.ebeaninternal.server.core.PersistRequestBean.executeDelete(PersistRequestBean.java:1092)
        at io.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:634)
        at io.ebeaninternal.server.core.PersistRequestBean.executeNoBatch(PersistRequestBean.java:668)
        at io.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:659)
        at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:719)
        at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:359)
        at io.ebeaninternal.server.persist.DefaultPersister.deleteRequest(DefaultPersister.java:341)
        at io.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:334)
        at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1695)
        at io.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1686)
        at io.ebean.Model.delete(Model.java:263)
        at models.main.User.deleteData(User.java:272)
...
```

**Comment by jnehlmeier** [comment]
You have to map OneToMany User -> HistoryEntry with cascade if you delete a user, right?

**Comment by PromanSEW** [comment]
@jnehlmeier yes... But I don't want to include` List<HistoryEntry>` to `User`, many entities have `@ManyToOne User user`, and I assumed that If I delete User, then all entities in other tables with `@ManyToOne User user` also will be deleted.

**Comment by jnehlmeier** [comment]
@PromanSEW That is not how cascase works. 

JavaDoc is pretty clear here: 

`The operations that must be cascaded to the target of the association.`. 

Your `User` entity does not have an association to `HistoryEntry` so the `REMOVE` operation you have issued on `User` instance is not cascaded. Because it is not cascaded you see the foreign key exception.

You have to choose one of the following:
- map all these associations in the `User` class so it can see all its children and can cascade the delete operation to them
- Write `DELETE .. WHERE parent_id = x`-Queries yourself and call them before removing the parent. One query per entity you do not want to map in `User`.
- Use a database foreign key with `on delete cascade`. Then you only need to delete the parent and the DB does the rest. However you then have to tell Ebean (any ORM) that additional tables in the DB have changed because Ebean (any ORM) cannot see the changes done by the DB automatically. In JPA you usually use `EntityManager.refresh/clear` but Ebean also has a method for it (I cannot remember the name right now). If you don't do that the ORM might return deleted data because it has been cached.

**Comment by PromanSEW** [comment]
@jnehlmeier thanks for comments a lot
@rbygrave how to add migration for cascade remove correctly, and do not break anything?
Ebean DDL created this line for table:
```sql
alter table history add constraint fk_history_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;
```

**Comment by PromanSEW** [comment]
Thanks @jnehlmeier, @rbygrave
I updated my constraint by migration:
```sql
alter table ban_history
    drop constraint fk_history_user_id,
    add constraint fk_history_user_id foreign key (user_id) references users (id) on delete cascade on update restrict;
```
