### ISSUE TITLE
NullPointerException: Cannot invoke "io.ebeaninternal.server.query.STreeProperty.name()"

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#3489]
## Expected behavior
`findList()` returns list of beans
## Actual behavior
Strange crash without explanation as usual in other situations (see below)
### Steps to reproduce
```java
@Entity
public class User extends Model {
	@Id
	public int id;
	...
}

@Entity
public class Tour extends Model {
	@Id
	public int id;
	...
}

@Entity
public class TourStats extends Model implements Comparable<TourStats> {
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	public User user;
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	public Tour tour;
	public int place;
	public int result;

	public static List<TourStats> byTour(int id) {
		return DB.find(TourStats.class).select("user_id, place, result").where().eq("tour_id", id).findList();
	}
}

...

var list = TourStats.byTour(1000); // CRASH
```

```console
Caused by: java.lang.NullPointerException: Cannot invoke "io.ebeaninternal.server.query.STreeProperty.name()" because "prop" is null
	at io.ebeaninternal.server.query.SqlTreeProperties.add(SqlTreeProperties.java:44)
	at io.ebeaninternal.server.query.SqlTreeBuilder.addProperty(SqlTreeBuilder.java:442)
	at io.ebeaninternal.server.query.SqlTreeBuilder.getBaseSelectPartial(SqlTreeBuilder.java:480)
	at io.ebeaninternal.server.query.SqlTreeBuilder.getBaseSelect(SqlTreeBuilder.java:501)
	at io.ebeaninternal.server.query.SqlTreeBuilder.buildSelectChain(SqlTreeBuilder.java:249)
	at io.ebeaninternal.server.query.SqlTreeBuilder.buildRoot(SqlTreeBuilder.java:211)
	at io.ebeaninternal.server.query.SqlTreeBuilder.build(SqlTreeBuilder.java:113)
	at io.ebeaninternal.server.query.CQueryBuilder.createSqlTree(CQueryBuilder.java:364)
	at io.ebeaninternal.server.query.CQueryBuilder.createSqlTree(CQueryBuilder.java:353)
	at io.ebeaninternal.server.query.CQueryBuilder.buildQuery(CQueryBuilder.java:323)
	at io.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:330)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:126)
	at io.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:379)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1329)
	at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1311)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1464)
	at io.ebeaninternal.server.expression.DefaultExpressionList.findList(DefaultExpressionList.java:273)
```
Ebean: 15.1.0, PostgreSQL 16.4
What am I doing wrong?

**Comment by rbygrave** [comment]
How about:

in the select use:  *user* instead of *user_id*
in the where use:  *tour.id <http://tour.id>* instead of *tour_id*

... these are the bean "property paths" and user_id and tour_id are not
"property paths" but instead look like db column names (but without alias
etc).



So:

return DB.find(TourStats.class).select("*user*, place,
result").where().eq("*tour.id <http://tour.id>*", id).findList();

**Comment by PromanSEW** [comment]
@rbygrave  `select("user, place, result")` fixed error, generated SQL looks correct. But I think it would be nice if it was informative exception instead of NPE, or Ebean should process these cases correctly itself
