### ISSUE TITLE
Exposing discriminator value in entity bean throws exception when updating or deleting

### ISSUE THREAD

**Issue by BonesGit** [ebean-orm/ebean#80]
Currently using version 3.2.5 of EBean ORM.

When using single table inheritance and sub-classes with discriminator values you get an error when updating or deleting an entity bean when attempting to expose the dtype column into the bean.  Selecting and inserting works correctly.

```
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[No value specified for parameter 12.]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:452) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:365) ~[avaje-ebeanorm-3.2.5.jar:na]
Caused by: org.postgresql.util.PSQLException: No value specified for parameter 12.
        at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:178) ~[postgresql-9.1-901-1.jdbc4.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:246) ~[postgresql-9.1-901-1.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512) ~[postgresql-9.1-901-1.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql-9.1-901-1.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334) ~[postgresql-9.1-901-1.jdbc4.jar:na]
        at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205) ~[bonecp.jar:na]
```

Test case:

```
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
public class Resource {

    @Id
    public UUID id;

    @Column(insertable=false, updatable=false)
    public String dtype;

    public String name;
}


@Entity
@DiscriminatorValue( "photo" )
public class Photo extends Resource {
}

@Entity
@DiscriminatorValue( "video" )
public class Video extends Resource {
}
```

Selecting a list of Resource, Photo, or Video all return the correct discriminator value in the dtype field.  Inserting new Photo or Video works correctly.  But attempting to update or delete a Photo or Video generates the exception above.

```
// insert
Photo p = new Photo();
p.name = "the name";
Ebean.save(p);  // works correctly

// update
p.name = "new name";
Ebean.save(p); // throws exception

// delete
Ebean.delete(p); // throws exception
```

**Comment by jenshuehn** [comment]
Hi. 
I stumbled upon this recommendation here. 
However, I think it is only fixed when the discriminator column is not using a camel case formatted name. Really strange. With camel case the evolution insert script contains the same column twice.

This works:
```
@DiscriminatorColumn(name = "billingprovider")
...
@Column(name="billingprovider", insertable = false, updatable = false)
String billingProvider;
```

This does not work:
```
@DiscriminatorColumn(name = "billingProvider")
...
@Column(name="billingProvider", insertable = false, updatable = false)
String billingProvider;

```

Camel case isn't forbidden, is it?

All the best.
Jens

**Comment by rbygrave** [comment]
> Camel case isn't forbidden, is it?

No but ... generally database dictionaries are not case sensitive (unless using quoted identifiers).  So using "billingProvider" can be problematic as it will most often be returned as "BILLINGPROVIDER" in any ResultSet meta data etc.

That all said ... `@DiscriminatorColumn(name = "billingprovider")` and `@DiscriminatorColumn(name = "billingProvider")` ... should both be treated the same so that really sounds like a bug in Ebean (both should effectively be treated as "billingprovider").
