### ISSUE TITLE
ENH: Add ability to globally use quoted identifiers on all tables and columns

### ISSUE THREAD

**Issue by icode** [ebean-orm/ebean#867]
## Expected behavior

quoted in table/column names

but, we use oracle is ok. because oracle `key` is not reserved keywords.

so need different databases require different whitelists, hibernate has quoted reserved keywords  whitelists

### Steps to reproduce

```java
  public class ModelA {
     String key;
  }

Ebean.save(modelA);
```

```console
 16:45:54.110 [Grizzly-worker(8)] DEBUG org.avaje.ebean.SQL - txn[1261] insert into wf_processlist (value, status, sort, name, key, valueads, type) values (?,?,?,?,?,?,?); --bind(test,1,6,ProcessType,1,null,null,)
16:45:54.113 [Grizzly-worker(8)] DEBUG org.avaje.ebean.SUM - txn[1261] ERROR executing DML bindLog[test,1,6,ProcessType,1,null,null,] error[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, valueads, type) values ('test',1,6,'ProcessType',1,null,null)' at line 1]
16:45:54.114 [Grizzly-worker(8)] TRACE org.avaje.ebean.TXN - txn[1261] Commit - query only
16:45:54.114 [Grizzly-worker(8)] ERROR ameba.db.PersistenceExceptionMapper - Executing SQL error
javax.persistence.PersistenceException: ERROR executing DML bindLog[test,1,6,ProcessType,1,null,null,] error[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, valueads, type) values ('test',1,6,'ProcessType',1,null,null)' at line 1]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:85)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:50)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:54)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:644)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:690)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:449)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:399)
	at com.avaje.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1508)
	at com.avaje.ebeaninternal.server.core.DefaultServer.insert(DefaultServer.java:1501)
	at ameba.db.ebean.EbeanPersister.insert(EbeanPersister.java:113)
	at com.sinitek.fiaame.resources.workflow.service.impl.WorkflowBaseServiceImpl.saveProcessList(WorkflowBaseServiceImpl.java:177)
	at com.sinitek.fiaame.resources.workflow.ProcessParemResource.saveProcessList(ProcessParemResource.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at ameba.container.grizzly.server.http.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:164)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, valueads, type) values ('test',1,6,'ProcessType',1,null,null)' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:253)
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:82)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:122)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:75)
	... 37 common frames omitted
```

https://github.com/ebean-orm/ebean/issues/539

hibernate config document :  http://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/cfg/Environment.html#GLOBALLY_QUOTED_IDENTIFIERS

**Comment by icode** [comment]
@rbygrave look this issue?

**Comment by 0xbaadf00d** [comment]
Using quoted fields is a very good practice and is compliant with all major existing DBMS. Implementation of `GLOBALLY_QUOTED_IDENTIFIERS` is a nice idea.  Is the char `&#96;` (back quote) will be used ?

**Comment by rPraml** [comment]
MS-SQL needs [...] to quote reserved fields.

**Comment by 0xbaadf00d** [comment]
Is something that the java driver provide ?

MS-SQL can use double quote too if the command `SET QUOTED_IDENTIFIER ON` is used : https://msdn.microsoft.com/en-us/library/ms174393.aspx

**Comment by rPraml** [comment]
Is there something in progress? 
I often run in that issue, that one DBMS supports reserved words and an other one does not.
I would suggest, to quote everything, I also tried to modify the ebean code, but this is a bit too much for me, there are so many places where the columnName is used and no databasePlatform is available to get the quote-characters.

Now I try to avoid SQL-keywords, for that I've written a small validation routine. I paste this routine here, maybe someone find it useful (It seems that the SqlReservedKeywords class in ebean is not used anywhere!?)

```java
/**
 * This is a list of all reserved SQL words
 * <p>
 * Source: https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words
 * Created by praml on 25.11.2016.
 */
public enum ReservedWords {
	A, ABORT, ABS, ABSOLUTE, ACCESS, ACTION, ADA, ADD, ADMIN, AFTER, AGGREGATE,
	ALIAS, ALL, ALLOCATE, ALSO, ALTER, ALWAYS, ANALYSE, ANALYZE, AND, ANY,
	ARE, ARRAY, AS, ASC, ASENSITIVE, ASSERTION, ASSIGNMENT, ASYMMETRIC, AT,
	ATOMIC, ATTRIBUTE, ATTRIBUTES, AUDIT, AUTHORIZATION, AUTO_INCREMENT, AVG,
	AVG_ROW_LENGTH,

	BACKUP, BACKWARD, BEFORE, BEGIN, BERNOULLI, BETWEEN, BIGINT, BINARY, BIT,
	BIT_LENGTH, BITVAR, BLOB, BOOL, BOOLEAN, BOTH, BREADTH, BREAK, BROWSE,
	BULK, BY,

	C, CACHE, CALL, CALLED, CARDINALITY, CASCADE, CASCADED, CASE, CAST,
	CATALOG, CATALOG_NAME, CEIL, CEILING, CHAIN, CHANGE, CHAR, CHAR_LENGTH,
	CHARACTER, CHARACTER_LENGTH, CHARACTER_SET_CATALOG, CHARACTER_SET_NAME,
	CHARACTER_SET_SCHEMA, CHARACTERISTICS, CHARACTERS, CHECK, CHECKED,
	CHECKPOINT, CHECKSUM, CLASS, CLASS_ORIGIN, CLOB, CLOSE, CLUSTER, CLUSTERED,
	COALESCE, COBOL, COLLATE, COLLATION, COLLATION_CATALOG, COLLATION_NAME,
	COLLATION_SCHEMA, COLLECT, COLUMN, COLUMN_NAME, COLUMNS, COMMAND_FUNCTION,
	COMMAND_FUNCTION_CODE, COMMENT, COMMIT, COMMITTED, COMPLETION, COMPRESS,
	COMPUTE, CONDITION, CONDITION_NUMBER, CONNECT, CONNECTION, CONNECTION_NAME,
	CONSTRAINT, CONSTRAINT_CATALOG, CONSTRAINT_NAME, CONSTRAINT_SCHEMA,
	CONSTRAINTS, CONSTRUCTOR, CONTAINS, CONTAINSTABLE, CONTINUE, CONVERSION,
	CONVERT, COPY, CORR, CORRESPONDING, COUNT, COVAR_POP, COVAR_SAMP, CREATE,
	CREATEDB, CREATEROLE, CREATEUSER, CROSS, CSV, CUBE, CUME_DIST, CURRENT,
	CURRENT_DATE, CURRENT_DEFAULT_TRANSFORM_GROUP, CURRENT_PATH, CURRENT_ROLE,
	CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_TRANSFORM_GROUP_FOR_TYPE,
	CURRENT_USER, CURSOR, CURSOR_NAME, CYCLE,

	DATA, DATABASE, DATABASES, DATE, DATETIME, DATETIME_INTERVAL_CODE,
	DATETIME_INTERVAL_PRECISION, DAY, DAY_HOUR, DAY_MICROSECOND, DAY_MINUTE,
	DAY_SECOND, DAYOFMONTH, DAYOFWEEK, DAYOFYEAR, DBCC, DEALLOCATE, DEC,
	DECIMAL, DECLARE, DEFAULT, DEFAULTS, DEFERRABLE, DEFERRED, DEFINED,
	DEFINER, DEGREE, DELAY_KEY_WRITE, DELAYED, DELETE, DELIMITER, DELIMITERS,
	DENSE_RANK, DENY, DEPTH, DEREF, DERIVED, DESC, DESCRIBE, DESCRIPTOR,
	DESTROY, DESTRUCTOR, DETERMINISTIC, DIAGNOSTICS, DICTIONARY, DISABLE,
	DISCONNECT, DISK, DISPATCH, DISTINCT, DISTINCTROW, DISTRIBUTED, DIV, DO,
	DOMAIN, DOUBLE, DROP, DUAL, DUMMY, DUMP, DYNAMIC, DYNAMIC_FUNCTION,
	DYNAMIC_FUNCTION_CODE,

	EACH, ELEMENT, ELSE, ELSEIF, ENABLE, ENCLOSED, ENCODING, ENCRYPTED, END,  //END-EXEC - no valid enum name	,
	ENUM, EQUALS, ERRLVL, ESCAPE, ESCAPED, EVERY, EXCEPT, EXCEPTION, EXCLUDE,
	EXCLUDING, EXCLUSIVE, EXEC, EXECUTE, EXISTING, EXISTS, EXIT, EXP, EXPLAIN,
	EXTERNAL, EXTRACT,

	FALSE, FETCH, FIELDS, FILE, FILLFACTOR, FILTER, FINAL, FIRST, FLOAT,
	FLOAT4, FLOAT8, FLOOR, FLUSH, FOLLOWING, FOR, FORCE, FOREIGN, FORTRAN,
	FORWARD, FOUND, FREE, FREETEXT, FREETEXTTABLE, FREEZE, FROM, FULL,
	FULLTEXT, FUNCTION, FUSION,

	G, GENERAL, GENERATED, GET, GLOBAL, GO, GOTO, GRANT, GRANTED, GRANTS,
	GREATEST, GROUP, GROUPING,

	HANDLER, HAVING, HEADER, HEAP, HIERARCHY, HIGH_PRIORITY, HOLD, HOLDLOCK,
	HOST, HOSTS, HOUR, HOUR_MICROSECOND, HOUR_MINUTE, HOUR_SECOND,

	IDENTIFIED, IDENTITY, IDENTITY_INSERT, IDENTITYCOL, IF, IGNORE, ILIKE,
	IMMEDIATE, IMMUTABLE, IMPLEMENTATION, IMPLICIT, IN, INCLUDE, INCLUDING,
	INCREMENT, INDEX, INDICATOR, INFILE, INFIX, INHERIT, INHERITS, INITIAL,
	INITIALIZE, INITIALLY, INNER, INOUT, INPUT, INSENSITIVE, INSERT, INSERT_ID,
	INSTANCE, INSTANTIABLE, INSTEAD, INT, INT1, INT2, INT3, INT4, INT8,
	INTEGER, INTERSECT, INTERSECTION, INTERVAL, INTO, INVOKER, IS, ISAM,
	ISNULL, ISOLATION, ITERATE,

	JOIN,

	K, KEY, KEY_MEMBER, KEY_TYPE, KEYS, KILL,

	LANCOMPILER, LANGUAGE, LARGE, LAST, LAST_INSERT_ID, LATERAL, LEADING,
	LEAST, LEAVE, LEFT, LENGTH, LESS, LEVEL, LIKE, LIMIT, LINENO, LINES,
	LISTEN, LN, LOAD, LOCAL, LOCALTIME, LOCALTIMESTAMP, LOCATION, LOCATOR,
	LOCK, LOGIN, LOGS, LONG, LONGBLOB, LONGTEXT, LOOP, LOW_PRIORITY, LOWER,

	M, MAP, MATCH, MATCHED, MAX, MAX_ROWS, MAXEXTENTS, MAXVALUE, MEDIUMBLOB,
	MEDIUMINT, MEDIUMTEXT, MEMBER, MERGE, MESSAGE_LENGTH, MESSAGE_OCTET_LENGTH,
	MESSAGE_TEXT, METHOD, MIDDLEINT, MIN, MIN_ROWS, MINUS, MINUTE,
	MINUTE_MICROSECOND, MINUTE_SECOND, MINVALUE, MLSLABEL, MOD, MODE, MODIFIES,
	MODIFY, MODULE, MONTH, MONTHNAME, MORE, MOVE, MULTISET, MUMPS, MYISAM,

	NAME, NAMES, NATIONAL, NATURAL, NCHAR, NCLOB, NESTING, NEW, NEXT, NO,
	NO_WRITE_TO_BINLOG, NOAUDIT, NOCHECK, NOCOMPRESS, NOCREATEDB, NOCREATEROLE,
	NOCREATEUSER, NOINHERIT, NOLOGIN, NONCLUSTERED, NONE, NORMALIZE,
	NORMALIZED, NOSUPERUSER, NOT, NOTHING, NOTIFY, NOTNULL, NOWAIT, NULL,
	NULLABLE, NULLIF, NULLS, NUMBER, NUMERIC,

	OBJECT, OCTET_LENGTH, OCTETS, OF, OFF, OFFLINE, OFFSET, OFFSETS, OIDS, OLD,
	ON, ONLINE, ONLY, OPEN, OPENDATASOURCE, OPENQUERY, OPENROWSET, OPENXML,
	OPERATION, OPERATOR, OPTIMIZE, OPTION, OPTIONALLY, OPTIONS, OR, ORDER,
	ORDERING, ORDINALITY, OTHERS, OUT, OUTER, OUTFILE, OUTPUT, OVER, OVERLAPS,
	OVERLAY, OVERRIDING, OWNER,

	PACK_KEYS, PAD, PARAMETER, PARAMETER_MODE, PARAMETER_NAME,
	PARAMETER_ORDINAL_POSITION, PARAMETER_SPECIFIC_CATALOG,
	PARAMETER_SPECIFIC_NAME, PARAMETER_SPECIFIC_SCHEMA, PARAMETERS, PARTIAL,
	PARTITION, PASCAL, PASSWORD, PATH, PCTFREE, PERCENT, PERCENT_RANK,
	PERCENTILE_CONT, PERCENTILE_DISC, PLACING, PLAN, PLI, POSITION, POSTFIX,
	POWER, PRECEDING, PRECISION, PREFIX, PREORDER, PREPARE, PREPARED, PRESERVE,
	PRIMARY, PRINT, PRIOR, PRIVILEGES, PROC, PROCEDURAL, PROCEDURE, PROCESS,
	PROCESSLIST, PUBLIC, PURGE,

	QUOTE,

	RAID0, RAISERROR, RANGE, RANK, RAW, READ, READS, READTEXT, REAL, RECHECK,
	RECONFIGURE, RECURSIVE, REF, REFERENCES, REFERENCING, REGEXP, REGR_AVGX,
	REGR_AVGY, REGR_COUNT, REGR_INTERCEPT, REGR_R2, REGR_SLOPE, REGR_SXX,
	REGR_SXY, REGR_SYY, REINDEX, RELATIVE, RELEASE, RELOAD, RENAME, REPEAT,
	REPEATABLE, REPLACE, REPLICATION, REQUIRE, RESET, RESIGNAL, RESOURCE,
	RESTART, RESTORE, RESTRICT, RESULT, RETURN, RETURNED_CARDINALITY,
	RETURNED_LENGTH, RETURNED_OCTET_LENGTH, RETURNED_SQLSTATE, RETURNS, REVOKE,
	RIGHT, RLIKE, ROLE, ROLLBACK, ROLLUP, ROUTINE, ROUTINE_CATALOG,
	ROUTINE_NAME, ROUTINE_SCHEMA, ROW, ROW_COUNT, ROW_NUMBER, ROWCOUNT,
	ROWGUIDCOL, ROWID, ROWNUM, ROWS, RULE,

	SAVE, SAVEPOINT, SCALE, SCHEMA, SCHEMA_NAME, SCHEMAS, SCOPE, SCOPE_CATALOG,
	SCOPE_NAME, SCOPE_SCHEMA, SCROLL, SEARCH, SECOND, SECOND_MICROSECOND,
	SECTION, SECURITY, SELECT, SELF, SENSITIVE, SEPARATOR, SEQUENCE,
	SERIALIZABLE, SERVER_NAME, SESSION, SESSION_USER, SET, SETOF, SETS,
	SETUSER, SHARE, SHOW, SHUTDOWN, SIGNAL, SIMILAR, SIMPLE, SIZE, SMALLINT,
	SOME, SONAME, SOURCE, SPACE, SPATIAL, SPECIFIC, SPECIFIC_NAME, SPECIFICTYPE,
	SQL, SQL_BIG_RESULT, SQL_BIG_SELECTS, SQL_BIG_TABLES, SQL_CALC_FOUND_ROWS,
	SQL_LOG_OFF, SQL_LOG_UPDATE, SQL_LOW_PRIORITY_UPDATES, SQL_SELECT_LIMIT,
	SQL_SMALL_RESULT, SQL_WARNINGS, SQLCA, SQLCODE, SQLERROR, SQLEXCEPTION,
	SQLSTATE, SQLWARNING, SQRT, SSL, STABLE, START, STARTING, STATE, STATEMENT,
	STATIC, STATISTICS, STATUS, STDDEV_POP, STDDEV_SAMP, STDIN, STDOUT, STORAGE,
	STRAIGHT_JOIN, STRICT, STRING, STRUCTURE, STYLE, SUBCLASS_ORIGIN, SUBLIST,
	SUBMULTISET, SUBSTRING, SUCCESSFUL, SUM, SUPERUSER, SYMMETRIC, SYNONYM,
	SYSDATE, SYSID, SYSTEM, SYSTEM_USER,

	TABLE, TABLE_NAME, TABLES, TABLESAMPLE, TABLESPACE, TEMP, TEMPLATE,
	TEMPORARY, TERMINATE, TERMINATED, TEXT, TEXTSIZE, THAN, THEN, TIES, TIME,
	TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE, TINYBLOB, TINYINT, TINYTEXT, TO,
	TOAST, TOP, TOP_LEVEL_COUNT, TRAILING, TRAN, TRANSACTION,
	TRANSACTION_ACTIVE, TRANSACTIONS_COMMITTED, TRANSACTIONS_ROLLED_BACK,
	TRANSFORM, TRANSFORMS, TRANSLATE, TRANSLATION, TREAT, TRIGGER,
	TRIGGER_CATALOG, TRIGGER_NAME, TRIGGER_SCHEMA, TRIM, TRUE, TRUNCATE,
	TRUSTED, TSEQUAL, TYPE,

	UESCAPE, UID, UNBOUNDED, UNCOMMITTED, UNDER, UNDO, UNENCRYPTED, UNION,
	UNIQUE, UNKNOWN, UNLISTEN, UNLOCK, UNNAMED, UNNEST, UNSIGNED, UNTIL,
	UPDATE, UPDATETEXT, UPPER, USAGE, USE, USER, USER_DEFINED_TYPE_CATALOG,
	USER_DEFINED_TYPE_CODE, USER_DEFINED_TYPE_NAME, USER_DEFINED_TYPE_SCHEMA,
	USING, UTC_DATE, UTC_TIME, UTC_TIMESTAMP,

	VACUUM, VALID, VALIDATE, VALIDATOR, VALUE, VALUES, VAR_POP, VAR_SAMP,
	VARBINARY, VARCHAR, VARCHAR2, VARCHARACTER, VARIABLE, VARIABLES, VARYING,
	VERBOSE, VIEW, VOLATILE,

	WAITFOR, WHEN, WHENEVER, WHERE, WHILE, WIDTH_BUCKET, WINDOW, WITH, WITHIN,
	WITHOUT, WORK, WRITE, WRITETEXT,

	X509, XOR,

	YEAR, YEAR_MONTH,

	ZEROFILL, ZONE;

	/**
	 * Returns TRUE if the value is a reserved SQL Keyword
	 * @param value
	 * @return
	 */
	public static boolean check(String value) {
		try {
			valueOf(value.toUpperCase());
		} catch (IllegalArgumentException e) {
			return false;
		}
		return true;
	}
}
```

**Comment by 0xbaadf00d** [comment]
i think is useless to keep a list of reserved words. It makes more sense to quote all fields name on the generated query.

**Comment by PierreAdam** [comment]
The Enum solution would be at my opinion a bad one. If new keyword get added for some reason in a supported type of SQL server, it would require to change the Enum. Plus this Enum would have basically no other purpose than serving as a "blacklist". Better quote all the fields from the query and be safe whatever happen.

**Comment by rPraml** [comment]
Ok, as said above 
> I would suggest, to quote everything
but I don't want to do that manually.
So is there an option in Ebean that all property names are quoted everywhere and correct for every platform?

**Comment by 0xbaadf00d** [comment]
You don't have to do this manually, except if you use non managed raw SQL query.

**Comment by rPraml** [comment]
I don't use unparsed SQL, I use simple entities like this:
```java
@Entity
public class Table {
  @Id
  private int order;
  @Index(unique=true)
  private String constraint;
  private String varchar;
  private MNonEnum join;
}
```
This generates a "create table table ... " DDL statement which fails, because it contains a lot of (=only) reserved words.

If I manually quote each value (see below), the generated DDL statements look correct
but I don't want to annotate each property with @Column / @Table 

Entity:
```java
@Entity
@javax.persistence.Table(name = "`table`")
public class Table {

  @Id
  @Column(name="`order`")
  private int order;

  @Index(unique=true)
  @Column(name="`constraint`")
  private String constraint;

  @Column(name="`varchar`")
  private String varchar;

  @Column(name="`join`")
  private MNonEnum join;
}
```
resulting DDL (for MS-SQL e.g.)
```sql
create table [table] (
  [order]                       integer identity(1,1) not null,
  [constraint]                  varchar(255),
  [varchar]                     varchar(255),
  [join]                        varchar(5),
  constraint ck_table_join check ( [join] in ('BEGIN','END')),
  constraint uq_table_constraint unique ([constraint]),
  constraint pk_table primary key ([order])
);
```

**Comment by 0xbaadf00d** [comment]
yeah is exactly what I try to tell you: it the purpose of Ebean to quote ALL bean field names on the generated query.  ALL without exception to avoid to iterate/find on a list / enum array (performance issue + possible outdated list).

**Comment by rbygrave** [comment]
Ok, changing this to an enhancement request ... ability (via ServerConfig) to globally turn on quoted identifiers.

**Comment by 0xbaadf00d** [comment]
Hi @rbygrave,

any news about this great feature ? We are just falling into this case with a client who don't want using anything else that MSSQL 2016 (and regarding to our others clients, we can't destroy the current tablename  convention just for 1 client).

Sincerely

**Comment by rbygrave** [comment]
Ok, let me see if I can look at this over the next day or two.

**Comment by rbygrave** [comment]
So on ServerConfig there is now a `allQuotedIdentifiers` boolean.  When this is set to true Ebean will use quoted identifiers for all db table and column names ... and generally it will change the namingConvention to MatchingNamingConvention (if it is UnderscoreNamingConvention).

The resulting DDL and DML use quoted identifies.  An example insert for sql server looks like:

```sql
insert into [customer] ([inactive], [name], [registered], [comments], [version], [whenCreated], [whenUpdated], [billingAddressId], [shippingAddressId]) values (?,?,?,?,?,?,?,?,?);
```
