### ISSUE TITLE
Error - Can't fetch JsonDB field - org.postgresql.util.PSQLException: ERROR: could not identify an equality operator for type json

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#900]
Ebean version 9.1.2

We can't use `.fetch("settings", "field")` where _field_ is annotated with @DbJson. Using only `.fetch("settings")` works, but in this case we don't want to retrieve all columns, we only need paypalSettings.

```java
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

```java
ContractModel.find
            .select("id,uid")
            .fetch("settings", "paypalSettings")
            .where()
            .eq("payoutRequests.status", PayoutRequestStatus.SCHEDULED)
            .eq("payoutRequests.payoutMethod", PaymentMethod.PAYPAL)
            .isNull("payoutRequests.payoutId")
            .isNull("payoutRequests.payoutBatchId")
            .findEach(this::pushPayoutRequestOnPaypalBatch);
```

```java
@DbJson
@Column(name = "paypal_settings")
private Map<String, Object> paypalSettings;
```

```console
[error] a.a.OneForOneStrategy - Query threw SQLException:ERROR: could not identify an equality operator for type json
  Position : 48 
Bind values:[SCHEDULED,PAYPAL] 
Query was:
select distinct t0.id c0, t0.uid c1, t1.id c2, t1.paypal_settings c3 from contract t0 join contract_settings t1 on t1.contract_id = t0.id  join payout_request u1 on u1.contract_id = t0.id  where u1.status = ?  and u1.method = ?  and u1.payout_id is null  and u1.payout_batch_id is null  


javax.persistence.PersistenceException: Query threw SQLException:ERROR: could not identify an equality operator for type json
  Position : 48 
Bind values:[SCHEDULED,PAYPAL] 
Query was:
select distinct t0.id c0, t0.uid c1, t1.id c2, t1.paypal_settings c3 from contract t0 join contract_settings t1 on t1.contract_id = t0.id  join payout_request u1 on u1.contract_id = t0.id  where u1.status = ?  and u1.method = ?  and u1.payout_id is null  and u1.payout_batch_id is null  


    at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:680)
    at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:660)
    at com.avaje.ebeaninternal.server.query.CQueryEngine.findIterate(CQueryEngine.java:209)
    at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIterate(DefaultOrmQueryEngine.java:84)
    at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findEach(OrmQueryRequest.java:312)
    at com.avaje.ebeaninternal.server.core.DefaultServer.findEach(DefaultServer.java:1332)
    at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findEach(DefaultOrmQuery.java:1112)
    at com.avaje.ebeaninternal.server.expression.DefaultExpressionList.findEach(DefaultExpressionList.java:357)
    at actors.SyncPayoutRequestActor.pushPayoutRequestOnPaypal(SyncPayoutRequestActor.java:306)
    at actors.SyncPayoutRequestActor.onReceive(SyncPayoutRequestActor.java:153)
Caused by: org.postgresql.util.PSQLException: ERROR: could not identify an equality operator for type json
  Position : 48
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:171)
    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:119)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:355)
```

**Comment by rbygrave** [comment]
This looks like a limitation of the JSON type in a SQL query that includes distinct.

1 -  If JSONB was used in PG 9.4+ ... it should work in theory
2 - If distinct was not on the query ... is should work (so try removing the predicates on the many to confirm that)
3 - If distinct on (...) is used ... the query should work

Reference  http://stackoverflow.com/questions/23509740/distinct-on-postgresql-json-data-column

Do you want to confirm 2 and 3 ?

**Comment by 0xbaadf00d** [comment]
2 => It working
3 => 

```sql
SELECT DISTINCT ON (t1.paypal_settings)
  t0.id              c0,
  t0.uid             c1,
  t1.id              c2,
  t1.paypal_settings c3
FROM contract t0
  JOIN contract_settings t1 ON t1.contract_id = t0.id
  JOIN payout_request u1 ON u1.contract_id = t0.id
WHERE u1.status = 1 AND u1.method = 1 AND u1.payout_id IS NULL AND u1.payout_batch_id IS NULL
```

```console
[42883] ERROR: could not identify an equality operator for type json Position : 21
```

**Comment by 0xbaadf00d** [comment]
Hi @rbygrave ,

any news about this issue ?

Thanks

**Comment by rbygrave** [comment]
Not really, in that I decided I need to "bite the bullet" on the io.ebean package change get that done if I could (and I'm pretty much done - just noted that the multi-tenant support introduced an issue for ebean-elastic).

I should be able to look at this my Thursday (Xmas event tomorrow night).

Now that said, you can use the new findNative() method as a workaround (or RawSql of course).

```java
// if java had multi-line strings ...
String sql = """
SELECT DISTINCT ON (t1.id)
  t0.id              ,
  t0.uid             ,
  t1.id              ,
  t1.paypal_settings
FROM contract t0
  JOIN contract_settings t1 ON t1.contract_id = t0.id
  JOIN payout_request u1 ON u1.contract_id = t0.id
WHERE u1.status = 1 AND u1.method = 1 AND u1.payout_id IS NULL AND u1.payout_batch_id IS NULL
"""

List<Contract> contracts  = 
  Ebean.findNative(Contract.class, sql).findList();
```

**Comment by rbygrave** [comment]
So the fix here is to for Postgres use `distinct on` which is made of the merge of the db order by clause and the id properties of the root type (and many root type if there is a fetch many).
