### ISSUE TITLE
NullPointerException on no version provided (when setVersion(null) is used)

### ISSUE THREAD

**Issue by IvanAR** [ebean-orm/ebean#963]
## Expected behavior
A more clear exception message for the user or provide a better treatment in the code

## Actual behavior
NullPointerException when trying to cast a null value to Long

### Steps to reproduce
Send a update with @Version field == null

Inside GeneratedCounterLong
```java
  @Override
  public Object getUpdateValue(BeanProperty prop, EntityBean bean, long now) {
    Long i = (Long) prop.getValue(bean);
    return i + 1;
  }
```

```console
java.lang.NullPointerException: null
	at com.avaje.ebeaninternal.server.deploy.generatedproperty.GeneratedCounterLong.getUpdateValue(GeneratedCounterLong.java:29)
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindablePropertyUpdateGenerated.dmlBind(BindablePropertyUpdateGenerated.java:40)
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableList.dmlBind(BindableList.java:59)
	at com.avaje.ebeaninternal.server.persist.dml.UpdatePlan.bindSet(UpdatePlan.java:56)
	at com.avaje.ebeaninternal.server.persist.dml.UpdateMeta.bind(UpdateMeta.java:68)
	at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.bind(UpdateHandler.java:49)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:69)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:59)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeUpdate(PersistRequestBean.java:1087)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:672)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:710)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:477)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:367)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:347)
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1478)
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1471)
```

**Comment by rbygrave** [comment]
Hi, We ideally want to know (via example code or test case) how to reproduce this issue.  This gives us the context for when/why this error is produced.

I can see there is an update() being executed but we really would like an example of the code (such that we can create a failing test case and then fix it).

Thanks, Rob.

**Comment by IvanAR** [comment]
https://github.com/IvanAR/example-java8/blob/master/src/test/java/org/example/domain/UpdateCustomerTest.java

**Comment by rbygrave** [comment]
Test case:

```java
    @Test
    public void update(){
        Customer customer = new Customer("Ivan");

        Ebean.insert(customer);

        customer.setComments("Any comments");
        // Version is now set to NULL
        customer.setVersion(null);

        Ebean.update(customer);
    }
```

**Comment by rbygrave** [comment]
At this point I don't think we should "fix" this issue.  The code explicitly setting the version to null leads to this NPE and I don't know when it would be good to not NPE as we are better off fixing the underlying cause.

So, I'll close this as "won't fix" unless there is some compelling reason/use case.

**Comment by rbygrave** [comment]
Closing, reopen if desired.

**Comment by IvanAR** [comment]
Hi Rob, explaining our scenario. I had some developers doing an insert on a Jerser REST server, and after this, trying to make an update without retrieving the updated resource with new version.  
With this, the second data sent had Version == null, resulting on a NPE, no problem with that, but the suggestion was just to set a better message on exception, because we had to debug ebean code to discover the real problem.

**Comment by rbygrave** [comment]
Ok, will review.
